import { makeColumnConfigs, mcc } from "./columnConfigBuilder";

export const columnConfigs = makeColumnConfigs({
  spreadsheetControls: {
    fillRowIdsLastRan: mcc(
      "col-045qGg4",
      "string",
      "Fill row IDs, last ran",
      false,
    ),
    fillRowIdsRunAndStatus: mcc(
      "col-0g24qGg",
      "string",
      "Fill row IDs, run and status",
      false,
    ),
    appendSheetAndColumnConfigRowsLastRan: mcc(
      "col-0g340Gg",
      "string",
      "Append sheet and column config rows, last ran",
      false,
    ),
    appendSheetAndColumnConfigRowsRunAndStatus: mcc(
      "col-0g34slk",
      "string",
      "Append sheet and column config rows, run and status",
      false,
    ),
  },
  addExpenses: {
    date: mcc("col-vXNHJps", "string", "Date", false),
    propertyName: mcc("col-_iOHEPj", "string", "Property name", false),
    unitName: mcc("col-OBqodd0", "string", "Unit name", false),
    billerName: mcc("col-xp4RR28", "string", "Biller name", false),
    description: mcc("col-pRON8SW", "string", "Description", false),
    amount: mcc("col-sE7oAfr", "string", "Amount", false),
    expenseCategory: mcc(
      "col-vgdpQaI",
      "expenseCategory",
      "Expense category",
      false,
    ),
    taxAdjust: mcc("col-T6Qbxvk", "residenceTaxAdjust", "Tax adjust", false),
    receiptFormat: mcc("col-yQtzinN", "receiptFormat", "Receipt format", false),
    notes: mcc("col-V7s3k7A", "string", "Notes", false),
    householdToCharge: mcc(
      "col-nGxFx4D",
      "string",
      "Household to charge",
      false,
    ),
    householdChargeLesserAmount: mcc(
      "col-OLIOifY",
      "string",
      "Household charge lesser amount",
      false,
    ),
    hhChargeNotes: mcc("col-6w_8wXP", "string", "HH charge notes", false),
    householdId: mcc("col-Mx2BiCo", "string", "Household ID", true),
    id: mcc("col-Wn1oOom", "string", "ID", true),
    propertyId: mcc("col-7hwOnld", "string", "Property ID", true),
    unitId: mcc("col-6mhn61V", "string", "Unit ID", true),
    enter: mcc("col-wipvQ46", "boolean", "Enter", false),
    enterStatus: mcc("col-jFOlWsa", "string", "Enter status", false),
  },
  addHhPaymentOnetime: {
    householdName: mcc("col-JxtgYhJ", "string", "Household name", false),
    portion: mcc("col-9qc_UOo", "rentPortionName", "Portion", false),
    description: mcc("col-OBqwLsb", "chargeDescription", "Description", false),
    amount: mcc("col-6Z-g6aN", "string", "Amount", false),
    unitName: mcc("col-YP9kC8o", "string", "Unit name", true),
    subsidyAgreementName: mcc(
      "col-Ligyt6Y",
      "string",
      "Subsidy agreement name",
      false,
    ),
    id: mcc("col-kU0tGW_", "string", "ID", true),
    householdId: mcc("col-noXL_e_", "string", "Household ID", true),
    unitId: mcc("col-fzBlkyl", "string", "Unit ID", true),
    subsidyAgreementId: mcc(
      "col--w2ekts",
      "string",
      "Subsidy agreement ID",
      true,
    ),
    date: mcc("col-u5S1p53", "date", "Date", true),
    detailsVerified: mcc("col-Wb5wdwz", "string", "Details verified", false),
    payerCategory: mcc("col-bXBsrNU", "payerCategory", "Payer category", false),
    paymentHhName: mcc("col-Y7a0Yut", "string", "Payment HH name", true),
    subsidyProgramName: mcc(
      "col-DHgo-6o",
      "string",
      "Subsidy program name",
      false,
    ),
    otherPayerName: mcc("col-W7b2hGx", "string", "Other payer name", false),
    paymentHhId: mcc("col-TGUKG69", "string", "Payment HH ID", true),
    subsidyProgramId: mcc("col-XedCXAM", "string", "Subsidy program ID", true),
    otherPayerId: mcc("col-OYsbh1q", "string", "Other payer ID", true),
    notes: mcc("col-KTl705t", "string", "Notes", false),
    enter: mcc("col-6PNfr_e", "boolean", "Enter", false),
    enterStatus: mcc("col-OHc-nd9", "string", "Enter status", false),
  },
  addOccChargeOnetime: {
    date: mcc("col-RcPqzF2", "date", "Date", true),
    householdName: mcc("col-olQUfAZ", "string", "Household name", false),
    amount: mcc("col-wS5UkZR", "string", "Amount", false),
    description: mcc(
      "col-fq3Wkwf",
      "chargeOnetimeDescription",
      "Description",
      false,
    ),
    unitName: mcc("col-A18WumZ", "string", "Unit name", true),
    householdId: mcc("col-S0LLFch", "string", "Household ID", true),
    unitId: mcc("col-43FJGcv", "string", "Unit ID", true),
    notes: mcc("col-rEqlwlw", "string", "Notes", false),
    id: mcc("col-VG-Y2z7", "string", "ID", true),
    enter: mcc("col-auSNCDT", "boolean", "Enter", false),
    enterStatus: mcc("col-MuVUEGl", "string", "Enter status", false),
  },
  columnConfig: {
    id: mcc("col-K9DptS1", "string", "ID", false),
    sheetName: mcc("col-U6y6xUt", "string", "Sheet name camel case", false),
    columnIndexBase0: mcc(
      "col-83ENHF2",
      "number",
      "Column index base 0",
      false,
    ),
    header: mcc("col-imgVzE3", "string", "Header", false),
    camelCaseHeader: mcc("col-wHrc1Q3", "string", "Camel case header", false),
    isFormula: mcc("col-F2caCWz", "boolean", "Is formula", false),
    valueName: mcc("col-PeplPjS", "string", "Value name", false),
    emptyAllowed: mcc("col-chk-U97", "boolean", "Empty allowed", false),
    customDefaultValue: mcc(
      "col-mdbDepg",
      "string",
      "Custom default value",
      false,
    ),
  },
  sheetConfig: {
    id: mcc("col-90lQMkS", "string", "ID", true),
    sheetGid: mcc("col-fqCrMdm", "number", "Sheet GID", false),
    sheetName: mcc("col-ssYwA1T", "string", "Sheet name camel case", false),
    idPrefix: mcc("col-iqW3fCT", "string", "ID prefix", false),
  },
  api: {
    id: mcc("col-ohQJSZw", "string", "ID", true),
    ulsLastRan: mcc("col-o3z5zKF", "string", "ULS last ran", false),
    ulsEnter: mcc("col-H147sTm", "boolean", "ULS enter", false),
    ulsEnterStatus: mcc("col-2Hh5Tiv", "string", "ULS enter status", false),
    upcLastRan: mcc("col-MVPM3jg", "string", "UPC last ran", false),
    upcStartMonth: mcc("col-dBUrfx_", "date", "UPC start month", false),
    upcEndMonth: mcc("col-QIU-hI6", "date", "UPC end month", false),
    upcMode: mcc("col-lw1GArS", "oneOccupancyOrAll", "UPC mode", false),
    upcHousehold: mcc("col-JAZwV4Z", "string", "UPC household", false),
    upcHouseholdId: mcc("col-jL103Fz", "string", "UPC household ID", true),
    upcEnter: mcc("col-2CcZP7l", "boolean", "UPC enter", false),
    upcEnterStatus: mcc("col-7zKZtJP", "string", "UPC enter status", false),
    aepLastRan: mcc("col-NpC_m7j", "string", "AEP last ran", false),
    aepEnter: mcc("col-SkBfBWg", "boolean", "AEP enter", false),
    aepEnterStatus: mcc("col-lhC7IXV", "string", "AEP enter status", false),
    bhlLastRan: mcc("col-s3TA0Js", "date", "BHL last ran", false),
    bhlLastRanHouseholdAndUnit: mcc(
      "col-koaPkot",
      "string",
      "BHL last ran household and unit",
      true,
    ),
    bhlHouseholdIdLastRan: mcc(
      "col-Bt_hiLJ",
      "string",
      "BHL household ID last ran",
      false,
    ),
    bhlUnitIdLastRan: mcc(
      "col-YgNpwF1",
      "string",
      "BHL unit ID last ran",
      true,
    ),
    bhlHouseholdName: mcc("col-qbSdWm7", "string", "BHL household name", false),
    bhlHouseholdId: mcc("col-L2Vwjlr", "string", "BHL household ID", true),
    bhlPortion: mcc("col-66PEBlM", "rentPortionName", "BHL portion", false),
    bhlSubsidyAgreementName: mcc(
      "col-7Dl8V9w",
      "string",
      "BHL subsidy agreement name",
      false,
    ),
    bhlSubsidyAgreementId: mcc(
      "col--Cx2izo",
      "string",
      "BHL subsidy agreement ID",
      true,
    ),
    bhlEnter: mcc("col-bBZV44s", "boolean", "BHL enter", false),
    bhlEnterStatus: mcc("col-VHVRiOc", "string", "BHL enter status", false),
  },
  biller: {
    name: mcc("col-IAA7ymg", "string", "Name", false),
    contact: mcc("col-TECY-w9", "string", "Contact", false),
    id: mcc("col-pBwZ74w", "string", "ID", true),
    category: mcc("col-HmUfHCe", "string", "Category", false),
    defaultExpenseCategory: mcc(
      "col-lZdCfdb",
      "string",
      "Default expense category",
      false,
    ),
    defaultExpenseDescription: mcc(
      "col-Q7pTk6J",
      "string",
      "Default expense description",
      false,
    ),
    notes: mcc("col-ioUEJuB", "string", "Notes", false),
  },
  buildOccLedger: {
    dateLastRan: mcc("col-56paOQ6", "date", "Date last ran", false),
    householdIdLastRan: mcc(
      "col-h8wdhIm",
      "string",
      "Household ID last ran",
      false,
    ),
    unitIdLastRan: mcc("col-kN5w1ui", "string", "Unit ID last ran", true),
    occupancyName: mcc("col-2IST_DW", "string", "Occupancy name", false),
    portion: mcc("col-javENeZ", "rentPortionName", "Portion", false),
    householdId: mcc("col-9K87DiZ", "string", "Household ID", true),
    subsidyAgreementName: mcc(
      "col-pJqCDM_",
      "string",
      "Subsidy agreement name",
      false,
    ),
    subsidyAgreementId: mcc(
      "col-bdXnDU7",
      "string",
      "Subsidy agreement ID",
      true,
    ),
    id: mcc("col-qFYr3BR", "string", "ID", true),
    enter: mcc("col-0pQVFbo", "boolean", "Enter", false),
    enterStatus: mcc("col-NReu6z0", "string", "Enter status", false),
  },
  businessExpense: {
    date: mcc("col-viByQSW", "date", "Date", false),
    amount: mcc("col-wH6T9oD", "number", "Amount", false),
    description: mcc("col-sGzmf3i", "string", "Description", false),
    deductibleAmount: mcc("col-D4Um8gD", "string", "Deductible amount", true),
    id: mcc("col-gI3wWFP", "string", "ID", true),
    billerName: mcc("col-ws-Kl9O", "string", "Biller name", false),
    expenseCategory: mcc(
      "col-1FLurWI",
      "expenseCategory",
      "Expense category",
      false,
    ),
    receiptFormat: mcc("col-PXfEBEq", "receiptFormat", "Receipt format", false),
    taxAdjust: mcc("col-FjnqqGg", "residenceTaxAdjust", "Tax adjust", false),
    notes: mcc("col--TmFGAd", "string", "Notes", false),
  },
  capex: {
    id: mcc("col-A_L0nQO", "string", "ID", false),
    name: mcc("col-wQVendk", "string", "Name", false),
    unitCost: mcc("col-zeNzhyO", "number", "Unit cost", false),
    propertyMultiplierName: mcc(
      "col-ZTAY92_",
      "string",
      "Property multiplier name",
      false,
    ),
    lifespanYears: mcc("col-U6_ZT0o", "number", "Lifespan years", false),
    lifespanMonths: mcc("col-YqvaRuI", "number", "Lifespan months", true),
    preference: mcc("col-4zmF0qs", "string", "Preference", false),
  },
  spreadsheetConfig: {
    id: mcc("col-LAM-LoC", "string", "ID", false),
    headerRowIndexBase1: mcc(
      "col-hOXiFmz",
      "number",
      "Header row idx base 1",
      false,
    ),
    topDataRowIdxBase1: mcc(
      "col-DZ4VSLw",
      "number",
      "Top body row idx base 1",
      false,
    ),
    columnIdRowIdxBase1: mcc(
      "col-4ySoLne",
      "number",
      "Column id row idx base 1",
      false,
    ),
    idDelimiter: mcc("col-zR-sehH", "string", "ID delimiter", false),
    activePaymentStandardYear: mcc(
      "col-mW2UEKf",
      "number",
      "Active payment standard year",
      false,
    ),
    domLateFeeCharged: mcc(
      "col-ZsjeOd2",
      "number",
      "DOM late fee charged",
      false,
    ),
  },
  export: {
    id: mcc("col-7HTLbQE", "string", "ID", false),
    necessaryAverageCostsMonthly: mcc(
      "col-iE08rV_",
      "number",
      "Necessary average costs monthly",
      true,
    ),
    subsidyPaymentsMonthly: mcc(
      "col-c2XXKTP",
      "number",
      "Subsidy payments monthly",
      true,
    ),
    tenantPaymentsMonthly: mcc(
      "col-vb-UnbW",
      "string",
      "Tenant payments monthly",
      true,
    ),
    realEstateCostsMinusTenantPayments: mcc(
      "col-nQar3gw",
      "string",
      "Real estate costs minus tenant payments",
      true,
    ),
    businessCheckingBalance: mcc(
      "col-b684Igh",
      "number",
      "Business checking balance",
      true,
    ),
    businessCheckingBalanceMinusNextBankPayments: mcc(
      "col-M1iFwht",
      "number",
      "Business checking balance minus next bank payments",
      true,
    ),
  },
  finance: {
    id: mcc("col-rXqzRW-", "string", "ID", false),
    businessAccountBankPaymentCushion: mcc(
      "col-VttZ8-h",
      "number",
      "Business account bank payment cushion",
      true,
    ),
    businessCashAccount: mcc(
      "col-E5Sd1yv",
      "number",
      "Business Cash Account",
      true,
    ),
    businessAccountDebt: mcc(
      "col-qLIGagR",
      "number",
      "Business Account Debt",
      true,
    ),
    helocAvailable: mcc("col-8eXfJd9", "number", "HELOC available", true),
    helocSpent: mcc("col-dypG3j3", "number", "HELOC spent", true),
    bankUtilityPaymentsMonthlyAvg: mcc(
      "col-UkNYRTj",
      "number",
      "Bank + utility payments monthly avg",
      true,
    ),
    bankPaymentsMonthly: mcc(
      "col-RuG2S80",
      "number",
      "Bank payments monthly",
      true,
    ),
    mortgagePaymentsMonthly: mcc(
      "col-GJ3W5CH",
      "number",
      "Mortgage payments monthly",
      true,
    ),
    helocPaymentsMonthly: mcc(
      "col-_F9eVFO",
      "number",
      "HELOC payments monthly",
      true,
    ),
    utilityPaymentsMonthlyAvg: mcc(
      "col-WNSnm31",
      "number",
      "Utility payments monthly avg",
      true,
    ),
    budgetsMonthly: mcc("col-LqC3tvw", "number", "Budgets monthly", true),
    maintenanceBudgetMonthly: mcc(
      "col-Usg-WMU",
      "number",
      "Maintenance budget monthly",
      true,
    ),
    lawncareBudgetMonthly: mcc(
      "col-USPILuC",
      "number",
      "Lawncare budget monthly",
      true,
    ),
    capExBudgetMonthly: mcc(
      "col-zrcshgj",
      "number",
      "Cap-Ex budget monthly",
      true,
    ),
    vacancyBudgetMonthly: mcc(
      "col-0MFgFfN",
      "number",
      "Vacancy budget monthly",
      true,
    ),
    flexibleIncomeMonthlyAvg: mcc(
      "col-Kctzpyn",
      "string",
      "Flexible income monthly avg",
      true,
    ),
    discretionaryIncomeMonthlyAvg: mcc(
      "col-S4V6HuT",
      "string",
      "Discretionary income monthly avg",
      true,
    ),
    realEstateReceivableMonthly: mcc(
      "col-pCYNnOt",
      "string",
      "Real estate receivable monthly",
      true,
    ),
    subsidyIncomeMonthly: mcc(
      "col-ojc6Pj3",
      "number",
      "Subsidy income Monthly",
      true,
    ),
    tenantIncomeMonthly: mcc(
      "col-fSe_zos",
      "string",
      "Tenant income Monthly",
      true,
    ),
  },
  furnace: {
    name: mcc("col-WgcleWq", "string", "Name", true),
    id: mcc("col-pjjrcyC", "string", "ID", true),
    propertyId: mcc("col-qM5MaTT", "string", "Property ID", false),
    propertyName: mcc("col-MDkBZw7", "string", "Property name", true),
    location: mcc("col--nrSW5N", "string", "Location", false),
    descriptor: mcc("col-3IqlZi_", "string", "Descriptor", false),
    brand: mcc("col-19ohP9V", "string", "Brand", false),
    yearBuilt: mcc("col-Jv4pMFL", "number", "Year built", false),
    age: mcc("col-333qv5F", "number", "Age", true),
    filterSize: mcc("col-sPRYcYC", "string", "Filter size", false),
    filterLocation: mcc("col-aOWKf6H", "string", "Filter location", false),
    filtersPresent: mcc("col-Q5FZff_", "number", "Filters present", false),
    filterLastReplaced: mcc(
      "col-VnZPpE8",
      "date",
      "Filter last replaced",
      false,
    ),
  },
  hhLedger: {
    date: mcc("col-9fBrgEn", "string", "Date", false),
    id: mcc("col-K6z58MJ", "string", "ID", true),
    unit: mcc("col-Gp-A2rX", "string", "Unit", false),
    issuer: mcc("col-6w2_q8O", "string", "Issuer", false),
    description: mcc("col-NUiKLPH", "string", "Description", false),
    charge: mcc("col-Uty4AVV", "string", "Charge", false),
    payment: mcc("col-qa5Sh_a", "string", "Payment", false),
    amountOwed: mcc("col-5pNKEjq", "string", "Amount owed", true),
    notes: mcc("col-zU1zrqH", "string", "Notes", false),
  },
  household: {
    name: mcc("col--IaO_J8", "string", "Name", true),
    id: mcc("col-e0nP-e3", "string", "ID", true),
    fullName: mcc("col-YICAuy6", "string", "Full name", true),
    residentCount: mcc("col-kSe11BO", "number", "Resident count", true),
    residentFullNames: mcc(
      "col-QD287on",
      "string",
      "Resident full names",
      true,
    ),
    residentFirstNames: mcc(
      "col-iqcpd0w",
      "string",
      "Resident first names",
      true,
    ),
    isActive: mcc("col-xKY_f2p", "string", "Is active", true),
    latestOccupancyId: mcc(
      "col-hvhiRQA",
      "string",
      "Latest occupancy ID",
      true,
    ),
    unitId: mcc("col-6T5u_QM", "string", "Unit ID", true),
    unitName: mcc("col-VNunYf2", "string", "Unit name", true),
    propertyId: mcc("col-uja0Yrs", "string", "Property ID", true),
    subsidyCount: mcc("col-N3Mr2EQ", "number", "Subsidy count", true),
    nextRentNoticeDate: mcc(
      "col-bCbIa94",
      "date",
      "Next rent notice date",
      true,
    ),
    "2MonthsFromLastNotice": mcc(
      "col-Ps_QhMG",
      "date",
      "2 months from last notice",
      true,
    ),
    properNoticeBeforeNextIncrease: mcc(
      "col-nCgODfJ",
      "date",
      "Proper notice before next increase",
      true,
    ),
    properNoticeAfterNextIncrease: mcc(
      "col-GWnB0N2",
      "date",
      "Proper notice after next increase",
      true,
    ),
    lastRentNoticeDate: mcc(
      "col-FJ8iUCl",
      "date",
      "Last rent notice date",
      false,
    ),
    nextRentChangeDate: mcc(
      "col-nryi7Ib",
      "date",
      "Next rent change date",
      true,
    ),
    nextRentIncreaseDateOverride: mcc(
      "col-jnm0WWU",
      "string",
      "Next rent increase date override",
      false,
    ),
    nextIncreaseDateIfNoticeNotGiven: mcc(
      "col-pFdQ2wc",
      "date",
      "Next increase date if notice not given",
      true,
    ),
    nextIncreaseDateIfNoticeGiven: mcc(
      "col-jS7wkf6",
      "date",
      "Next increase date if notice given",
      true,
    ),
    increaseAnnualDate: mcc(
      "col--UUuPBE",
      "date",
      "Increase annual date",
      true,
    ),
    currentLeaseId: mcc("col-NTsT2xI", "string", "Current lease ID", false),
    lastRentChangeDate: mcc(
      "col-Y0_rdiQ",
      "date",
      "Last rent change date",
      true,
    ),
    firstRentChargeDate: mcc(
      "col-alSTrIH",
      "string",
      "First rent charge date",
      true,
    ),
    lastDayRented: mcc("col-XePDi4w", "date", "Last day rented", true),
    baseRentChargeMonthly: mcc(
      "col-BxUxPE3",
      "number",
      "Base rent charge monthly",
      true,
    ),
    nextBaseRentChargeMonthly: mcc(
      "col-BjuCaR7",
      "number",
      "Next base rent charge monthly",
      true,
    ),
    increaseBy: mcc("col-Ld9NSxu", "number", "Increase by %", true),
    nextRentChargeOverride: mcc(
      "col-DDMUsEe",
      "string",
      "Next rent charge override",
      false,
    ),
    increaseByOverride: mcc(
      "col-DzDssB7",
      "string",
      "Increase by % override",
      false,
    ),
    increaseBy3PerYear: mcc(
      "col-cUIfPaL",
      "number",
      "Increase by 3% per year",
      true,
    ),
    nextMinusLastIncreaseYears: mcc(
      "col-fEFknBM",
      "number",
      "Next minus last increase years",
      true,
    ),
    daysInNextRentIncreaseYear: mcc(
      "col-qdUg1o-",
      "number",
      "Days in next rent increase year",
      true,
    ),
    rentReasonablenessBaseRentMax: mcc(
      "col-1tbaSjP",
      "string",
      "Rent reasonableness base rent max",
      true,
    ),
    nextGrossRentMonthly: mcc(
      "col-6vZwa1y",
      "string",
      "Next gross rent monthly",
      true,
    ),
    grossRentMonthly: mcc("col-FXIspcm", "string", "Gross rent monthly", true),
    rentReasonablenessGrossRentMax: mcc(
      "col-lmqcCkk",
      "string",
      "Rent reasonableness gross rent max",
      true,
    ),
    rentCompType: mcc("col-rsTDTeF", "string", "Rent comp type", true),
    paymentStandardGrossRentMax: mcc(
      "col-szqb-Cu",
      "string",
      "Payment standard gross rent max",
      true,
    ),
    paymentStandardUtilities: mcc(
      "col-8FfdKef",
      "string",
      "Payment standard utilities",
      true,
    ),
    paymentStandardName: mcc(
      "col-OgGGOhY",
      "string",
      "Payment standard name",
      true,
    ),
    gasHeating: mcc("col-RWqNDKN", "boolean", "Gas Heating", false),
    electricHeating: mcc("col-s6dJhNw", "boolean", "Electric Heating", false),
    gasCooking: mcc("col-lTFdWvg", "boolean", "Gas Cooking", false),
    electricCooking: mcc("col-JkMRVe3", "boolean", "Electric Cooking", false),
    otherElectric: mcc("col-OT1NP05", "boolean", "Other Electric", false),
    gasWaterHeating: mcc("col-1u19gB4", "boolean", "Gas Water Heating", false),
    electricWaterHeating: mcc(
      "col-c8031x6",
      "boolean",
      "Electric Water Heating",
      false,
    ),
    waterSewer: mcc("col-d96lUou", "boolean", "Water & Sewer", false),
    trashCollection: mcc("col-uYwbwrh", "boolean", "Trash Collection", false),
    districtEnergyHeating: mcc(
      "col-C6cHg7u",
      "boolean",
      "District Energy Heating",
      false,
    ),
    districtEnergyWaterHeating: mcc(
      "col-N6LwTYC",
      "boolean",
      "District Energy Water Heating",
      false,
    ),
    netChargeMonthly: mcc("col-W735ss-", "string", "Net charge monthly", true),
    caretakerRentReductionMonthly: mcc(
      "col-VlkCkKM",
      "string",
      "Caretaker rent reduction monthly",
      true,
    ),
    petFeeMonthly: mcc("col-ZYvV_a2", "number", "Pet fee monthly", true),
    hhTotalPaymentMonthly: mcc(
      "col-WOCcFgo",
      "string",
      "HH total payment monthly",
      true,
    ),
    hhBaseRentPortionMonthly: mcc(
      "col-iWlLmUs",
      "number",
      "HH base rent portion monthly",
      true,
    ),
    subsidyRentPortionMonthly: mcc(
      "col-0S-3LvX",
      "number",
      "Subsidy rent portion monthly",
      true,
    ),
    currentHhBalance: mcc("col-T3P1irS", "string", "Current hh balance", true),
    totalHhCharges: mcc("col-oaHTV9l", "string", "Total hh charges", true),
    totalHhPayments: mcc("col-D6EPFV3", "string", "Total hh payments", true),
    depositCharged: mcc("col-ft6MFJu", "number", "Deposit charged", true),
    depositReceived: mcc("col-FDyT3Vx", "number", "Deposit received", true),
    currentSubsidyBalance: mcc(
      "col-0OkeFPc",
      "string",
      "Current subsidy balance",
      true,
    ),
    totalSubsidyCharges: mcc(
      "col-owX13pV",
      "string",
      "Total subsidy charges",
      true,
    ),
    totalSubsidyPayments: mcc(
      "col-829U06m",
      "string",
      "Total subsidy payments",
      true,
    ),
    grandPaymentTotalForTaxes: mcc(
      "col-A2Xqlyb",
      "string",
      "Grand payment total for taxes",
      false,
    ),
    tenantPaymentTotalForTaxes: mcc(
      "col-aDrn-R0",
      "string",
      "Tenant payment total for taxes",
      false,
    ),
    phaPaymentTotalForTaxes: mcc(
      "col-dDeXl-9",
      "string",
      "PHA payment total for taxes",
      false,
    ),
  },
  householdProspect: {
    name: mcc("col-pMwl8_N", "string", "Name", false),
    id: mcc("col-cqj4thW", "string", "ID", true),
    totalIncomeMonthly: mcc(
      "col-7k3rBt_",
      "number",
      "Total income monthly",
      true,
    ),
    dependents: mcc("col-grW56Jj", "number", "Dependents", false),
    pets: mcc("col-xXB1s_l", "string", "Pets", false),
  },
  householdYear: {
    name: mcc("col-j48UWNj", "string", "Name", true),
    id: mcc("col-slPqvjH", "string", "ID", true),
    occupancyId: mcc("col-5NpZpfU", "string", "Occupancy ID", false),
    year: mcc("col-JPQvvQo", "number", "Year", false),
    residentCount: mcc("col-bvqNtvg", "number", "Resident count", true),
    householdRentPaidPerResident: mcc(
      "col-tzpNLQZ",
      "number",
      "Household rent paid per resident",
      true,
    ),
    caretakerRentReducedPerResident: mcc(
      "col-FIAS76q",
      "number",
      "Caretaker rent reduced per resident",
      true,
    ),
    totalAttributedPerResident: mcc(
      "col-nXoe3eF",
      "number",
      "Total attributed per resident",
      true,
    ),
    totalAttributedToOccupancy: mcc(
      "col-dD8eVIq",
      "number",
      "Total attributed to occupancy",
      true,
    ),
    caretakerRentReduced: mcc(
      "col-55cJEpn",
      "number",
      "Caretaker rent reduced",
      true,
    ),
    householdRentPaid: mcc(
      "col-1dAHPjH",
      "number",
      "Household rent paid",
      true,
    ),
    firstDateChargedRentInYear: mcc(
      "col-3XZvYtM",
      "date",
      "First date charged rent in year",
      true,
    ),
    lastDateChargedRentInYear: mcc(
      "col-Jm50CK4",
      "date",
      "Last date charged rent in year",
      true,
    ),
    firstRentChargeDate: mcc(
      "col-zvBywR1",
      "date",
      "First rent charge date",
      true,
    ),
    lastDateChargedRent: mcc(
      "col-0VgdtTA",
      "date",
      "Last date charged rent",
      true,
    ),
    subsidyRentPaid: mcc("col-OipY03K", "number", "Subsidy rent paid", true),
    scrollSpace: mcc("col-SqUK6d0", "string", "_scroll space", false),
  },
  materialCost: {
    id: mcc("col-uGd0dOc", "string", "ID", false),
    item: mcc("col-VH8n1pn", "string", "Item", false),
    v1Name: mcc("col-zwyYm9d", "string", "V1 name", false),
    v1Cost: mcc("col-UhEx93h", "number", "V1 cost", false),
    v1Count: mcc("col-f_qLF8F", "number", "V1 count", false),
    v2Name: mcc("col-QdlP7OT", "string", "V2 name", false),
    v2Cost: mcc("col-J9MMP8s", "string", "V2 cost", false),
  },
  nonResidentPayer: {
    name: mcc("col-K_eFNP9", "string", "Name", false),
    id: mcc("col-rrScEfG", "string", "ID", true),
  },
  occCharge: {
    name: mcc("col-udxK-Hf", "string", "Name", true),
    id: mcc("col-nLiqq-6", "string", "ID", true),
    occupancyId: mcc("col-IrTjVUr", "string", "Occupancy ID", false),
    occupancyName: mcc("col-VGP6Bgk", "string", "Occupancy name", true),
    date: mcc("col-rdw667_", "date", "Date", false),
    description: mcc("col-Z5b__-f", "string", "Description", false),
    amount: mcc("col-bDbtLKn", "number", "Amount", false),
    amountAccounted: mcc("col-OCiouvy", "number", "Amount accounted", true),
    amountUnaccounted: mcc("col-N4oYQrk", "number", "Amount unaccounted", true),
    notes: mcc("col-wsWXgR4", "string", "Notes", false),
  },
  occChargeReduce: {
    id: mcc("col-1rSG9i_", "string", "ID", true),
    date: mcc("col-9FwOGpt", "date", "Date", false),
    chargeId: mcc("col-3zLvJOz", "string", "Charge ID", false),
    chargeName: mcc("col-pW6NptW", "string", "Charge name", true),
    description: mcc(
      "col-s_hOaKR",
      "chargeReduceDescription",
      "Description",
      false,
    ),
    chargeAmount: mcc("col-bBHlDi-", "number", "Charge amount", true),
    amount: mcc("col-kzsS2s_", "number", "Amount", true),
    reduceFullAmount: mcc(
      "col-2KKhHBO",
      "boolean",
      "Reduce full amount",
      false,
    ),
    lesserAmount: mcc("col-sRi8MA4", "string", "Lesser amount", false),
  },
  occPayAllocation: {
    name: mcc("col-EL5Jx4e", "string", "Name", true),
    occupancyName: mcc("col-vK3JZeg", "string", "Occupancy name", true),
    id: mcc("col-0RTP0fy", "string", "ID", true),
    paymentId: mcc("col-sCLgGiO", "string", "Payment id", false),
    payerCategory: mcc("col-MFTWV8M", "string", "Payer category", true),
    payerName: mcc("col-la7Ma45", "string", "Payer name", true),
    formOfPayment: mcc("col-M6W-rV_", "string", "Form of payment", true),
    paymentAllocated: mcc("col-_q_cK2F", "number", "Payment allocated", true),
    paymentDate: mcc("col-6ORlom4", "date", "Payment date", true),
    paymentAmount: mcc("col-LDzLVDD", "number", "Payment amount", true),
    chargeId: mcc("col-9zJ7Xt4", "string", "Charge id", false),
    occupancyId: mcc("col-v_hGHUV", "string", "Occupancy id", true),
    propertyId: mcc("col-fmJ3xRA", "string", "Property id", true),
    chargeDescription: mcc("col-A8yIJGL", "string", "Charge description", true),
    chargePaid: mcc("col-1uuH5TK", "number", "Charge paid", true),
    chargeDate: mcc("col-okGjzno", "date", "Charge date", true),
    chargeAmount: mcc("col-NQN3uEw", "number", "Charge amount", true),
    paymentSummary: mcc("col-aRUT8Yn", "string", "Payment summary", true),
    chargeSummary: mcc("col-_6eV_gi", "string", "Charge summary", true),
    paymentUnallocated: mcc(
      "col-EnmorGU",
      "number",
      "Payment unallocated",
      true,
    ),
    chargeUnpaid: mcc("col-Ue-A9_V", "number", "Charge unpaid", true),
    amount: mcc("col-Mz8l5TA", "number", "Amount", true),
    allocateWhat: mcc(
      "col-YZpq7hn",
      "paymentAllocateWhat",
      "Allocate what",
      false,
    ),
    lesserAmount: mcc("col-vMrDrB6", "number", "Lesser amount", false),
    filledOut: mcc("col-e9I0oXB", "string", "Filled out", true),
    processed: mcc("col-ufcTD5Q", "yesOrNo", "Processed", true),
  },
  occPayment: {
    id: mcc("col-5p14Hz-", "string", "ID", true),
    paymentName: mcc("col-JL9ycn7", "string", "Payment name", true),
    allocationName: mcc("col-HwbqxPk", "string", "Allocation name", true),
    date: mcc("col-v7ZMbTS", "date", "Date", false),
    payerCategory: mcc("col-jU98tyc", "payerCategory", "Payer category", false),
    payerName: mcc("col-W340xfW", "string", "Payer name", true),
    householdId: mcc("col-2UvItSc", "string", "Household ID", false),
    nonResidentPayerId: mcc(
      "col-Y8oUjzx",
      "string",
      "Non-resident payer ID",
      false,
    ),
    formOfPayment: mcc("col-8c4YSaF", "paymentType", "Form of payment", false),
    amount: mcc("col-UzaXtjU", "number", "Amount", false),
    detailsVerified: mcc("col-YrD2LQj", "yesOrNo", "Details verified", false),
    amountAllocated: mcc("col-SZpwM52", "number", "Amount allocated", true),
    allocationCount: mcc("col-aip45rN", "number", "Allocation count", true),
    amountUnallocated: mcc("col-3SmJeZz", "number", "Amount unallocated", true),
    processed: mcc("col-DoMfDwe", "yesOrNo", "Processed", true),
    notes: mcc("col-ZLNoGUf", "string", "Notes", false),
  },
  occupancy: {
    name: mcc("col-jHfWw_p", "string", "Name", true),
    id: mcc("col-aobYS7A", "string", "ID", true),
    householdId: mcc("col-cQbzV2A", "string", "Household ID", false),
    residentCount: mcc("col-yVuonvl", "number", "Resident count", true),
    unitId: mcc("col-OsokrlB", "string", "Unit ID", false),
    propertyId: mcc("col-d8mC6Rn", "string", "Property ID", true),
    unitStandardName: mcc("col-I4yjYPD", "string", "Unit standard name", true),
    isActive: mcc("col-tuQZLj-", "string", "Is active", true),
    firstOccupancyTermsId: mcc(
      "col-mnW1daF",
      "string",
      "First occupancy terms ID",
      true,
    ),
    activeOccupancyTermsId: mcc(
      "col-s4Zxv4D",
      "string",
      "Active occupancy terms ID",
      true,
    ),
    latestOccupancyTermsId: mcc(
      "col-EZp4_52",
      "string",
      "Latest occupancy terms ID",
      true,
    ),
    latestEndedOccupancyTermsId: mcc(
      "col-SUlG0Wm",
      "string",
      "Latest ended occupancy terms ID",
      true,
    ),
    latestOccupancyTermsStartDate: mcc(
      "col-lwvPphy",
      "date",
      "Latest occupancy terms start date",
      true,
    ),
    firstOccupancyDate: mcc(
      "col-KRlbXkL",
      "date",
      "First occupancy date",
      true,
    ),
    latestOccupancyDate: mcc(
      "col-BWZ97DV",
      "date",
      "Latest occupancy date",
      true,
    ),
    subsidyCount: mcc("col-6GjBcbG", "number", "Subsidy count", true),
    buildLedgerLastRan: mcc(
      "col-0g1jOuv",
      "date",
      "Build ledger last ran",
      false,
    ),
    buildLedgerSelect: mcc(
      "col-0g1jY1d",
      "boolean",
      "Build ledger, select",
      false,
    ),
    buildLedgerRunAndStatus: mcc(
      "col-0g1jopp",
      "string",
      "Build ledger, run and status",
      false,
    ),
  },
  occupancyTerms: {
    residentAndUnitName: mcc(
      "col-yq4jyPb",
      "string",
      "Resident and unit name",
      true,
    ),
    id: mcc("col-dcm4U7V", "string", "ID", true),
    occupancyId: mcc("col-OXD-Ek9", "string", "Occupancy ID", false),
    noticeDate: mcc("col-0dJOCyD", "string", "Notice date", false),
    startDate: mcc("col-AtT0nqz", "date", "Start date", false),
    endDate: mcc("col-nhh7hS1", "date", "End date", false),
    rentChargeMonthly: mcc(
      "col-ivd-pWw",
      "number",
      "Rent charge monthly",
      false,
    ),
    caretakerRentReductionMonthly: mcc(
      "col-h0uS5oi",
      "number",
      "Caretaker rent reduction monthly",
      false,
    ),
    petFeeMonthly: mcc("col-NXjOs5W", "number", "Pet fee monthly", false),
    gasHeating: mcc("col-mdfuos3", "boolean", "Gas Heating", false),
    electricHeating: mcc("col-C2tyPDA", "boolean", "Electric Heating", false),
    gasCooking: mcc("col-y4Tjo7G", "boolean", "Gas Cooking", false),
    electricCooking: mcc("col-J5X2by5", "boolean", "Electric Cooking", false),
    otherElectric: mcc("col-3XZWzZb", "boolean", "Other Electric", false),
    gasWaterHeating: mcc("col-5q18yvd", "boolean", "Gas Water Heating", false),
    electricWaterHeating: mcc(
      "col-hr2Ex2L",
      "boolean",
      "Electric Water Heating",
      false,
    ),
    waterSewer: mcc("col-TV-65-Y", "boolean", "Water & Sewer", false),
    trashCollection: mcc("col-ahrWo52", "boolean", "Trash Collection", false),
    districtEnergyHeating: mcc(
      "col-hgRDXpl",
      "boolean",
      "District Energy Heating",
      false,
    ),
    districtEnergyWaterHeating: mcc(
      "col-WnfDv0q",
      "boolean",
      "District Energy Water Heating",
      false,
    ),
    notes: mcc("col-9E6_E_l", "string", "Notes", false),
  },
  paymentGroup: {
    name: mcc("col-M2AcrkT", "string", "Name", false),
    id: mcc("col-8ZambHV", "string", "ID", true),
  },
  paymentStandard: {
    id: mcc("col-WSIA79A", "string", "ID", false),
    name: mcc("col-nXZJynE", "string", "Name", true),
    areaStandardName: mcc("col-LLk1Rnw", "string", "Area standard name", true),
    unitStandardName: mcc("col-_d26cZW", "string", "Unit standard name", true),
    type: mcc("col-UKMMk6d", "string", "Type", false),
    area: mcc("col-PdIqODe", "string", "Area", false),
    year: mcc("col-Vqa770-", "number", "Year", false),
    buildingType: mcc(
      "col-MciQOdX",
      "buildingTypeAndAny",
      "Building type",
      false,
    ),
    bedroomCount: mcc("col-ayrEE8U", "number", "Bedroom count", false),
    grossRent: mcc("col-2NN5vKf", "number", "Gross rent", false),
    gasHeating: mcc("col-D5Mq2iT", "number", "Gas Heating", false),
    electricHeating: mcc("col-Tk7-gts", "number", "Electric Heating", false),
    gasCooking: mcc("col-TQGm_hh", "number", "Gas Cooking", false),
    electricCooking: mcc("col-usiVwX-", "number", "Electric Cooking", false),
    gasWaterHeating: mcc("col--PXRLlq", "number", "Gas Water Heating", false),
    electricWaterHeating: mcc(
      "col-bijwMhk",
      "number",
      "Electric Water Heating",
      false,
    ),
    otherElectric: mcc("col-huaucO6", "number", "Other Electric", false),
    waterSewer: mcc("col-1GsKsEm", "number", "Water & Sewer", false),
    trashCollection: mcc("col-nAb9KBk", "number", "Trash Collection", false),
    districtEnergyHeating: mcc(
      "col-Z428AUE",
      "number",
      "District Energy Heating",
      false,
    ),
    districtEnergyWaterHeating: mcc(
      "col-3DuCyZ1",
      "number",
      "District Energy Water Heating",
      false,
    ),
    range: mcc("col-TlqPiw-", "number", "Range", false),
    refrigerator: mcc("col-kt86HvQ", "number", "Refrigerator", false),
  },
  pet: {
    id: mcc("col-UukcD_J", "string", "ID", true),
    name: mcc("col-YfYkSGo", "string", "Name", false),
    householdName: mcc("col-l9or2xk", "string", "Household name", true),
    householdId: mcc("col-0zkPeRN", "string", "Household ID", false),
    species: mcc("col-NyQH0lV", "string", "Species", false),
    breed: mcc("col-JT5K0b8", "string", "Breed", false),
    birthDateApproximate: mcc(
      "col-i_9-yIb",
      "date",
      "Birth date, approximate",
      false,
    ),
    age: mcc("col-XsopPha", "number", "Age", true),
    rentersInsuranceProofDate: mcc(
      "col--PB8t09",
      "date",
      "Renters insurance proof date",
      false,
    ),
    vaccinationProofDate: mcc(
      "col-WiA5qeP",
      "date",
      "Vaccination proof date",
      false,
    ),
    petFeeMonthly: mcc("col-uHS2k_j", "number", "Pet fee monthly", false),
  },
  property: {
    name: mcc("col-UKOooW1", "string", "Name", false),
    id: mcc("col-NYNaEua", "string", "ID", true),
    parcelNumber: mcc("col-dlhnglY", "number", "Parcel number", false),
    streetAddress: mcc("col-RxPUYIT", "string", "Street address", false),
    zipCode: mcc("col-mf-CiKH", "number", "Zip code", false),
    yearBuilt: mcc("col-iQ1mkhJ", "number", "Year built", false),
    squareFeet: mcc("col-ndjGDiW", "number", "Square feet", false),
    pavedDrivewayCount: mcc(
      "col-KaVpIiL",
      "number",
      "Paved driveway count",
      false,
    ),
    garageDoorCount: mcc("col-sppZ7na", "number", "Garage door count", false),
    unitLabelPrepend: mcc("col-ij_IAXs", "string", "Unit label prepend", false),
    purchasePrice: mcc("col-C2GI_ft", "number", "Purchase price", false),
    closingDate: mcc("col-7a6orCO", "string", "Closing date", false),
    buildingType: mcc("col-pTuQDxB", "string", "Building type", true),
    unitCount: mcc("col-wsgC_ig", "number", "Unit count", true),
    bedroomCount: mcc("col-dw-dis5", "number", "Bedroom count", true),
    furnaceCount: mcc("col-9YOXfRA", "number", "Furnace count", true),
    projectedRoi: mcc("col-l6xMHBT", "string", "Projected ROI", false),
    upfrontInvestment: mcc(
      "col-2jKnRmE",
      "string",
      "Upfront investment",
      false,
    ),
    averagePrincipalMonthly: mcc(
      "col-Ww_GkTd",
      "string",
      "Average principal monthly",
      false,
    ),
    discretionaryIncomeAnnualAvg: mcc(
      "col-fnh7KJP",
      "number",
      "Discretionary income annual avg",
      true,
    ),
    discretionaryIncomeMonthlyAvg: mcc(
      "col-McnYr72",
      "number",
      "Discretionary income monthly avg",
      true,
    ),
    flexibleIncomeMonthlyAvg: mcc(
      "col-GIXXH26",
      "number",
      "Flexible income monthly avg",
      true,
    ),
    grossIncomeMonthly: mcc(
      "col-ajl0Vey",
      "number",
      "Gross income monthly",
      true,
    ),
    mortgagePaymentMonthly: mcc(
      "col-6P8iAZC",
      "number",
      "Mortgage payment monthly",
      false,
    ),
    principalPaymentMonthlyAvg: mcc(
      "col-Nzx4807",
      "number",
      "Principal payment monthly avg",
      true,
    ),
    mortgageBalanceOriginal: mcc(
      "col-dMZggrr",
      "number",
      "Mortgage balance original",
      false,
    ),
    mortgageHolder: mcc("col-oeUhWvv", "string", "Mortgage holder", false),
    ltv: mcc("col-EeeukQT", "number", "LTV %", true),
    pmi: mcc("col-QxQPjIT", "string", "PMI", false),
    mortgageBalance: mcc("col-KhZEP9D", "number", "Mortgage balance", false),
    mortgageNumber: mcc("col-UH9nd_C", "number", "Mortgage number", false),
    helocPaymentMonthly: mcc(
      "col-7pB1h02",
      "number",
      "Heloc payment monthly",
      true,
    ),
    helocPaymentOverride: mcc(
      "col-fa446XR",
      "string",
      "HELOC payment override",
      false,
    ),
    helocInterestPayment: mcc(
      "col-Cx25AZv",
      "number",
      "HELOC interest payment",
      true,
    ),
    helocSpent: mcc("col-Sh2sxCg", "number", "HELOC spent", false),
    helocLimit: mcc("col-DDIzEX3", "number", "HELOC limit", false),
    helocAvailable: mcc("col-_sRmpcG", "number", "HELOC available", true),
    helocHolder: mcc("col-lIgVCtz", "string", "HELOC holder", false),
    helocInterestRate: mcc(
      "col-1xOaDGm",
      "number",
      "HELOC interest rate",
      false,
    ),
    helocPaymentDay: mcc("col-7oATSzG", "number", "HELOC payment day", false),
    helocNumber: mcc("col-Jw8ApcW", "number", "HELOC number", false),
    helocStartDate: mcc("col-1gA69gI", "date", "HELOC start date", false),
    utilityPaymentMonthlyAvg: mcc(
      "col-fDZD238",
      "number",
      "Utility payment monthly avg",
      true,
    ),
    energyPaymentMonthlyAvg: mcc(
      "col-kh-75Dj",
      "number",
      "Energy payment monthly avg",
      false,
    ),
    waterPaymentMonthlyAvg: mcc(
      "col-pxPZeyT",
      "number",
      "Water payment monthly avg",
      true,
    ),
    waterBillQuarterlyAvg: mcc(
      "col-2r-MvrC",
      "number",
      "Water bill quarterly avg",
      false,
    ),
    waterAccount: mcc("col-zGB5wLk", "string", "Water account", false),
    waterPaymentDayOfMonthEarly: mcc(
      "col-qDmMkZJ",
      "number",
      "Water payment day of month early",
      false,
    ),
    waterPaymentDayOfMonthLate: mcc(
      "col-8jXuvG-",
      "number",
      "Water payment day of month late",
      false,
    ),
    waterPaymentFirstQuarter: mcc(
      "col-o1x-wv4",
      "string",
      "Water payment first quarter",
      false,
    ),
    garbagePaymentMonthlyAvg: mcc(
      "col-n_D8298",
      "number",
      "Garbage payment monthly avg",
      true,
    ),
    garbageBillQuarterly: mcc(
      "col-jvoXCCB",
      "number",
      "Garbage bill quarterly",
      false,
    ),
    garbageBins: mcc("col-8bq2kF6", "string", "Garbage bins", false),
    budgetsMonthly: mcc("col-m1WV4qs", "number", "Budgets monthly", true),
    maintenanceBudgetMonthly: mcc(
      "col-ZH_jQsz",
      "number",
      "Maintenance budget monthly",
      true,
    ),
    vacancyBudgetMonthly: mcc(
      "col-g9Wb4sq",
      "number",
      "Vacancy budget monthly",
      true,
    ),
    groundskeepingBudgetMonthly: mcc(
      "col-Dy2oTtx",
      "number",
      "Groundskeeping budget monthly",
      false,
    ),
    capexBudgetMonthly: mcc(
      "col-U2UTMN3",
      "number",
      "Capex budget monthly",
      true,
    ),
    perProperty: mcc("col-ejzcxIv", "number", "Per property", true),
    windowCountEstimate: mcc(
      "col-Qqr81ps",
      "number",
      "Window count estimate",
      true,
    ),
    roof: mcc("col-dmwUWVp", "number", "Roof", true),
    siding: mcc("col-meHYx80", "number", "Siding", true),
    furnace: mcc("col-RmN-bYV", "number", "Furnace", true),
    waterHeater: mcc("col-iUTHiqG", "number", "Water heater", true),
    flooring: mcc("col-jN28F8U", "number", "Flooring", true),
    gutters: mcc("col-zXJ8dhr", "number", "Gutters", true),
    interiorPaint: mcc("col-RvWphY1", "number", "Interior paint", true),
    refrigerator: mcc("col-JPhrE1-", "number", "Refrigerator", true),
    range: mcc("col-mqLl6c1", "number", "Range", true),
    clothesWasher: mcc("col-V5JLenJ", "number", "Clothes washer", true),
    clothesDryer: mcc("col-YjDwWCa", "number", "Clothes dryer", true),
    dishwasher: mcc("col-WJIYxcR", "number", "Dishwasher", true),
    windows: mcc("col-XI0diwj", "number", "Windows", true),
    cabinets: mcc("col-mHi63ZH", "number", "Cabinets", true),
    countertops: mcc("col-BIpQMby", "number", "Countertops", true),
    landscaping: mcc("col-h_ax2o8", "number", "Landscaping", true),
    driveway: mcc("col-55h3otY", "number", "Driveway", true),
    garageDoor: mcc("col-Ndh1QvP", "number", "Garage door", true),
    insuranceProvider: mcc(
      "col-l8xxJGI",
      "string",
      "Insurance provider",
      false,
    ),
    insurancePolicyNumber: mcc(
      "col-F5FD5Fu",
      "string",
      "Insurance policy number",
      false,
    ),
    insuranceRenewalDate: mcc(
      "col-LQlJfeM",
      "date",
      "Insurance renewal date",
      false,
    ),
    insuranceDeductible: mcc(
      "col-TEv3fQS",
      "number",
      "Insurance deductible",
      false,
    ),
    insurancePremiumYearly: mcc(
      "col-4dwzFhA",
      "number",
      "Insurance premium yearly",
      false,
    ),
    insurancePremiumMonthly: mcc(
      "col-f1sJZjS",
      "number",
      "Insurance premium monthly",
      true,
    ),
    insuranceNotes: mcc("col-fmolBdG", "string", "Insurance notes", false),
    outdoorWaterSource: mcc(
      "col-aBMOpUk",
      "string",
      "Outdoor water source",
      false,
    ),
    gardenBedSqFt: mcc("col-xgNmSP2", "number", "Garden bed sq ft", false),
    gardenYardSqFt: mcc("col-lLGiPJ-", "number", "Garden yard sq ft", true),
    boulevardSqFt: mcc("col-xPhh3bL", "number", "Boulevard sq ft", true),
    kidsPlayBackYardSqFt: mcc(
      "col-HmSzSso",
      "number",
      "Kids play back yard sq ft",
      false,
    ),
    lawnMowSqft: mcc("col-tGD0Atd", "string", "Lawn mow sqft", false),
    totalYardSqft: mcc("col-AWQC6wR", "string", "Total yard sqft", false),
  },
  propertyExpense: {
    expenseName: mcc("col-w_PiWJi", "string", "Expense name", true),
    id: mcc("col-Qj2-mYp", "string", "ID", true),
    propertyId: mcc("col-1hpEB5R", "string", "Property ID", false),
    date: mcc("col-eg74PeC", "date", "Date", false),
    year: mcc("col-4DAHsCd", "number", "Year", true),
    propertyYearId: mcc("col-WchviCc", "string", "Property year ID", true),
    unitId: mcc("col-rH-ATRE", "string", "Unit ID", false),
    billerName: mcc("col-icHn2T8", "string", "Biller name", false),
    description: mcc("col-g1WqJPr", "string", "Description", false),
    expenseCategory: mcc(
      "col-HVmhEMV",
      "expenseCategory",
      "Expense category",
      false,
    ),
    receiptFormat: mcc("col-qpJqo2x", "receiptFormat", "Receipt format", false),
    amount: mcc("col-Tum3aH7", "number", "Amount", false),
    deductibleAmount: mcc("col-55XKM_i", "number", "Deductible amount", true),
    taxAdjust: mcc("col-V2BAd2p", "residenceTaxAdjust", "Tax adjust", false),
    isUpfrontInvestment: mcc(
      "col-bK8A6h_",
      "yesOrNo",
      "Is upfront investment",
      false,
    ),
    notes: mcc("col-tf50IlU", "string", "Notes", false),
  },
  propertyProspect: {
    name: mcc("col-S0OAuTp", "string", "Name", false),
    id: mcc("col-OkqJWNn", "string", "ID", true),
    parcelNumberPropertyId: mcc(
      "col-0lIe4Xa",
      "string",
      "Parcel Number/\nProperty ID",
      false,
    ),
    streetAddress: mcc("col-jiFMS_y", "string", "Street address", false),
    zipCode: mcc("col-1y1a6Ff", "string", "Zip code", false),
    purchaseDate: mcc("col-CW9RU72", "string", "Purchase date", false),
    status: mcc("col-8d9-nfv", "string", "Status", false),
    notes: mcc("col-RoBy_Ut", "string", "Notes", false),
    questions: mcc("col-9qe82lZ", "string", "Questions", false),
    yearBuilt: mcc("col-lKMwqMV", "string", "Year built", false),
    squareFeet: mcc("col-DqT0mwa", "string", "Square feet", false),
    unitCount: mcc("col-Ag6_m69", "string", "Unit count", false),
    furnaceCount: mcc("col-rO5CGy0", "string", "Furnace count", false),
    bedroomCount: mcc("col-se5gANl", "string", "Bedroom count", false),
    pavedDrivewayCount: mcc(
      "col-jVdARRy",
      "string",
      "Paved driveway count",
      false,
    ),
    garageDoorCount: mcc("col-yYgBB3-", "string", "Garage door count", false),
    purchasePrice: mcc("col-FpFVeeU", "string", "Purchase price", false),
    comission: mcc("col-QZfm4Rg", "string", "Comission", false),
    downPayment: mcc("col-E6lZNsV", "number", "Down payment", true),
    startingRentalIncome: mcc(
      "col-IkgdHr9",
      "string",
      "Starting rental income",
      false,
    ),
    rentalIncome: mcc("col-W0Q3tXm", "string", "Rental income", false),
    upfrontRepairCosts: mcc(
      "col-6cQlFxE",
      "string",
      "Upfront repair costs",
      false,
    ),
    nonUpfrontRepairCostsCapex: mcc(
      "col-MwxRVjG",
      "string",
      "Non-upfront repair costs (CapEx)",
      false,
    ),
    taxesAnnual: mcc("col-gCG2Qie", "string", "Taxes annual", false),
    taxesMonthly: mcc("col-VL874yL", "number", "Taxes monthly", true),
    lawncareBudgetMonthly: mcc(
      "col-W1p8b1b",
      "number",
      "Lawncare budget monthly",
      true,
    ),
    insuranceMonthlyEstimate: mcc(
      "col-XcPapnZ",
      "number",
      "Insurance monthly estimate",
      true,
    ),
    insuranceAnnualEstimate: mcc(
      "col-ZvJvQRO",
      "number",
      "Insurance annual estimate",
      true,
    ),
    utilityTotalMonthly: mcc(
      "col-e8TG1zH",
      "number",
      "Utility total monthly",
      true,
    ),
    waterMonthly: mcc("col-ybMqgFN", "number", "Water monthly", true),
    waterQuarterly: mcc("col-B3xgDQf", "string", "Water quarterly", false),
    garbageMonthly: mcc("col-tbRXTof", "number", "Garbage monthly", true),
    garbageQuarterly: mcc("col-P29jxIM", "number", "Garbage quarterly", true),
    capexTotalMonthly: mcc(
      "col-BTE_UBh",
      "number",
      "CapEx total monthly",
      true,
    ),
    perProperty: mcc("col-0E8iAux", "number", "Per property", true),
    windowCountEstimate: mcc(
      "col-NnjG4Rt",
      "number",
      "Window count estimate",
      true,
    ),
    roof: mcc("col-yT_a5B3", "number", "Roof", true),
    siding: mcc("col-5gg-upp", "number", "Siding", true),
    furnace: mcc("col-ioVtdjD", "number", "Furnace", true),
    waterHeater: mcc("col-izjCpVm", "number", "Water heater", true),
    flooring: mcc("col-JTSdHJz", "number", "Flooring", true),
    gutters: mcc("col-WESKtQv", "number", "Gutters", true),
    interiorPaint: mcc("col-iTcbFAe", "number", "Interior paint", true),
    refrigerator: mcc("col-Cmdyap_", "number", "Refrigerator", true),
    range: mcc("col-9YxhUFQ", "number", "Range", true),
    clothesWasher: mcc("col-wVSe7xy", "number", "Clothes washer", true),
    clothesDryer: mcc("col-QJ-YTkC", "number", "Clothes dryer", true),
    dishwasher: mcc("col-hY1lYJN", "number", "Dishwasher", true),
    windows: mcc("col-OQREydX", "number", "Windows", true),
    cabinets: mcc("col-IppyLV4", "number", "Cabinets", true),
    countertops: mcc("col-ICqtSww", "number", "Countertops", true),
    landscaping: mcc("col-vqT2zOu", "number", "Landscaping", true),
    driveway: mcc("col-PLW0MYK", "number", "Driveway", true),
    garageDoor: mcc("col-ZKkZ7-V", "number", "Garage door", true),
    vacancyBudgetMonthly: mcc(
      "col-ljxz0gR",
      "number",
      "Vacancy budget monthly",
      true,
    ),
    maintenanceBudgetMonthly: mcc(
      "col-i2fS7QU",
      "number",
      "Maintenance budget monthly",
      true,
    ),
    loanAmountBase: mcc("col-nwkgCz7", "number", "Loan amount base", true),
    ltvRatio: mcc("col-IYtSZG9", "string", "LTV ratio", true),
    interestRateYearly: mcc(
      "col-BB4uKDl",
      "number",
      "Interest rate yearly",
      true,
    ),
    interestRateMonthly: mcc(
      "col-Vw_TTgT",
      "number",
      "Interest rate monthly",
      true,
    ),
    loanTermYears: mcc("col-HOqeQW_", "number", "Loan term years", true),
    loanTermMonths: mcc("col-Db1veZf", "number", "Loan term months", true),
    closingCosts: mcc("col-MF8af4Z", "number", "Closing costs", true),
    sellerPaidClosingCosts: mcc(
      "col-XDKvGiw",
      "string",
      "Seller-paid closing costs",
      false,
    ),
    prepaidsAtClosing: mcc(
      "col-JHBkv_7",
      "string",
      "Prepaids at closing",
      false,
    ),
    principalAndInterestMonthly: mcc(
      "col-sxLq4Fz",
      "number",
      "Principal and interest monthly",
      true,
    ),
    pmiMonthly: mcc("col-5xHnDsz", "number", "PMI monthly", true),
    pmiAnnual: mcc("col-i50sS9U", "number", "PMI annual", true),
    pmiRate: mcc("col-geWSWWp", "string", "PMI rate", false),
    mortgagePaymentEstimatePiti: mcc(
      "col-ORerHse",
      "number",
      "Mortgage payment estimate (PITI)",
      true,
    ),
    grossIncomeMonthly: mcc(
      "col-Yt4wh4q",
      "string",
      "Gross income monthly",
      false,
    ),
    upfrontCosts: mcc("col-Af68cx4", "number", "Upfront costs", true),
    upfrontCash: mcc("col-SFb8uBJ", "string", "Upfront cash", false),
    propertyExpensesMonthly: mcc(
      "col-xvpvOfm",
      "number",
      "Property expenses monthly",
      true,
    ),
    financingExpensesMonthly: mcc(
      "col-X5gIiB8",
      "number",
      "Financing expenses monthly",
      true,
    ),
    totalExpensesMonthly: mcc(
      "col-6yEJQ__",
      "number",
      "Total expenses monthly",
      true,
    ),
    cashFlowMonthly: mcc("col-O8benrs", "number", "Cash flow monthly", true),
    cashFlowAnnual: mcc("col-JNeUlZP", "number", "Cash flow annual", true),
    roi: mcc("col-2JBw-J8", "number", "ROI", true),
    column96: mcc("col--9HLvkP", "string", "Column 96", false),
    insurancePremiumYearly: mcc(
      "col-CjODhuL",
      "string",
      "Insurance premium yearly",
      false,
    ),
    insurancePremiumMonthly: mcc(
      "col-B-TtJXJ",
      "number",
      "Insurance premium monthly",
      true,
    ),
    insuranceProvider: mcc(
      "col-W3x5YSr",
      "string",
      "Insurance provider",
      false,
    ),
    insurancePolicyNumber: mcc(
      "col-VqbqKMH",
      "string",
      "Insurance policy number",
      false,
    ),
    insuranceRenewalDate: mcc(
      "col-C62joYg",
      "string",
      "Insurance renewal date",
      false,
    ),
    insuranceDeductible: mcc(
      "col-gO6IMv8",
      "string",
      "Insurance deductible",
      false,
    ),
    insuranceNotes: mcc("col-6atkGeu", "string", "Insurance notes", false),
    utilityMonthlyTotal: mcc(
      "col-51JutEB",
      "number",
      "Utility monthly total",
      true,
    ),
    waterPaymentMonthly: mcc(
      "col-8yIBK-J",
      "number",
      "Water payment monthly",
      true,
    ),
    garbagePaymentMonthly: mcc(
      "col-pOB7Uhb",
      "number",
      "Garbage payment monthly",
      true,
    ),
    energyPaymentMonthly: mcc(
      "col-Wq9kMAe",
      "string",
      "Energy payment monthly",
      false,
    ),
    waterAccountUnverified: mcc(
      "col-hH3A_7Z",
      "string",
      "Water account (unverified)",
      false,
    ),
    avgWaterBillQuarterly: mcc(
      "col-YbK6nes",
      "string",
      "Avg water bill quarterly",
      false,
    ),
    nextWaterPaymentDate: mcc(
      "col-SFdq1KP",
      "date",
      "Next water payment date",
      true,
    ),
    waterPaymentDate: mcc("col-mK1W-mH", "string", "Water payment date", false),
    avgGarbageBillQuarterly: mcc(
      "col-2Be_ZlX",
      "string",
      "Avg garbage bill quarterly",
      false,
    ),
    nextGarbagePaymentDate: mcc(
      "col-6sO5HEW",
      "string",
      "Next garbage payment date",
      false,
    ),
    garbagePaymentDate: mcc(
      "col-gi63OtF",
      "string",
      "Garbage payment date",
      false,
    ),
    column97: mcc("col-ptM7Jj7", "string", "Column 97", false),
    column1: mcc("col-Egb6CCR", "string", "Column 1", false),
    mortgagePaymentMonthly: mcc(
      "col-p9lga5D",
      "string",
      "Mortgage payment monthly",
      false,
    ),
    mortgageHolder: mcc("col-tvtnSGs", "string", "Mortgage holder", false),
    mortgageNumber: mcc("col-f0TEYw-", "string", "Mortgage number", false),
    mortgageBalance: mcc("col-XSvoDWo", "string", "Mortgage balance", false),
    ltv: mcc("col-7HKVmK_", "string", "LTV %", true),
    pmi: mcc("col-nto9Ao2", "string", "PMI", false),
    helocAvailable: mcc("col-P2LYFfH", "number", "HELOC available", true),
    helocPaymentMonthly: mcc(
      "col--vU01TX",
      "string",
      "HELOC payment monthly",
      false,
    ),
    helocHolder: mcc("col--wsHtE_", "string", "HELOC holder", false),
    helocNumber: mcc("col-RBLV5s_", "string", "HELOC number", false),
    helocStartDate: mcc("col-0dnlzzL", "string", "HELOC start date", false),
    helocLimit: mcc("col-PhrD5vU", "string", "HELOC limit", false),
    helocBalance: mcc("col-mNIXW1Y", "string", "HELOC balance", false),
    helocInterestRate: mcc(
      "col-XWTq4RX",
      "string",
      "HELOC interest rate",
      false,
    ),
  },
  propertyYear: {
    name: mcc("col--GXBgqg", "string", "Name", true),
    id: mcc("col-pLbR676", "string", "ID", true),
    propertyId: mcc("col-MqF-anY", "string", "Property ID", false),
    year: mcc("col-TawhTyt", "number", "Year", false),
    primarySpace: mcc("col-alQOQuj", "number", "Primary space", false),
    notPrimarySpace: mcc("col-QkHxyMW", "number", "Not primary space", true),
    primaryTimeOwned: mcc("col-iSuANXq", "number", "Primary time owned", false),
    notPrimaryTimeOwned: mcc(
      "col-kj62b6N",
      "number",
      "Not primary time owned",
      true,
    ),
    total: mcc("col-w0edV92", "number", "Total", true),
    incomeFromHouseholds: mcc(
      "col-iD9skHh",
      "number",
      "Income from households",
      true,
    ),
    incomeFromSubsidies: mcc(
      "col-7X1LeUo",
      "number",
      "Income from subsidies",
      true,
    ),
    incomeFromOtherSources: mcc(
      "col-QseAaB5",
      "number",
      "Income from other sources",
      true,
    ),
    "1099Misc": mcc("col-dcCSLJn", "string", "1099-Misc", false),
    incomeExptected: mcc("col-8LhB3qW", "string", "Income exptected", false),
    incomeExpectedMaximum: mcc(
      "col-M08K-ca",
      "string",
      "Income expected maximum",
      false,
    ),
    budgetsCostEstimates: mcc(
      "col-qhjoI7t",
      "string",
      "Budgets & cost estimates",
      false,
    ),
    maintenanceBudget: mcc(
      "col-4r-P97r",
      "string",
      "Maintenance budget",
      false,
    ),
    vacancyBudget: mcc("col-vBhf-u-", "string", "Vacancy budget", false),
    lawncareBudget: mcc("col-PT5uv-S", "string", "Lawncare budget", false),
    capexBudget: mcc("col-p54csmV", "string", "CapEx budget", false),
    utilityCostEstimate: mcc(
      "col-xy2UuPt",
      "string",
      "Utility cost estimate",
      false,
    ),
    actualCosts: mcc("col-nIf7Xtx", "number", "Actual costs", true),
    maintenanceGroundskeepingCosts: mcc(
      "col-hYWXrQz",
      "number",
      "Maintenance & groundskeeping costs",
      true,
    ),
    utilityCosts: mcc("col-0KWDOnD", "number", "Utility costs", true),
    capexCosts: mcc("col-exdmXLl", "number", "CapEx costs", true),
    vacancyCosts: mcc("col-J7djr8C", "string", "Vacancy costs", false),
    taxableTotal: mcc("col-Bzs_uJu", "number", "Taxable total", true),
    absoluteTotal: mcc("col-PGC9pdA", "number", "Absolute total", true),
    cleaningMaintenance: mcc(
      "col-RmgQG7B",
      "number",
      "Cleaning & maintenance",
      true,
    ),
    insurance: mcc("col-lUNFd66", "number", "Insurance", true),
    mortgageInterestPaidToBanks: mcc(
      "col-J2F1NxS",
      "number",
      "Mortgage interest paid to banks",
      true,
    ),
    repair: mcc("col-AiWPNkl", "number", "Repair", true),
    supplies: mcc("col-4OAhSq1", "number", "Supplies", true),
    taxes: mcc("col-2pLgeyL", "number", "Taxes", true),
    utilities: mcc("col-uU2oYki", "number", "Utilities", true),
    depreciationExpenseOrDepletion: mcc(
      "col-Y9hnxem",
      "number",
      "Depreciation expense or depletion",
      true,
    ),
    legalProfessional: mcc(
      "col-D6zQXl4",
      "number",
      "Legal & professional",
      true,
    ),
    advertising: mcc("col-aHKMePu", "number", "Advertising", true),
    autoAndTravel: mcc("col-dx-FCXy", "number", "Auto and travel", true),
    mgmtFees: mcc("col-hmM-lMs", "number", "Mgmt fees", true),
    commissions: mcc("col-4J2Mxv9", "number", "Commissions", true),
    otherInterest: mcc("col-JbhS4Y6", "number", "Other interest", true),
    other: mcc("col-okSrW_E", "number", "Other", true),
    principal: mcc("col-i_x5Gzf", "number", "Principal", true),
  },
  quotes: {
    date: mcc("col-WGt6dPd", "date", "Date", false),
    id: mcc("col-h3wgJ39", "string", "ID", true),
    prospectiveBillerName: mcc(
      "col-QlJe96V",
      "string",
      "Prospective biller name",
      false,
    ),
    billerName: mcc("col-ly-BMJ_", "string", "Biller name", false),
    billerCategory: mcc("col-3hlIrmQ", "string", "Biller category", true),
    service: mcc("col-4swJjZZ", "string", "Service", false),
    amount: mcc("col-7xyQYhm", "number", "Amount", false),
    preferredForService: mcc(
      "col-Fwju2h2",
      "string",
      "Preferred for service",
      false,
    ),
    notes: mcc("col-qyRbDVX", "string", "Notes", false),
  },
  recurringTransaction: {
    id: mcc("col-gP8cSSs", "string", "ID", false),
    item: mcc("col-T5ui0fF", "string", "Item", false),
    transactionType: mcc("col-ViD8IQV", "string", "Transaction type", false),
    transactWith: mcc("col-1lm7yg5", "string", "Transact with", false),
    propertyId: mcc("col-0Hg4hkA", "string", "Property ID", false),
    transactionDayOfMonth: mcc(
      "col-Rk2rqXQ",
      "number",
      "Transaction day of month",
      false,
    ),
    monthsBetweenTransactions: mcc(
      "col-x7aeIs_",
      "number",
      "Months between transactions",
      false,
    ),
    nextTransactionDateEarly: mcc(
      "col-Qq_cpwI",
      "date",
      "Next transaction date early",
      true,
    ),
    nextTransactionAmount: mcc(
      "col-CCXBkki",
      "number",
      "Next transaction amount",
      true,
    ),
    averageMonthlyTransactionAmount: mcc(
      "col-sOSxVtN",
      "string",
      "Average monthly transaction amount",
      false,
    ),
    notes: mcc("col-NRvXapU", "string", "Notes", false),
  },
  rentComp: {
    id: mcc("col-pDoUFPj", "string", "ID", false),
    rentCompType: mcc("col-WPrzo7n", "string", "Rent comp type", true),
    paymentStandardName: mcc(
      "col-Dwm_BvW",
      "string",
      "Payment standard name",
      true,
    ),
    name: mcc("col-sk5BTbD", "string", "Name", false),
    date: mcc("col-PR3fL6v", "date", "Date", false),
    paymentStandardYear: mcc(
      "col-zAF93A0",
      "number",
      "Payment standard year",
      false,
    ),
    buildingType: mcc("col-kwd1nJf", "buildingType", "Building type", false),
    bedroomCount: mcc("col-zUPaL7J", "number", "Bedroom count", false),
    zipCode: mcc("col-SCKjbMh", "number", "Zip code", false),
    baseRentChargeMonthly: mcc(
      "col--KXLs3h",
      "number",
      "Base rent charge monthly",
      false,
    ),
    paymentStandardGrossRent: mcc(
      "col-XPaiJuh",
      "string",
      "Payment standard gross rent",
      true,
    ),
    paymentStandardUtilities: mcc(
      "col-uHlQTjQ",
      "string",
      "Payment standard utilities",
      true,
    ),
    gasHeating: mcc("col-v6ruJbN", "boolean", "Gas Heating", false),
    electricHeating: mcc("col-1tFVepW", "boolean", "Electric Heating", false),
    gasCooking: mcc("col-yXPEotT", "boolean", "Gas Cooking", false),
    electricCooking: mcc("col-lEpzVR-", "boolean", "Electric Cooking", false),
    gasWaterHeating: mcc("col-fRt2Yns", "boolean", "Gas Water Heating", false),
    electricWaterHeating: mcc(
      "col-6CK9SPa",
      "boolean",
      "Electric Water Heating",
      false,
    ),
    otherElectric: mcc("col-kDXrKLj", "boolean", "Other Electric", false),
    waterSewer: mcc("col-d1u_yOr", "boolean", "Water & Sewer", false),
    trashCollection: mcc("col-xXD5Eot", "boolean", "Trash Collection", false),
    districtEnergyHeating: mcc(
      "col-qyoPjKZ",
      "boolean",
      "District Energy Heating",
      false,
    ),
    districtEnergyWaterHeating: mcc(
      "col-5aWwQIZ",
      "boolean",
      "District Energy Water Heating",
      false,
    ),
  },
  resident: {
    fullName: mcc("col-JQF8pac", "string", "Full name", true),
    id: mcc("col-8zXeQEw", "string", "ID", true),
    householdId: mcc("col-MMj5Qgq", "string", "Household ID", false),
    isActive: mcc("col-7LZcJ2t", "string", "Is active", true),
    firstName: mcc("col-ad6YZal", "string", "First name", false),
    lastName: mcc("col-cU-EQJv", "string", "Last name", false),
    middleInitial: mcc("col-w73gARY", "string", "Middle Initial", false),
    nameRank: mcc("col-XTeBHw2", "number", "Name rank", false),
    ssn: mcc("col-KDa6EVM", "string", "SSN", false),
    dob: mcc("col-NmeH8b0", "string", "DOB", false),
    phoneNumber: mcc("col-WDpsFk0", "string", "Phone Number", false),
    emailAddress: mcc("col-Q_gueC7", "string", "Email Address", false),
    income: mcc("col-TX8xQd6", "string", "Income", false),
    disability: mcc("col-Tkuv1y3", "string", "Disability", false),
    couldPay: mcc("col-FNPG_yQ", "string", "Could Pay?", false),
  },
  subPayAllocation: {
    name: mcc("col-uzEH5HL", "string", "Name", true),
    id: mcc("col-PJ1qm7P", "string", "ID", true),
    paymentId: mcc("col-jAnSZoZ", "string", "Payment ID", false),
    paymentDate: mcc("col-ek62dJt", "date", "Payment date", true),
    formOfPayment: mcc("col-3jQA3el", "string", "Form of payment", true),
    paymentAllocated: mcc("col-ci9Olfh", "number", "Payment allocated", true),
    chargeId: mcc("col-dWzWhmG", "string", "Charge ID", false),
    chargeDescription: mcc("col-20hJLMV", "string", "Charge description", true),
    subsidyAgreementId: mcc(
      "col-xymKv30",
      "string",
      "Subsidy agreement ID",
      true,
    ),
    occupancyId: mcc("col--Kn3Eaj", "string", "Occupancy ID", true),
    propertyId: mcc("col-GnmfHIq", "string", "Property ID", true),
    paymentUnallocated: mcc(
      "col-zZm04Vj",
      "number",
      "Payment unallocated",
      true,
    ),
    chargeUnpaid: mcc("col-AdryODU", "number", "Charge unpaid", true),
    amount: mcc("col-uPlGvHp", "number", "Amount", true),
    allocateFullAmount: mcc(
      "col-dGJNUqv",
      "boolean",
      "Allocate full amount",
      false,
    ),
    lesserAmount: mcc("col-BZ8hOws", "string", "Lesser amount", false),
    filledOut: mcc("col-Goy1X8c", "string", "Filled out", true),
    processed: mcc("col-pZ746C-", "yesOrNo", "Processed", true),
  },
  subsidyAgreement: {
    name: mcc("col-2LNDs6x", "string", "Name", true),
    id: mcc("col-otFGzR9", "string", "ID", true),
    occupancyId: mcc("col-29TQHcp", "string", "Occupancy ID", false),
    subsidyProgramId: mcc("col-0WyuPph", "string", "Subsidy program ID", false),
    paymentGroupId: mcc("col-hltQiWS", "string", "Payment group ID", false),
    paymentGroupName: mcc("col-CNLvSX-", "string", "Payment group name", true),
    agreementStandardName: mcc(
      "col-Sh_eL0o",
      "string",
      "Agreement standard name",
      true,
    ),
    programStandardName: mcc(
      "col-9Aw3w41",
      "string",
      "Program standard name",
      true,
    ),
    unitStandardName: mcc("col-SAZOgc0", "string", "Unit standard name", true),
    annualRenewalMonth: mcc(
      "col-9VVjyo4",
      "string",
      "Annual renewal month",
      false,
    ),
    annualInspectionMonth: mcc(
      "col-Xb7V4lu",
      "string",
      "Annual inspection month",
      false,
    ),
    subsidyContractStartDate: mcc(
      "col-h4okp5i",
      "date",
      "Subsidy contract start date",
      true,
    ),
    rentPortionMonthly: mcc(
      "col-KL3PAT5",
      "number",
      "Rent portion monthly",
      true,
    ),
    nextSubsidyContractStartDate: mcc(
      "col-RakSpZz",
      "string",
      "Next subsidy contract start date",
      false,
    ),
    nextRentPortionMonthly: mcc(
      "col-NktpEAf",
      "string",
      "Next rent portion monthly",
      false,
    ),
    updateSubsidyContractEnter: mcc(
      "col-pZ_-OR1",
      "boolean",
      "Update subsidy contract enter",
      false,
    ),
    subsidyWorkerId: mcc("col-0Ep6gXa", "string", "Subsidy worker ID", false),
    subsidyWorkerFirstName: mcc(
      "col-B0Dj4Od",
      "string",
      "Subsidy worker first name",
      true,
    ),
    subsidyWorkerEmail: mcc(
      "col-sOKTA2U",
      "string",
      "Subsidy worker email",
      true,
    ),
    totalCharges: mcc("col-YAdsPFN", "number", "Total charges", true),
    totalPayments: mcc("col-BPXV2hW", "number", "Total payments", true),
    balance: mcc("col-w8vLkK8", "number", "Balance", true),
  },
  subsidyCharge: {
    name: mcc("col-sUaYozJ", "string", "Name", true),
    id: mcc("col--nTU65W", "string", "ID", true),
    subsidyAgreementId: mcc(
      "col-MONO5y5",
      "string",
      "Subsidy agreement ID",
      false,
    ),
    date: mcc("col-siQYN_v", "date", "Date", false),
    description: mcc("col-eki29GV", "chargeDescription", "Description", false),
    amount: mcc("col-D_ZLCZz", "number", "Amount", false),
    amountPaid: mcc("col-RNSqWma", "number", "Amount paid", true),
    amountUnpaid: mcc("col-899hXuQ", "number", "Amount unpaid", true),
  },
  subsidyPayment: {
    date: mcc("col-_YBhAu5", "date", "Date", false),
    id: mcc("col-PTux14k", "string", "ID", true),
    allocationName: mcc("col-f083hYz", "string", "Allocation name", true),
    subsidyProgramId: mcc("col-3wCKfdm", "string", "Subsidy program ID", false),
    numAllocated: mcc("col-Bc6Z9wd", "number", "Num allocated", true),
    formOfPayment: mcc("col-dkz_xwK", "paymentType", "Form of payment", false),
    amount: mcc("col-AcmAj-n", "number", "Amount", false),
    detailsVerified: mcc("col-V9Ue8yu", "yesOrNo", "Details verified", false),
    amountAllocated: mcc("col-OHWAx0k", "number", "Amount allocated", true),
    amountUnallocated: mcc("col-4kyYlK4", "number", "Amount unallocated", true),
    processed: mcc("col-s-HNMVx", "yesOrNo", "Processed", true),
  },
  subsidyProgram: {
    name: mcc("col-o4QSWBF", "string", "Name", true),
    id: mcc("col-SP4bmlN", "string", "ID", true),
    nonResidentPayerId: mcc(
      "col-_17JhlQ",
      "string",
      "Non-resident payer ID",
      false,
    ),
    nonResidentPayerName: mcc(
      "col-p2sw2KM",
      "string",
      "Non-resident payer name",
      true,
    ),
    programStandardName: mcc(
      "col-J26TwQD",
      "string",
      "Program standard name",
      true,
    ),
    paymentStandardType: mcc(
      "col-2DJ5qZa",
      "string",
      "Payment standard type",
      false,
    ),
    paymentStandardArea: mcc(
      "col-Wk4Fb9d",
      "string",
      "Payment standard area",
      false,
    ),
  },
  subsidyTerms: {
    name: mcc("col-YqGL5a7", "string", "Name", true),
    id: mcc("col-8MJW0am", "string", "ID", true),
    subsidyAgreementId: mcc(
      "col-NGDD5AZ",
      "string",
      "Subsidy agreement ID",
      false,
    ),
    occupancyId: mcc("col-d7tvBlB", "string", "Occupancy ID", true),
    subsidyProgramId: mcc("col-h9ut47r", "string", "Subsidy program ID", true),
    occupancyTermsId: mcc("col-EiyA0BM", "string", "Occupancy terms ID", true),
    rentChargeMonthly: mcc(
      "col-kSFbjAd",
      "number",
      "Rent charge monthly",
      false,
    ),
    startDate: mcc("col-N98wM8U", "date", "Start date", false),
    endDate: mcc("col-WAdoKW-", "string", "End date", false),
    grossRent: mcc("col-ubljNHa", "string", "Gross rent", false),
    grossUtilities: mcc("col-Ysocizr", "string", "Gross utilities", true),
    paymentStandardName: mcc(
      "col-YS5igdB",
      "string",
      "Payment standard name",
      true,
    ),
    gasHeating: mcc("col-3Cxid3J", "boolean", "Gas Heating", true),
    electricHeating: mcc("col-2jWsE7c", "boolean", "Electric Heating", true),
    gasCooking: mcc("col-RNh1HKZ", "boolean", "Gas Cooking", true),
    electricCooking: mcc("col-Qz2zH70", "boolean", "Electric Cooking", true),
    otherElectric: mcc("col-rc7bLdS", "boolean", "Other Electric", true),
    gasWaterHeating: mcc("col-zVC9R-p", "boolean", "Gas Water Heating", true),
    electricWaterHeating: mcc(
      "col-jxHTX7M",
      "boolean",
      "Electric Water Heating",
      true,
    ),
    waterSewer: mcc("col-WElsMcQ", "boolean", "Water & Sewer", true),
    trashCollection: mcc("col-YJt59t-", "boolean", "Trash Collection", true),
    districtEnergyHeating: mcc(
      "col-TQGePfn",
      "boolean",
      "District Energy Heating",
      true,
    ),
    districtEnergyWaterHeating: mcc(
      "col-qcYF86e",
      "boolean",
      "District Energy Water Heating",
      true,
    ),
    space: mcc("col-ASpRcFN", "string", "_space", false),
  },
  subsidyWorker: {
    firstName: mcc("col-hfOt7C0", "string", "First name", false),
    lastName: mcc("col-L_VYXUd", "string", "Last name", false),
    id: mcc("col-TQPNwF_", "string", "ID", true),
    email: mcc("col-88UVmfe", "string", "Email", false),
    backupEmail: mcc("col-dNdbe6y", "string", "Backup email", false),
    phoneNumber: mcc("col-6VuYdwS", "string", "Phone number", false),
    organization: mcc("col-tPe80XG", "string", "Organization", false),
    programs: mcc("col-gN6fMbl", "string", "Programs", false),
    covers: mcc("col-J13PcBt", "string", "Covers", false),
    updateDate: mcc("col-MnyQXGB", "date", "Update date", false),
  },
  tenantPros: {
    id: mcc("col-DGFdnb-", "string", "ID", true),
    firstName: mcc("col-WrouvG3", "string", "First Name", false),
    lastName: mcc("col-7DS8uNK", "string", "Last Name", false),
    householdProspectId: mcc(
      "col-mhlI1zY",
      "string",
      "Household prospect ID",
      false,
    ),
    incomeSources: mcc("col-ldU8XUc", "string", "Income sources", false),
    incomeAmountMonthly: mcc(
      "col-eywE1hX",
      "number",
      "Income amount monthly",
      true,
    ),
    issues: mcc("col-amHKB33", "string", "Issues", false),
  },
  test: {
    column5: mcc("col-Oy9WtzQ", "string", "Column 5", true),
    id: mcc("col-8wOXbE6", "string", "ID", false),
    number: mcc("col-kJ47IXM", "number", "Number", false),
    dropdown: mcc("col-4_IzNLS", "yesOrNo", "Dropdown", false),
    date: mcc("col--K2Vvyh", "date", "Date", true),
  },
  unit: {
    name: mcc("col-6WTZgxx", "string", "Name", true),
    id: mcc("col-Qo3J03G", "string", "ID", true),
    propertyId: mcc("col-lrmLxqZ", "string", "Property ID", false),
    unitIdentifier: mcc("col-6lzrdO8", "string", "Unit identifier", false),
    addressLabel: mcc("col-jfe-foO", "string", "Address label", true),
    bedroomCount: mcc("col-jW2kk6k", "number", "Bedroom count", false),
    bathroomCount: mcc("col-OjXNgxW", "number", "Bathroom count", false),
    unitLocation: mcc("col-QyE4mns", "string", "Unit location", false),
    propertyName: mcc("col-VmQmaL-", "string", "Property name", true),
    streetAddress: mcc("col-euGUQGm", "string", "Street address", true),
    zipCode: mcc("col-8dSwV9O", "number", "Zip code", true),
    rentReasonablenessCompType: mcc(
      "col-XdcNPGi",
      "string",
      "Rent reasonableness comp type",
      true,
    ),
    unitStandardName: mcc("col-70aCBAb", "string", "Unit standard name", true),
    rentDue: mcc("col-v5NXrsS", "string", "Rent due", false),
    householdName: mcc("col-Mgm5WDL", "string", "Household name", false),
    totalMonthlyRent: mcc("col-x-nfN3F", "string", "Total monthly rent", false),
    securityDeposit: mcc("col-s6Coo3X", "string", "Security deposit", false),
    rentIncreaseDates: mcc(
      "col-FDIXEKX",
      "string",
      "Rent increase dates",
      false,
    ),
    runnerRugOptimalMeasurements: mcc(
      "col-8MKf5R4",
      "string",
      "Runner rug optimal measurements",
      false,
    ),
    refrigeratorSpotDimensions: mcc(
      "col-vSvL3Rv",
      "string",
      "Refrigerator spot dimensions",
      false,
    ),
    dishwasherDimensions: mcc(
      "col-eZKABlO",
      "string",
      "Dishwasher dimensions",
      false,
    ),
    windowUnitAirConditioner: mcc(
      "col-Qa7kjlt",
      "string",
      "Window unit air conditioner",
      false,
    ),
    showerRodLength: mcc("col-7xQbB7A", "string", "Shower rod length", false),
    furnaceId: mcc("col-oCIcC_4", "string", "Furnace ID", false),
    furnaceName: mcc("col-1b27zS9", "string", "Furnace name", true),
    needAccessForFurnaceTuneUp: mcc(
      "col-tl-7F_a",
      "string",
      "Need access for furnace tune up",
      false,
    ),
    needAccessForFilterReplacement: mcc(
      "col-XKCYp-Z",
      "string",
      "Need access for filter replacement",
      false,
    ),
    avgGasBillMonthly: mcc(
      "col-O4spxsQ",
      "string",
      "Avg gas bill monthly",
      false,
    ),
    avgElectricBillMonthly: mcc(
      "col-CBzNuou",
      "string",
      "Avg electric bill monthly",
      false,
    ),
    laundryDays: mcc("col-JLxgTft", "string", "Laundry days", false),
    noticeGivenForRentIncrease: mcc(
      "col-9u79MPa",
      "string",
      "Notice given for rent increase",
      false,
    ),
    rentUpdateEnter: mcc("col-uwbyE7w", "boolean", "Rent update enter", false),
    rentUpdateStatus: mcc("col-k6cKvLp", "string", "Rent update status", false),
  },
  valueConfig: {
    id: mcc("col-KISd0k_", "string", "ID", false),
    transactionDescription: mcc(
      "col-My0v9xM",
      "string",
      "Transaction description",
      true,
    ),
    chargeDescription: mcc("col-4MRAohP", "string", "Charge description", true),
    chargeRecurringDescription: mcc(
      "col-LshlsTS",
      "string",
      "Charge recurring description",
      false,
    ),
    chargeOnetimeDescription: mcc(
      "col-ZFyzZf4",
      "string",
      "Charge onetime description",
      false,
    ),
    chargeReduceDescription: mcc(
      "col-FqR_6se",
      "string",
      "Charge reduce description",
      false,
    ),
    rentPortionName: mcc("col-LtgQHTi", "string", "Rent portion name", false),
    paymentType: mcc("col-9CulPu2", "string", "Payment type", false),
    payerCategory: mcc("col-_DwO2R3", "string", "Payer category", false),
    paymentAllocateWhat: mcc(
      "col-umhxhPg",
      "string",
      "Payment allocate what",
      false,
    ),
    expenseCategory: mcc("col-u0Fstxj", "string", "Expense category", false),
    expenseCategoryTaxable: mcc(
      "col-9XaRDGK",
      "string",
      "Expense category taxable",
      true,
    ),
    expenseCategoryBank: mcc(
      "col-k3_mD_q",
      "string",
      "Expense category bank",
      true,
    ),
    residenceTaxAdjust: mcc(
      "col-08YH-3Z",
      "string",
      "Residence tax adjust",
      false,
    ),
    receiptFormat: mcc("col-StBJQCC", "string", "Receipt format", false),
    firstOfEachMonthThisYear: mcc(
      "col-sgLi6Pa",
      "date",
      "First of each month this year",
      true,
    ),
    januaryQuartersThisYear: mcc(
      "col-iRu6A9m",
      "date",
      "January quarters this year",
      true,
    ),
    februaryQuartersThisYear: mcc(
      "col-ZOaq1Tm",
      "date",
      "February quarters this year",
      true,
    ),
    marchQuartersThisYear: mcc(
      "col-MZIxCW9",
      "date",
      "March quarters this year",
      true,
    ),
    yesOrNo: mcc("col-d5gC0K8", "string", "Yes or no", false),
    oneOccupancyOrAll: mcc(
      "col-qpxkX-L",
      "string",
      "One occupancy or all",
      false,
    ),
    buildingType: mcc("col-0eGzKFb", "string", "Building type", false),
    buildingTypeAndAny: mcc(
      "col-jJBNGWq",
      "string",
      "Building type and any",
      true,
    ),
  },
  valueName: {
    id: mcc("col-JhdzBMj", "string", "ID", false),
    valueName: mcc("col-35A6jyC", "string", "Value name", true),
  },
  variable: {
    id: mcc("col-bMRolLy", "string", "ID", false),
    today: mcc("col-07PPMWD", "date", "Today", true),
    "15thOfThisMonth": mcc("col-yfTbEv-", "date", "15th of this month", true),
    "2MonthsOut": mcc("col-_P8yYla", "date", "2 months out", true),
  },
  year: {
    id: mcc("col-MEgZSIX", "string", "ID", true),
    name: mcc("col-Z2qkqDh", "number", "Name", false),
    dayCount: mcc("col-hZo8xT2", "number", "Day count", true),
  },
} as const);
