import { makeStructuredConfig } from "../00_base/base";

export function makeValueConfigs<T extends Record<string, readonly string[]>>(
  valueConfigs: T,
): T {
  return makeStructuredConfig({} as Record<string, readonly string[]>, valueConfigs);
}

export const valueConfigs = makeValueConfigs({
  transactionDescription: [
    "Rent (base)",
    "Rent (utilities)",
    "Pet fee (recurring)",
    "Caretaker rent reduction",
    "Security deposit",
    "Late fee",
    "Damage, waste, or service",
    "Forgiveness",
  ],
  chargeDescription: [
    "Rent (base)",
    "Rent (utilities)",
    "Pet fee (recurring)",
    "Caretaker rent reduction",
    "Security deposit",
    "Late fee",
    "Damage, waste, or service",
    "Forgiveness",
  ],
  chargeRecurringDescription: [
    "Rent (base)",
    "Rent (utilities)",
    "Pet fee (recurring)",
    "Caretaker rent reduction",
  ],
  chargeOnetimeDescription: [
    "Security deposit",
    "Late fee",
    "Damage, waste, or service",
    "Forgiveness",
  ],
  chargeReduceDescription: ["Forgiveness", "Security deposit"],
  rentPortionName: ["Household", "Subsidy program"],
  paymentType: ["Currency", "Caretaking"],
  payerCategory: ["Household", "Non-resident"],
  paymentAllocateWhat: ["Full payment", "Full charge", "Lesser amount"],
  expenseCategory: [
    "Repair",
    "Supplies",
    "Cleaning & maintenance",
    "Depreciation expense or depletion",
    "Utilities",
    "Insurance",
    "Taxes",
    "Mortgage interest paid to banks",
    "Legal & professional",
    "Advertising",
    "Auto and travel",
    "Mgmt fees",
    "Commissions",
    "Other interest",
    "Other",
    "Principal",
  ],
  expenseCategoryTaxable: [
    "Repair",
    "Supplies",
    "Cleaning & maintenance",
    "Depreciation expense or depletion",
    "Utilities",
    "Insurance",
    "Taxes",
    "Mortgage interest paid to banks",
    "Legal & professional",
    "Advertising",
    "Auto and travel",
    "Mgmt fees",
    "Commissions",
    "Other interest",
    "Other",
  ],
  expenseCategoryBank: [
    "Insurance",
    "Taxes",
    "Mortgage interest paid to banks",
    "Principal",
  ],
  residenceTaxAdjust: [
    "Minus primary space",
    "Primary residence",
    "Half primary residence",
    "Minus primary time space",
  ],
  receiptFormat: [
    "Electronic",
    "Physical",
    "Cash ledger",
    "Text message",
    "Biller website",
    "Email",
    "Cash App",
    "Venmo",
    "Unknown",
  ],
  yesOrNo: ["Yes", "No"],
  oneOccupancyOrAll: ["One occupancy", "All"],
  buildingType: [
    "Small multifamily",
    "Single family home",
    "Apartment building",
  ],
  buildingTypeAndAny: [
    "Small multifamily",
    "Single family home",
    "Apartment building",
    "Any",
  ],
} as const);
