import { makeValueConfigs } from "./makeConfigs";

export const valueConfigs = makeValueConfigs({
  yesOrNo: ["Yes", "No"],
  chargeOnetimeDescription: [
    "Security deposit",
    "Late fee",
    "Damage, waste, or service",
    "Forgiveness",
  ],
  rentPortionName: ["Household", "Subsidy program"],
  chargeDescription: [
    "Rent (base)",
    "Rent (utilities)",
    "Pet fee (recurring)",
    "Caretaker rent reduction",
    "Security deposit",
    "Late fee",
    "Damage, waste, or service",
    "Forgiveness",
  ],
  payerCategory: ["Household", "Non-resident"],
  expenseCategory: [
    "Repair",
    "Supplies",
    "Cleaning & maintenance",
    "Depreciation expense or depletion",
    "Utilities",
    "Insurance",
    "Taxes",
    "Mortgage interest paid to banks",
    "Legal & professional",
    "Advertising",
    "Auto and travel",
    "Mgmt fees",
    "Commissions",
    "Other interest",
    "Other",
    "Principal",
  ],
  residenceTaxAdjust: [
    "Minus primary space",
    "Primary residence",
    "Half primary residence",
    "Minus primary time space",
  ],
  receiptFormat: [
    "Electronic",
    "Physical",
    "Cash ledger",
    "Text message",
    "Biller website",
    "Email",
    "Cash App",
    "Venmo",
    "Unknown",
  ],
  chargeReduceDescription: ["Forgiveness", "Security deposit"],
  paymentType: ["Currency", "Caretaking"],
  paymentAllocateWhat: ["Full payment", "Full charge", "Lesser amount"],
});
