import {
  cellValueNames,
  makeStructuredConfig,
} from "../1.0 Configs/0.0 ConfigPrecursors";
import {
  makeCellListValueschemas,
  valueConfigKeys,
} from "../1.0 Configs/4.0 valueConfig";
import { Dat } from "../utils/Dat";
import { valS } from "../utils/validation";
import { extractCellValue, vsc, type ValueSchemaBase } from "./3.0 valueSchema";

const valueNames = ["id", ...cellValueNames, ...valueConfigKeys] as const;
type ValueNameSimple = (typeof valueNames)[number];

type AllValueAttributesBase = Record<ValueNameSimple, ValueSchemaBase>;

const allValueAttributes = makeStructuredConfig(
  {} as AllValueAttributesBase,
  {
    id: vsc({
      type: "" as string,
      makeDefault: () => {
        throw new Error(
          "Attempted to make default value for an ID column from valueAttributes; it should be generated by a sheet schema.",
        );
      },
      strictValidate: valS.validate.string,
      extractCellValue: (colCell) => extractCellValue(colCell, "stringValue"),
      makeUserEnteredValue: (value) => ({ stringValue: value }),
    }),
    string: vsc({
      type: "" as string,
      makeDefault: () => "",
      strictValidate: valS.validate.string,
      extractCellValue: (colCell) => extractCellValue(colCell, "stringValue"),
      makeUserEnteredValue: (value) => ({ stringValue: value }),
    }),
    number: vsc({
      type: "" as number | "",
      makeDefault: () => "" as const,
      strictValidate: valS.validate.number,
      extractCellValue: (colCell) => extractCellValue(colCell, "numberValue"),
      makeUserEnteredValue: (value) =>
        typeof value === "string"
          ? { stringValue: value }
          : { numberValue: value },
    }),
    boolean: vsc({
      type: false as boolean | "",
      makeDefault: () => false,
      strictValidate: valS.validate.boolean,
      extractCellValue: (colCell) => extractCellValue(colCell, "boolValue"),
      makeUserEnteredValue: (value) =>
        typeof value === "string"
          ? { stringValue: value }
          : { boolValue: value },
    }),
    date: vsc({
      type: "" as Date | "",
      makeDefault: () => new Date(),
      strictValidate: valS.validate.date,
      extractCellValue: (colCell) =>
        extractCellValue(colCell, "numberValue", (value) =>
          Dat.serialToDate(value),
        ),
      makeUserEnteredValue: (value) =>
        typeof value === "string"
          ? { stringValue: value }
          : { numberValue: Dat.dateToSerial(value) },
    }),
    ...makeCellListValueschemas(),
  } as const,
); // I could add a "noEmpty" column to certain values.

export type AllValueAttributes = typeof allValueAttributes;
export type ValueName<V extends ValueNameSimple = ValueNameSimple> = V;
export type ValueAttributes<VN extends ValueName = ValueName> =
  AllValueAttributes[VN];

export function getValueAttribute<
  VN extends ValueNameSimple,
  K extends keyof ValueAttributes<VN>,
>(valueName: VN, key: K): ValueAttributes<VN>[K] {
  return allValueAttributes[valueName][key];
}

export type Value<VN extends ValueName = ValueName> =
  ValueAttributes<VN>["type"];

export type MakeDefaultValue<VN extends ValueName> = () => Value<VN>;
export type ValidateValue<VN extends ValueName> = (value: unknown) => Value<VN>;
