import {
  makeStructuredConfig,
  nameDelimiter,
  type NameDelimiter,
} from "../00_base/base";
import { Obj, type KeyedMap } from "../utils/Obj";
import { valS } from "../utils/validation";
import {
  getSheetTraitByName,
  schemaSheetNames,
  type SheetNameSimple,
} from "./02_sheetTraitsTypes";
import {
  type Value,
  type ValueName,
  type ValueSchema,
} from "./06_valueSchemas";

export interface ColTraitsLiteral {
  columnId: string;
  header: string;
  isFormula: boolean;
  emptyAllowed: boolean;
}
export interface ColTraitsBase<
  VN extends ValueName = ValueName,
> extends ColTraitsLiteral {
  valueName: VN;
  customDefaultValue: Value<VN> | null;
}
function makeColTraits<VN extends ValueName>(
  columnId: string,
  valueName: VN,
  header: string,
  isFormula: boolean,
  emptyAllowed: boolean = false,
  customDefaultValue: Value<VN> | null = null,
): ColTraitsBase<VN> {
  return {
    columnId,
    valueName,
    header,
    isFormula,
    emptyAllowed,
    customDefaultValue,
  };
}

const mcs = makeColTraits;
type TableColTraitsBase = Record<string, ColTraitsBase>;
type AllColTraitsBase = Record<SheetNameSimple, TableColTraitsBase>;

const allColTraits = makeStructuredConfig(
  {} as AllColTraitsBase,
  {
    spreadsheetControls: {
      fillRowIdsLastRan: mcs(
        "col-045qGg4",
        "string",
        "Fill row IDs, last ran",
        false,
      ),
      fillRowIdsRunAndStatus: mcs(
        "col-0g24qGg",
        "string",
        "Fill row IDs, run and status",
        false,
      ),
      appendSheetAndColumnConfigRowsLastRan: mcs(
        "col-0g340Gg",
        "string",
        "Append sheet and column config rows, last ran",
        false,
      ),
      appendSheetAndColumnConfigRowsRunAndStatus: mcs(
        "col-0g34slk",
        "string",
        "Append sheet and column config rows, run and status",
        false,
      ),
    },
    addExpenses: {
      date: mcs("col-vXNHJps", "string", "Date", false),
      propertyName: mcs("col-_iOHEPj", "string", "Property name", false),
      unitName: mcs("col-OBqodd0", "string", "Unit name", false),
      billerName: mcs("col-xp4RR28", "string", "Biller name", false),
      description: mcs("col-pRON8SW", "string", "Description", false),
      amount: mcs("col-sE7oAfr", "string", "Amount", false),
      expenseCategory: mcs(
        "col-vgdpQaI",
        "expenseCategory",
        "Expense category",
        false,
      ),
      taxAdjust: mcs("col-T6Qbxvk", "residenceTaxAdjust", "Tax adjust", false),
      receiptFormat: mcs(
        "col-yQtzinN",
        "receiptFormat",
        "Receipt format",
        false,
      ),
      notes: mcs("col-V7s3k7A", "string", "Notes", false),
      householdToCharge: mcs(
        "col-nGxFx4D",
        "string",
        "Household to charge",
        false,
      ),
      householdChargeLesserAmount: mcs(
        "col-OLIOifY",
        "string",
        "Household charge lesser amount",
        false,
      ),
      hhChargeNotes: mcs("col-6w_8wXP", "string", "HH charge notes", false),
      householdId: mcs("col-Mx2BiCo", "string", "Household ID", true),
      id: mcs("col-Wn1oOom", "string", "ID", true),
      propertyId: mcs("col-7hwOnld", "string", "Property ID", true),
      unitId: mcs("col-6mhn61V", "string", "Unit ID", true),
      enter: mcs("col-wipvQ46", "boolean", "Enter", false),
      enterStatus: mcs("col-jFOlWsa", "string", "Enter status", false),
    },
    addHhPaymentOnetime: {
      householdName: mcs("col-JxtgYhJ", "string", "Household name", false),
      portion: mcs("col-9qc_UOo", "rentPortionName", "Portion", false),
      description: mcs(
        "col-OBqwLsb",
        "chargeDescription",
        "Description",
        false,
      ),
      amount: mcs("col-6Z-g6aN", "string", "Amount", false),
      unitName: mcs("col-YP9kC8o", "string", "Unit name", true),
      subsidyAgreementName: mcs(
        "col-Ligyt6Y",
        "string",
        "Subsidy agreement name",
        false,
      ),
      id: mcs("col-kU0tGW_", "string", "ID", true),
      householdId: mcs("col-noXL_e_", "string", "Household ID", true),
      unitId: mcs("col-fzBlkyl", "string", "Unit ID", true),
      subsidyAgreementId: mcs(
        "col--w2ekts",
        "string",
        "Subsidy agreement ID",
        true,
      ),
      date: mcs("col-u5S1p53", "date", "Date", true),
      detailsVerified: mcs("col-Wb5wdwz", "string", "Details verified", false),
      payerCategory: mcs(
        "col-bXBsrNU",
        "payerCategory",
        "Payer category",
        false,
      ),
      paymentHhName: mcs("col-Y7a0Yut", "string", "Payment HH name", true),
      subsidyProgramName: mcs(
        "col-DHgo-6o",
        "string",
        "Subsidy program name",
        false,
      ),
      otherPayerName: mcs("col-W7b2hGx", "string", "Other payer name", false),
      paymentHhId: mcs("col-TGUKG69", "string", "Payment HH ID", true),
      subsidyProgramId: mcs(
        "col-XedCXAM",
        "string",
        "Subsidy program ID",
        true,
      ),
      otherPayerId: mcs("col-OYsbh1q", "string", "Other payer ID", true),
      notes: mcs("col-KTl705t", "string", "Notes", false),
      enter: mcs("col-6PNfr_e", "boolean", "Enter", false),
      enterStatus: mcs("col-OHc-nd9", "string", "Enter status", false),
    },
    addOccChargeOnetime: {
      date: mcs("col-RcPqzF2", "date", "Date", true),
      householdName: mcs("col-olQUfAZ", "string", "Household name", false),
      amount: mcs("col-wS5UkZR", "string", "Amount", false),
      description: mcs(
        "col-fq3Wkwf",
        "chargeOnetimeDescription",
        "Description",
        false,
      ),
      unitName: mcs("col-A18WumZ", "string", "Unit name", true),
      householdId: mcs("col-S0LLFch", "string", "Household ID", true),
      unitId: mcs("col-43FJGcv", "string", "Unit ID", true),
      notes: mcs("col-rEqlwlw", "string", "Notes", false),
      id: mcs("col-VG-Y2z7", "string", "ID", true),
      enter: mcs("col-auSNCDT", "boolean", "Enter", false),
      enterStatus: mcs("col-MuVUEGl", "string", "Enter status", false),
    },
    columnConfig: {
      id: mcs("col-K9DptS1", "string", "ID", false),
      sheetName: mcs("col-U6y6xUt", "string", "Sheet name camel case", false),
      columnIndexBase0: mcs(
        "col-83ENHF2",
        "number",
        "Column index base 0",
        false,
      ),
      header: mcs("col-imgVzE3", "string", "Header", false),
      camelCaseHeader: mcs("col-wHrc1Q3", "string", "Camel case header", false),
      isFormula: mcs("col-F2caCWz", "boolean", "Is formula", false),
      valueName: mcs("col-PeplPjS", "string", "Value name", false),
      emptyAllowed: mcs("col-chk-U97", "boolean", "Empty allowed", false),
      customDefaultValue: mcs(
        "col-mdbDepg",
        "string",
        "Custom default value",
        false,
      ),
    },
    sheetConfig: {
      id: mcs("col-90lQMkS", "string", "ID", true),
      sheetGid: mcs("col-fqCrMdm", "number", "Sheet GID", false),
      sheetName: mcs("col-ssYwA1T", "string", "Sheet name camel case", false),
      idPrefix: mcs("col-iqW3fCT", "string", "ID prefix", false),
    },
    api: {
      id: mcs("col-ohQJSZw", "string", "ID", true),
      ulsLastRan: mcs("col-o3z5zKF", "string", "ULS last ran", false),
      ulsEnter: mcs("col-H147sTm", "boolean", "ULS enter", false),
      ulsEnterStatus: mcs("col-2Hh5Tiv", "string", "ULS enter status", false),
      upcLastRan: mcs("col-MVPM3jg", "string", "UPC last ran", false),
      upcStartMonth: mcs("col-dBUrfx_", "date", "UPC start month", false),
      upcEndMonth: mcs("col-QIU-hI6", "date", "UPC end month", false),
      upcMode: mcs("col-lw1GArS", "oneOccupancyOrAll", "UPC mode", false),
      upcHousehold: mcs("col-JAZwV4Z", "string", "UPC household", false),
      upcHouseholdId: mcs("col-jL103Fz", "string", "UPC household ID", true),
      upcEnter: mcs("col-2CcZP7l", "boolean", "UPC enter", false),
      upcEnterStatus: mcs("col-7zKZtJP", "string", "UPC enter status", false),
      aepLastRan: mcs("col-NpC_m7j", "string", "AEP last ran", false),
      aepEnter: mcs("col-SkBfBWg", "boolean", "AEP enter", false),
      aepEnterStatus: mcs("col-lhC7IXV", "string", "AEP enter status", false),
      bhlLastRan: mcs("col-s3TA0Js", "date", "BHL last ran", false),
      bhlLastRanHouseholdAndUnit: mcs(
        "col-koaPkot",
        "string",
        "BHL last ran household and unit",
        true,
      ),
      bhlHouseholdIdLastRan: mcs(
        "col-Bt_hiLJ",
        "string",
        "BHL household ID last ran",
        false,
      ),
      bhlUnitIdLastRan: mcs(
        "col-YgNpwF1",
        "string",
        "BHL unit ID last ran",
        true,
      ),
      bhlHouseholdName: mcs(
        "col-qbSdWm7",
        "string",
        "BHL household name",
        false,
      ),
      bhlHouseholdId: mcs("col-L2Vwjlr", "string", "BHL household ID", true),
      bhlPortion: mcs("col-66PEBlM", "rentPortionName", "BHL portion", false),
      bhlSubsidyAgreementName: mcs(
        "col-7Dl8V9w",
        "string",
        "BHL subsidy agreement name",
        false,
      ),
      bhlSubsidyAgreementId: mcs(
        "col--Cx2izo",
        "string",
        "BHL subsidy agreement ID",
        true,
      ),
      bhlEnter: mcs("col-bBZV44s", "boolean", "BHL enter", false),
      bhlEnterStatus: mcs("col-VHVRiOc", "string", "BHL enter status", false),
    },
    biller: {
      name: mcs("col-IAA7ymg", "string", "Name", false),
      contact: mcs("col-TECY-w9", "string", "Contact", false),
      id: mcs("col-pBwZ74w", "string", "ID", true),
      category: mcs("col-HmUfHCe", "string", "Category", false),
      defaultExpenseCategory: mcs(
        "col-lZdCfdb",
        "string",
        "Default expense category",
        false,
      ),
      defaultExpenseDescription: mcs(
        "col-Q7pTk6J",
        "string",
        "Default expense description",
        false,
      ),
      notes: mcs("col-ioUEJuB", "string", "Notes", false),
    },
    buildOccLedger: {
      dateLastRan: mcs("col-56paOQ6", "date", "Date last ran", false),
      householdIdLastRan: mcs(
        "col-h8wdhIm",
        "string",
        "Household ID last ran",
        false,
      ),
      unitIdLastRan: mcs("col-kN5w1ui", "string", "Unit ID last ran", true),
      occupancyName: mcs("col-2IST_DW", "string", "Occupancy name", false),
      portion: mcs("col-javENeZ", "rentPortionName", "Portion", false),
      householdId: mcs("col-9K87DiZ", "string", "Household ID", true),
      subsidyAgreementName: mcs(
        "col-pJqCDM_",
        "string",
        "Subsidy agreement name",
        false,
      ),
      subsidyAgreementId: mcs(
        "col-bdXnDU7",
        "string",
        "Subsidy agreement ID",
        true,
      ),
      id: mcs("col-qFYr3BR", "string", "ID", true),
      enter: mcs("col-0pQVFbo", "boolean", "Enter", false),
      enterStatus: mcs("col-NReu6z0", "string", "Enter status", false),
    },
    businessExpense: {
      date: mcs("col-viByQSW", "date", "Date", false),
      amount: mcs("col-wH6T9oD", "number", "Amount", false),
      description: mcs("col-sGzmf3i", "string", "Description", false),
      deductibleAmount: mcs("col-D4Um8gD", "string", "Deductible amount", true),
      id: mcs("col-gI3wWFP", "string", "ID", true),
      billerName: mcs("col-ws-Kl9O", "string", "Biller name", false),
      expenseCategory: mcs(
        "col-1FLurWI",
        "expenseCategory",
        "Expense category",
        false,
      ),
      receiptFormat: mcs(
        "col-PXfEBEq",
        "receiptFormat",
        "Receipt format",
        false,
      ),
      taxAdjust: mcs("col-FjnqqGg", "residenceTaxAdjust", "Tax adjust", false),
      notes: mcs("col--TmFGAd", "string", "Notes", false),
    },
    capex: {
      id: mcs("col-A_L0nQO", "string", "ID", false),
      name: mcs("col-wQVendk", "string", "Name", false),
      unitCost: mcs("col-zeNzhyO", "number", "Unit cost", false),
      propertyMultiplierName: mcs(
        "col-ZTAY92_",
        "string",
        "Property multiplier name",
        false,
      ),
      lifespanYears: mcs("col-U6_ZT0o", "number", "Lifespan years", false),
      lifespanMonths: mcs("col-YqvaRuI", "number", "Lifespan months", true),
      preference: mcs("col-4zmF0qs", "string", "Preference", false),
    },
    spreadsheetConfig: {
      id: mcs("col-LAM-LoC", "string", "ID", false),
      headerRowIndexBase1: mcs(
        "col-hOXiFmz",
        "number",
        "Header row idx base 1",
        false,
      ),
      topDataRowIdxBase1: mcs(
        "col-DZ4VSLw",
        "number",
        "Top body row idx base 1",
        false,
      ),
      columnIdRowIdxBase1: mcs(
        "col-4ySoLne",
        "number",
        "Column id row idx base 1",
        false,
      ),
      idDelimiter: mcs("col-zR-sehH", "string", "ID delimiter", false),
      activePaymentStandardYear: mcs(
        "col-mW2UEKf",
        "number",
        "Active payment standard year",
        false,
      ),
      domLateFeeCharged: mcs(
        "col-ZsjeOd2",
        "number",
        "DOM late fee charged",
        false,
      ),
    },
    export: {
      id: mcs("col-7HTLbQE", "string", "ID", false),
      necessaryAverageCostsMonthly: mcs(
        "col-iE08rV_",
        "number",
        "Necessary average costs monthly",
        true,
      ),
      subsidyPaymentsMonthly: mcs(
        "col-c2XXKTP",
        "number",
        "Subsidy payments monthly",
        true,
      ),
      tenantPaymentsMonthly: mcs(
        "col-vb-UnbW",
        "string",
        "Tenant payments monthly",
        true,
      ),
      realEstateCostsMinusTenantPayments: mcs(
        "col-nQar3gw",
        "string",
        "Real estate costs minus tenant payments",
        true,
      ),
      businessCheckingBalance: mcs(
        "col-b684Igh",
        "number",
        "Business checking balance",
        true,
      ),
      businessCheckingBalanceMinusNextBankPayments: mcs(
        "col-M1iFwht",
        "number",
        "Business checking balance minus next bank payments",
        true,
      ),
    },
    finance: {
      id: mcs("col-rXqzRW-", "string", "ID", false),
      businessAccountBankPaymentCushion: mcs(
        "col-VttZ8-h",
        "number",
        "Business account bank payment cushion",
        true,
      ),
      businessCashAccount: mcs(
        "col-E5Sd1yv",
        "number",
        "Business Cash Account",
        true,
      ),
      businessAccountDebt: mcs(
        "col-qLIGagR",
        "number",
        "Business Account Debt",
        true,
      ),
      helocAvailable: mcs("col-8eXfJd9", "number", "HELOC available", true),
      helocSpent: mcs("col-dypG3j3", "number", "HELOC spent", true),
      bankUtilityPaymentsMonthlyAvg: mcs(
        "col-UkNYRTj",
        "number",
        "Bank + utility payments monthly avg",
        true,
      ),
      bankPaymentsMonthly: mcs(
        "col-RuG2S80",
        "number",
        "Bank payments monthly",
        true,
      ),
      mortgagePaymentsMonthly: mcs(
        "col-GJ3W5CH",
        "number",
        "Mortgage payments monthly",
        true,
      ),
      helocPaymentsMonthly: mcs(
        "col-_F9eVFO",
        "number",
        "HELOC payments monthly",
        true,
      ),
      utilityPaymentsMonthlyAvg: mcs(
        "col-WNSnm31",
        "number",
        "Utility payments monthly avg",
        true,
      ),
      budgetsMonthly: mcs("col-LqC3tvw", "number", "Budgets monthly", true),
      maintenanceBudgetMonthly: mcs(
        "col-Usg-WMU",
        "number",
        "Maintenance budget monthly",
        true,
      ),
      lawncareBudgetMonthly: mcs(
        "col-USPILuC",
        "number",
        "Lawncare budget monthly",
        true,
      ),
      capExBudgetMonthly: mcs(
        "col-zrcshgj",
        "number",
        "Cap-Ex budget monthly",
        true,
      ),
      vacancyBudgetMonthly: mcs(
        "col-0MFgFfN",
        "number",
        "Vacancy budget monthly",
        true,
      ),
      flexibleIncomeMonthlyAvg: mcs(
        "col-Kctzpyn",
        "string",
        "Flexible income monthly avg",
        true,
      ),
      discretionaryIncomeMonthlyAvg: mcs(
        "col-S4V6HuT",
        "string",
        "Discretionary income monthly avg",
        true,
      ),
      realEstateReceivableMonthly: mcs(
        "col-pCYNnOt",
        "string",
        "Real estate receivable monthly",
        true,
      ),
      subsidyIncomeMonthly: mcs(
        "col-ojc6Pj3",
        "number",
        "Subsidy income Monthly",
        true,
      ),
      tenantIncomeMonthly: mcs(
        "col-fSe_zos",
        "string",
        "Tenant income Monthly",
        true,
      ),
    },
    furnace: {
      name: mcs("col-WgcleWq", "string", "Name", true),
      id: mcs("col-pjjrcyC", "string", "ID", true),
      propertyId: mcs("col-qM5MaTT", "string", "Property ID", false),
      propertyName: mcs("col-MDkBZw7", "string", "Property name", true),
      location: mcs("col--nrSW5N", "string", "Location", false),
      descriptor: mcs("col-3IqlZi_", "string", "Descriptor", false),
      brand: mcs("col-19ohP9V", "string", "Brand", false),
      yearBuilt: mcs("col-Jv4pMFL", "number", "Year built", false),
      age: mcs("col-333qv5F", "number", "Age", true),
      filterSize: mcs("col-sPRYcYC", "string", "Filter size", false),
      filterLocation: mcs("col-aOWKf6H", "string", "Filter location", false),
      filtersPresent: mcs("col-Q5FZff_", "number", "Filters present", false),
      filterLastReplaced: mcs(
        "col-VnZPpE8",
        "date",
        "Filter last replaced",
        false,
      ),
    },
    hhLedger: {
      date: mcs("col-9fBrgEn", "string", "Date", false),
      id: mcs("col-K6z58MJ", "string", "ID", true),
      unit: mcs("col-Gp-A2rX", "string", "Unit", false),
      issuer: mcs("col-6w2_q8O", "string", "Issuer", false),
      description: mcs("col-NUiKLPH", "string", "Description", false),
      charge: mcs("col-Uty4AVV", "string", "Charge", false),
      payment: mcs("col-qa5Sh_a", "string", "Payment", false),
      amountOwed: mcs("col-5pNKEjq", "string", "Amount owed", true),
      notes: mcs("col-zU1zrqH", "string", "Notes", false),
    },
    household: {
      name: mcs("col--IaO_J8", "string", "Name", true),
      id: mcs("col-e0nP-e3", "string", "ID", true),
      fullName: mcs("col-YICAuy6", "string", "Full name", true),
      residentCount: mcs("col-kSe11BO", "number", "Resident count", true),
      residentFullNames: mcs(
        "col-QD287on",
        "string",
        "Resident full names",
        true,
      ),
      residentFirstNames: mcs(
        "col-iqcpd0w",
        "string",
        "Resident first names",
        true,
      ),
      isActive: mcs("col-xKY_f2p", "string", "Is active", true),
      latestOccupancyId: mcs(
        "col-hvhiRQA",
        "string",
        "Latest occupancy ID",
        true,
      ),
      unitId: mcs("col-6T5u_QM", "string", "Unit ID", true),
      unitName: mcs("col-VNunYf2", "string", "Unit name", true),
      propertyId: mcs("col-uja0Yrs", "string", "Property ID", true),
      subsidyCount: mcs("col-N3Mr2EQ", "number", "Subsidy count", true),
      nextRentNoticeDate: mcs(
        "col-bCbIa94",
        "date",
        "Next rent notice date",
        true,
      ),
      "2MonthsFromLastNotice": mcs(
        "col-Ps_QhMG",
        "date",
        "2 months from last notice",
        true,
      ),
      properNoticeBeforeNextIncrease: mcs(
        "col-nCgODfJ",
        "date",
        "Proper notice before next increase",
        true,
      ),
      properNoticeAfterNextIncrease: mcs(
        "col-GWnB0N2",
        "date",
        "Proper notice after next increase",
        true,
      ),
      lastRentNoticeDate: mcs(
        "col-FJ8iUCl",
        "date",
        "Last rent notice date",
        false,
      ),
      nextRentChangeDate: mcs(
        "col-nryi7Ib",
        "date",
        "Next rent change date",
        true,
      ),
      nextRentIncreaseDateOverride: mcs(
        "col-jnm0WWU",
        "string",
        "Next rent increase date override",
        false,
      ),
      nextIncreaseDateIfNoticeNotGiven: mcs(
        "col-pFdQ2wc",
        "date",
        "Next increase date if notice not given",
        true,
      ),
      nextIncreaseDateIfNoticeGiven: mcs(
        "col-jS7wkf6",
        "date",
        "Next increase date if notice given",
        true,
      ),
      increaseAnnualDate: mcs(
        "col--UUuPBE",
        "date",
        "Increase annual date",
        true,
      ),
      currentLeaseId: mcs("col-NTsT2xI", "string", "Current lease ID", false),
      lastRentChangeDate: mcs(
        "col-Y0_rdiQ",
        "date",
        "Last rent change date",
        true,
      ),
      firstRentChargeDate: mcs(
        "col-alSTrIH",
        "string",
        "First rent charge date",
        true,
      ),
      lastDayRented: mcs("col-XePDi4w", "date", "Last day rented", true),
      baseRentChargeMonthly: mcs(
        "col-BxUxPE3",
        "number",
        "Base rent charge monthly",
        true,
      ),
      nextBaseRentChargeMonthly: mcs(
        "col-BjuCaR7",
        "number",
        "Next base rent charge monthly",
        true,
      ),
      increaseBy: mcs("col-Ld9NSxu", "number", "Increase by %", true),
      nextRentChargeOverride: mcs(
        "col-DDMUsEe",
        "string",
        "Next rent charge override",
        false,
      ),
      increaseByOverride: mcs(
        "col-DzDssB7",
        "string",
        "Increase by % override",
        false,
      ),
      increaseBy3PerYear: mcs(
        "col-cUIfPaL",
        "number",
        "Increase by 3% per year",
        true,
      ),
      nextMinusLastIncreaseYears: mcs(
        "col-fEFknBM",
        "number",
        "Next minus last increase years",
        true,
      ),
      daysInNextRentIncreaseYear: mcs(
        "col-qdUg1o-",
        "number",
        "Days in next rent increase year",
        true,
      ),
      rentReasonablenessBaseRentMax: mcs(
        "col-1tbaSjP",
        "string",
        "Rent reasonableness base rent max",
        true,
      ),
      nextGrossRentMonthly: mcs(
        "col-6vZwa1y",
        "string",
        "Next gross rent monthly",
        true,
      ),
      grossRentMonthly: mcs(
        "col-FXIspcm",
        "string",
        "Gross rent monthly",
        true,
      ),
      rentReasonablenessGrossRentMax: mcs(
        "col-lmqcCkk",
        "string",
        "Rent reasonableness gross rent max",
        true,
      ),
      rentCompType: mcs("col-rsTDTeF", "string", "Rent comp type", true),
      paymentStandardGrossRentMax: mcs(
        "col-szqb-Cu",
        "string",
        "Payment standard gross rent max",
        true,
      ),
      paymentStandardUtilities: mcs(
        "col-8FfdKef",
        "string",
        "Payment standard utilities",
        true,
      ),
      paymentStandardName: mcs(
        "col-OgGGOhY",
        "string",
        "Payment standard name",
        true,
      ),
      gasHeating: mcs("col-RWqNDKN", "boolean", "Gas Heating", false),
      electricHeating: mcs("col-s6dJhNw", "boolean", "Electric Heating", false),
      gasCooking: mcs("col-lTFdWvg", "boolean", "Gas Cooking", false),
      electricCooking: mcs("col-JkMRVe3", "boolean", "Electric Cooking", false),
      otherElectric: mcs("col-OT1NP05", "boolean", "Other Electric", false),
      gasWaterHeating: mcs(
        "col-1u19gB4",
        "boolean",
        "Gas Water Heating",
        false,
      ),
      electricWaterHeating: mcs(
        "col-c8031x6",
        "boolean",
        "Electric Water Heating",
        false,
      ),
      waterSewer: mcs("col-d96lUou", "boolean", "Water & Sewer", false),
      trashCollection: mcs("col-uYwbwrh", "boolean", "Trash Collection", false),
      districtEnergyHeating: mcs(
        "col-C6cHg7u",
        "boolean",
        "District Energy Heating",
        false,
      ),
      districtEnergyWaterHeating: mcs(
        "col-N6LwTYC",
        "boolean",
        "District Energy Water Heating",
        false,
      ),
      netChargeMonthly: mcs(
        "col-W735ss-",
        "string",
        "Net charge monthly",
        true,
      ),
      caretakerRentReductionMonthly: mcs(
        "col-VlkCkKM",
        "string",
        "Caretaker rent reduction monthly",
        true,
      ),
      petFeeMonthly: mcs("col-ZYvV_a2", "number", "Pet fee monthly", true),
      hhTotalPaymentMonthly: mcs(
        "col-WOCcFgo",
        "string",
        "HH total payment monthly",
        true,
      ),
      hhBaseRentPortionMonthly: mcs(
        "col-iWlLmUs",
        "number",
        "HH base rent portion monthly",
        true,
      ),
      subsidyRentPortionMonthly: mcs(
        "col-0S-3LvX",
        "number",
        "Subsidy rent portion monthly",
        true,
      ),
      currentHhBalance: mcs(
        "col-T3P1irS",
        "string",
        "Current hh balance",
        true,
      ),
      totalHhCharges: mcs("col-oaHTV9l", "string", "Total hh charges", true),
      totalHhPayments: mcs("col-D6EPFV3", "string", "Total hh payments", true),
      depositCharged: mcs("col-ft6MFJu", "number", "Deposit charged", true),
      depositReceived: mcs("col-FDyT3Vx", "number", "Deposit received", true),
      currentSubsidyBalance: mcs(
        "col-0OkeFPc",
        "string",
        "Current subsidy balance",
        true,
      ),
      totalSubsidyCharges: mcs(
        "col-owX13pV",
        "string",
        "Total subsidy charges",
        true,
      ),
      totalSubsidyPayments: mcs(
        "col-829U06m",
        "string",
        "Total subsidy payments",
        true,
      ),
      grandPaymentTotalForTaxes: mcs(
        "col-A2Xqlyb",
        "string",
        "Grand payment total for taxes",
        false,
      ),
      tenantPaymentTotalForTaxes: mcs(
        "col-aDrn-R0",
        "string",
        "Tenant payment total for taxes",
        false,
      ),
      phaPaymentTotalForTaxes: mcs(
        "col-dDeXl-9",
        "string",
        "PHA payment total for taxes",
        false,
      ),
    },
    householdProspect: {
      name: mcs("col-pMwl8_N", "string", "Name", false),
      id: mcs("col-cqj4thW", "string", "ID", true),
      totalIncomeMonthly: mcs(
        "col-7k3rBt_",
        "number",
        "Total income monthly",
        true,
      ),
      dependents: mcs("col-grW56Jj", "number", "Dependents", false),
      pets: mcs("col-xXB1s_l", "string", "Pets", false),
    },
    householdYear: {
      name: mcs("col-j48UWNj", "string", "Name", true),
      id: mcs("col-slPqvjH", "string", "ID", true),
      occupancyId: mcs("col-5NpZpfU", "string", "Occupancy ID", false),
      year: mcs("col-JPQvvQo", "number", "Year", false),
      residentCount: mcs("col-bvqNtvg", "number", "Resident count", true),
      householdRentPaidPerResident: mcs(
        "col-tzpNLQZ",
        "number",
        "Household rent paid per resident",
        true,
      ),
      caretakerRentReducedPerResident: mcs(
        "col-FIAS76q",
        "number",
        "Caretaker rent reduced per resident",
        true,
      ),
      totalAttributedPerResident: mcs(
        "col-nXoe3eF",
        "number",
        "Total attributed per resident",
        true,
      ),
      totalAttributedToOccupancy: mcs(
        "col-dD8eVIq",
        "number",
        "Total attributed to occupancy",
        true,
      ),
      caretakerRentReduced: mcs(
        "col-55cJEpn",
        "number",
        "Caretaker rent reduced",
        true,
      ),
      householdRentPaid: mcs(
        "col-1dAHPjH",
        "number",
        "Household rent paid",
        true,
      ),
      firstDateChargedRentInYear: mcs(
        "col-3XZvYtM",
        "date",
        "First date charged rent in year",
        true,
      ),
      lastDateChargedRentInYear: mcs(
        "col-Jm50CK4",
        "date",
        "Last date charged rent in year",
        true,
      ),
      firstRentChargeDate: mcs(
        "col-zvBywR1",
        "date",
        "First rent charge date",
        true,
      ),
      lastDateChargedRent: mcs(
        "col-0VgdtTA",
        "date",
        "Last date charged rent",
        true,
      ),
      subsidyRentPaid: mcs("col-OipY03K", "number", "Subsidy rent paid", true),
      scrollSpace: mcs("col-SqUK6d0", "string", "_scroll space", false),
    },
    materialCost: {
      id: mcs("col-uGd0dOc", "string", "ID", false),
      item: mcs("col-VH8n1pn", "string", "Item", false),
      v1Name: mcs("col-zwyYm9d", "string", "V1 name", false),
      v1Cost: mcs("col-UhEx93h", "number", "V1 cost", false),
      v1Count: mcs("col-f_qLF8F", "number", "V1 count", false),
      v2Name: mcs("col-QdlP7OT", "string", "V2 name", false),
      v2Cost: mcs("col-J9MMP8s", "string", "V2 cost", false),
    },
    nonResidentPayer: {
      name: mcs("col-K_eFNP9", "string", "Name", false),
      id: mcs("col-rrScEfG", "string", "ID", true),
    },
    occCharge: {
      name: mcs("col-udxK-Hf", "string", "Name", true),
      id: mcs("col-nLiqq-6", "string", "ID", true),
      occupancyId: mcs("col-IrTjVUr", "string", "Occupancy ID", false),
      occupancyName: mcs("col-VGP6Bgk", "string", "Occupancy name", true),
      date: mcs("col-rdw667_", "date", "Date", false),
      description: mcs("col-Z5b__-f", "string", "Description", false),
      amount: mcs("col-bDbtLKn", "number", "Amount", false),
      amountAccounted: mcs("col-OCiouvy", "number", "Amount accounted", true),
      amountUnaccounted: mcs(
        "col-N4oYQrk",
        "number",
        "Amount unaccounted",
        true,
      ),
      notes: mcs("col-wsWXgR4", "string", "Notes", false),
    },
    occChargeReduce: {
      id: mcs("col-1rSG9i_", "string", "ID", true),
      date: mcs("col-9FwOGpt", "date", "Date", false),
      chargeId: mcs("col-3zLvJOz", "string", "Charge ID", false),
      chargeName: mcs("col-pW6NptW", "string", "Charge name", true),
      description: mcs(
        "col-s_hOaKR",
        "chargeReduceDescription",
        "Description",
        false,
      ),
      chargeAmount: mcs("col-bBHlDi-", "number", "Charge amount", true),
      amount: mcs("col-kzsS2s_", "number", "Amount", true),
      reduceFullAmount: mcs(
        "col-2KKhHBO",
        "boolean",
        "Reduce full amount",
        false,
      ),
      lesserAmount: mcs("col-sRi8MA4", "string", "Lesser amount", false),
    },
    occPayAllocation: {
      name: mcs("col-EL5Jx4e", "string", "Name", true),
      occupancyName: mcs("col-vK3JZeg", "string", "Occupancy name", true),
      id: mcs("col-0RTP0fy", "string", "ID", true),
      paymentId: mcs("col-sCLgGiO", "string", "Payment id", false),
      payerCategory: mcs("col-MFTWV8M", "string", "Payer category", true),
      payerName: mcs("col-la7Ma45", "string", "Payer name", true),
      formOfPayment: mcs("col-M6W-rV_", "string", "Form of payment", true),
      paymentAllocated: mcs("col-_q_cK2F", "number", "Payment allocated", true),
      paymentDate: mcs("col-6ORlom4", "date", "Payment date", true),
      paymentAmount: mcs("col-LDzLVDD", "number", "Payment amount", true),
      chargeId: mcs("col-9zJ7Xt4", "string", "Charge id", false),
      occupancyId: mcs("col-v_hGHUV", "string", "Occupancy id", true),
      propertyId: mcs("col-fmJ3xRA", "string", "Property id", true),
      chargeDescription: mcs(
        "col-A8yIJGL",
        "string",
        "Charge description",
        true,
      ),
      chargePaid: mcs("col-1uuH5TK", "number", "Charge paid", true),
      chargeDate: mcs("col-okGjzno", "date", "Charge date", true),
      chargeAmount: mcs("col-NQN3uEw", "number", "Charge amount", true),
      paymentSummary: mcs("col-aRUT8Yn", "string", "Payment summary", true),
      chargeSummary: mcs("col-_6eV_gi", "string", "Charge summary", true),
      paymentUnallocated: mcs(
        "col-EnmorGU",
        "number",
        "Payment unallocated",
        true,
      ),
      chargeUnpaid: mcs("col-Ue-A9_V", "number", "Charge unpaid", true),
      amount: mcs("col-Mz8l5TA", "number", "Amount", true),
      allocateWhat: mcs(
        "col-YZpq7hn",
        "paymentAllocateWhat",
        "Allocate what",
        false,
      ),
      lesserAmount: mcs("col-vMrDrB6", "number", "Lesser amount", false),
      filledOut: mcs("col-e9I0oXB", "string", "Filled out", true),
      processed: mcs("col-ufcTD5Q", "yesOrNo", "Processed", true),
    },
    occPayment: {
      id: mcs("col-5p14Hz-", "string", "ID", true),
      paymentName: mcs("col-JL9ycn7", "string", "Payment name", true),
      allocationName: mcs("col-HwbqxPk", "string", "Allocation name", true),
      date: mcs("col-v7ZMbTS", "date", "Date", false),
      payerCategory: mcs(
        "col-jU98tyc",
        "payerCategory",
        "Payer category",
        false,
      ),
      payerName: mcs("col-W340xfW", "string", "Payer name", true),
      householdId: mcs("col-2UvItSc", "string", "Household ID", false),
      nonResidentPayerId: mcs(
        "col-Y8oUjzx",
        "string",
        "Non-resident payer ID",
        false,
      ),
      formOfPayment: mcs(
        "col-8c4YSaF",
        "paymentType",
        "Form of payment",
        false,
      ),
      amount: mcs("col-UzaXtjU", "number", "Amount", false),
      detailsVerified: mcs("col-YrD2LQj", "yesOrNo", "Details verified", false),
      amountAllocated: mcs("col-SZpwM52", "number", "Amount allocated", true),
      allocationCount: mcs("col-aip45rN", "number", "Allocation count", true),
      amountUnallocated: mcs(
        "col-3SmJeZz",
        "number",
        "Amount unallocated",
        true,
      ),
      processed: mcs("col-DoMfDwe", "yesOrNo", "Processed", true),
      notes: mcs("col-ZLNoGUf", "string", "Notes", false),
    },
    occupancy: {
      name: mcs("col-jHfWw_p", "string", "Name", true),
      id: mcs("col-aobYS7A", "string", "ID", true),
      householdId: mcs("col-cQbzV2A", "string", "Household ID", false),
      residentCount: mcs("col-yVuonvl", "number", "Resident count", true),
      unitId: mcs("col-OsokrlB", "string", "Unit ID", false),
      propertyId: mcs("col-d8mC6Rn", "string", "Property ID", true),
      unitStandardName: mcs(
        "col-I4yjYPD",
        "string",
        "Unit standard name",
        true,
      ),
      isActive: mcs("col-tuQZLj-", "string", "Is active", true),
      firstOccupancyTermsId: mcs(
        "col-mnW1daF",
        "string",
        "First occupancy terms ID",
        true,
      ),
      activeOccupancyTermsId: mcs(
        "col-s4Zxv4D",
        "string",
        "Active occupancy terms ID",
        true,
      ),
      latestOccupancyTermsId: mcs(
        "col-EZp4_52",
        "string",
        "Latest occupancy terms ID",
        true,
      ),
      latestEndedOccupancyTermsId: mcs(
        "col-SUlG0Wm",
        "string",
        "Latest ended occupancy terms ID",
        true,
      ),
      latestOccupancyTermsStartDate: mcs(
        "col-lwvPphy",
        "date",
        "Latest occupancy terms start date",
        true,
      ),
      firstOccupancyDate: mcs(
        "col-KRlbXkL",
        "date",
        "First occupancy date",
        true,
      ),
      latestOccupancyDate: mcs(
        "col-BWZ97DV",
        "date",
        "Latest occupancy date",
        true,
      ),
      subsidyCount: mcs("col-6GjBcbG", "number", "Subsidy count", true),
      buildLedgerLastRan: mcs(
        "col-0g1jOuv",
        "date",
        "Build ledger last ran",
        false,
      ),
      buildLedgerSelect: mcs(
        "col-0g1jY1d",
        "boolean",
        "Build ledger, select",
        false,
      ),
      buildLedgerRunAndStatus: mcs(
        "col-0g1jopp",
        "string",
        "Build ledger, run and status",
        false,
      ),
    },
    occupancyTerms: {
      residentAndUnitName: mcs(
        "col-yq4jyPb",
        "string",
        "Resident and unit name",
        true,
      ),
      id: mcs("col-dcm4U7V", "string", "ID", true),
      occupancyId: mcs("col-OXD-Ek9", "string", "Occupancy ID", false),
      noticeDate: mcs("col-0dJOCyD", "string", "Notice date", false),
      startDate: mcs("col-AtT0nqz", "date", "Start date", false),
      endDate: mcs("col-nhh7hS1", "date", "End date", false),
      rentChargeMonthly: mcs(
        "col-ivd-pWw",
        "number",
        "Rent charge monthly",
        false,
      ),
      caretakerRentReductionMonthly: mcs(
        "col-h0uS5oi",
        "number",
        "Caretaker rent reduction monthly",
        false,
      ),
      petFeeMonthly: mcs("col-NXjOs5W", "number", "Pet fee monthly", false),
      gasHeating: mcs("col-mdfuos3", "boolean", "Gas Heating", false),
      electricHeating: mcs("col-C2tyPDA", "boolean", "Electric Heating", false),
      gasCooking: mcs("col-y4Tjo7G", "boolean", "Gas Cooking", false),
      electricCooking: mcs("col-J5X2by5", "boolean", "Electric Cooking", false),
      otherElectric: mcs("col-3XZWzZb", "boolean", "Other Electric", false),
      gasWaterHeating: mcs(
        "col-5q18yvd",
        "boolean",
        "Gas Water Heating",
        false,
      ),
      electricWaterHeating: mcs(
        "col-hr2Ex2L",
        "boolean",
        "Electric Water Heating",
        false,
      ),
      waterSewer: mcs("col-TV-65-Y", "boolean", "Water & Sewer", false),
      trashCollection: mcs("col-ahrWo52", "boolean", "Trash Collection", false),
      districtEnergyHeating: mcs(
        "col-hgRDXpl",
        "boolean",
        "District Energy Heating",
        false,
      ),
      districtEnergyWaterHeating: mcs(
        "col-WnfDv0q",
        "boolean",
        "District Energy Water Heating",
        false,
      ),
      notes: mcs("col-9E6_E_l", "string", "Notes", false),
    },
    paymentGroup: {
      name: mcs("col-M2AcrkT", "string", "Name", false),
      id: mcs("col-8ZambHV", "string", "ID", true),
    },
    paymentStandard: {
      id: mcs("col-WSIA79A", "string", "ID", false),
      name: mcs("col-nXZJynE", "string", "Name", true),
      areaStandardName: mcs(
        "col-LLk1Rnw",
        "string",
        "Area standard name",
        true,
      ),
      unitStandardName: mcs(
        "col-_d26cZW",
        "string",
        "Unit standard name",
        true,
      ),
      type: mcs("col-UKMMk6d", "string", "Type", false),
      area: mcs("col-PdIqODe", "string", "Area", false),
      year: mcs("col-Vqa770-", "number", "Year", false),
      buildingType: mcs(
        "col-MciQOdX",
        "buildingTypeAndAny",
        "Building type",
        false,
      ),
      bedroomCount: mcs("col-ayrEE8U", "number", "Bedroom count", false),
      grossRent: mcs("col-2NN5vKf", "number", "Gross rent", false),
      gasHeating: mcs("col-D5Mq2iT", "number", "Gas Heating", false),
      electricHeating: mcs("col-Tk7-gts", "number", "Electric Heating", false),
      gasCooking: mcs("col-TQGm_hh", "number", "Gas Cooking", false),
      electricCooking: mcs("col-usiVwX-", "number", "Electric Cooking", false),
      gasWaterHeating: mcs("col--PXRLlq", "number", "Gas Water Heating", false),
      electricWaterHeating: mcs(
        "col-bijwMhk",
        "number",
        "Electric Water Heating",
        false,
      ),
      otherElectric: mcs("col-huaucO6", "number", "Other Electric", false),
      waterSewer: mcs("col-1GsKsEm", "number", "Water & Sewer", false),
      trashCollection: mcs("col-nAb9KBk", "number", "Trash Collection", false),
      districtEnergyHeating: mcs(
        "col-Z428AUE",
        "number",
        "District Energy Heating",
        false,
      ),
      districtEnergyWaterHeating: mcs(
        "col-3DuCyZ1",
        "number",
        "District Energy Water Heating",
        false,
      ),
      range: mcs("col-TlqPiw-", "number", "Range", false),
      refrigerator: mcs("col-kt86HvQ", "number", "Refrigerator", false),
    },
    pet: {
      id: mcs("col-UukcD_J", "string", "ID", true),
      name: mcs("col-YfYkSGo", "string", "Name", false),
      householdName: mcs("col-l9or2xk", "string", "Household name", true),
      householdId: mcs("col-0zkPeRN", "string", "Household ID", false),
      species: mcs("col-NyQH0lV", "string", "Species", false),
      breed: mcs("col-JT5K0b8", "string", "Breed", false),
      birthDateApproximate: mcs(
        "col-i_9-yIb",
        "date",
        "Birth date, approximate",
        false,
      ),
      age: mcs("col-XsopPha", "number", "Age", true),
      rentersInsuranceProofDate: mcs(
        "col--PB8t09",
        "date",
        "Renters insurance proof date",
        false,
      ),
      vaccinationProofDate: mcs(
        "col-WiA5qeP",
        "date",
        "Vaccination proof date",
        false,
      ),
      petFeeMonthly: mcs("col-uHS2k_j", "number", "Pet fee monthly", false),
    },
    property: {
      name: mcs("col-UKOooW1", "string", "Name", false),
      id: mcs("col-NYNaEua", "string", "ID", true),
      parcelNumber: mcs("col-dlhnglY", "number", "Parcel number", false),
      streetAddress: mcs("col-RxPUYIT", "string", "Street address", false),
      zipCode: mcs("col-mf-CiKH", "number", "Zip code", false),
      yearBuilt: mcs("col-iQ1mkhJ", "number", "Year built", false),
      squareFeet: mcs("col-ndjGDiW", "number", "Square feet", false),
      pavedDrivewayCount: mcs(
        "col-KaVpIiL",
        "number",
        "Paved driveway count",
        false,
      ),
      garageDoorCount: mcs("col-sppZ7na", "number", "Garage door count", false),
      unitLabelPrepend: mcs(
        "col-ij_IAXs",
        "string",
        "Unit label prepend",
        false,
      ),
      purchasePrice: mcs("col-C2GI_ft", "number", "Purchase price", false),
      closingDate: mcs("col-7a6orCO", "string", "Closing date", false),
      buildingType: mcs("col-pTuQDxB", "string", "Building type", true),
      unitCount: mcs("col-wsgC_ig", "number", "Unit count", true),
      bedroomCount: mcs("col-dw-dis5", "number", "Bedroom count", true),
      furnaceCount: mcs("col-9YOXfRA", "number", "Furnace count", true),
      projectedRoi: mcs("col-l6xMHBT", "string", "Projected ROI", false),
      upfrontInvestment: mcs(
        "col-2jKnRmE",
        "string",
        "Upfront investment",
        false,
      ),
      averagePrincipalMonthly: mcs(
        "col-Ww_GkTd",
        "string",
        "Average principal monthly",
        false,
      ),
      discretionaryIncomeAnnualAvg: mcs(
        "col-fnh7KJP",
        "number",
        "Discretionary income annual avg",
        true,
      ),
      discretionaryIncomeMonthlyAvg: mcs(
        "col-McnYr72",
        "number",
        "Discretionary income monthly avg",
        true,
      ),
      flexibleIncomeMonthlyAvg: mcs(
        "col-GIXXH26",
        "number",
        "Flexible income monthly avg",
        true,
      ),
      grossIncomeMonthly: mcs(
        "col-ajl0Vey",
        "number",
        "Gross income monthly",
        true,
      ),
      mortgagePaymentMonthly: mcs(
        "col-6P8iAZC",
        "number",
        "Mortgage payment monthly",
        false,
      ),
      principalPaymentMonthlyAvg: mcs(
        "col-Nzx4807",
        "number",
        "Principal payment monthly avg",
        true,
      ),
      mortgageBalanceOriginal: mcs(
        "col-dMZggrr",
        "number",
        "Mortgage balance original",
        false,
      ),
      mortgageHolder: mcs("col-oeUhWvv", "string", "Mortgage holder", false),
      ltv: mcs("col-EeeukQT", "number", "LTV %", true),
      pmi: mcs("col-QxQPjIT", "string", "PMI", false),
      mortgageBalance: mcs("col-KhZEP9D", "number", "Mortgage balance", false),
      mortgageNumber: mcs("col-UH9nd_C", "number", "Mortgage number", false),
      helocPaymentMonthly: mcs(
        "col-7pB1h02",
        "number",
        "Heloc payment monthly",
        true,
      ),
      helocPaymentOverride: mcs(
        "col-fa446XR",
        "string",
        "HELOC payment override",
        false,
      ),
      helocInterestPayment: mcs(
        "col-Cx25AZv",
        "number",
        "HELOC interest payment",
        true,
      ),
      helocSpent: mcs("col-Sh2sxCg", "number", "HELOC spent", false),
      helocLimit: mcs("col-DDIzEX3", "number", "HELOC limit", false),
      helocAvailable: mcs("col-_sRmpcG", "number", "HELOC available", true),
      helocHolder: mcs("col-lIgVCtz", "string", "HELOC holder", false),
      helocInterestRate: mcs(
        "col-1xOaDGm",
        "number",
        "HELOC interest rate",
        false,
      ),
      helocPaymentDay: mcs("col-7oATSzG", "number", "HELOC payment day", false),
      helocNumber: mcs("col-Jw8ApcW", "number", "HELOC number", false),
      helocStartDate: mcs("col-1gA69gI", "date", "HELOC start date", false),
      utilityPaymentMonthlyAvg: mcs(
        "col-fDZD238",
        "number",
        "Utility payment monthly avg",
        true,
      ),
      energyPaymentMonthlyAvg: mcs(
        "col-kh-75Dj",
        "number",
        "Energy payment monthly avg",
        false,
      ),
      waterPaymentMonthlyAvg: mcs(
        "col-pxPZeyT",
        "number",
        "Water payment monthly avg",
        true,
      ),
      waterBillQuarterlyAvg: mcs(
        "col-2r-MvrC",
        "number",
        "Water bill quarterly avg",
        false,
      ),
      waterAccount: mcs("col-zGB5wLk", "string", "Water account", false),
      waterPaymentDayOfMonthEarly: mcs(
        "col-qDmMkZJ",
        "number",
        "Water payment day of month early",
        false,
      ),
      waterPaymentDayOfMonthLate: mcs(
        "col-8jXuvG-",
        "number",
        "Water payment day of month late",
        false,
      ),
      waterPaymentFirstQuarter: mcs(
        "col-o1x-wv4",
        "string",
        "Water payment first quarter",
        false,
      ),
      garbagePaymentMonthlyAvg: mcs(
        "col-n_D8298",
        "number",
        "Garbage payment monthly avg",
        true,
      ),
      garbageBillQuarterly: mcs(
        "col-jvoXCCB",
        "number",
        "Garbage bill quarterly",
        false,
      ),
      garbageBins: mcs("col-8bq2kF6", "string", "Garbage bins", false),
      budgetsMonthly: mcs("col-m1WV4qs", "number", "Budgets monthly", true),
      maintenanceBudgetMonthly: mcs(
        "col-ZH_jQsz",
        "number",
        "Maintenance budget monthly",
        true,
      ),
      vacancyBudgetMonthly: mcs(
        "col-g9Wb4sq",
        "number",
        "Vacancy budget monthly",
        true,
      ),
      groundskeepingBudgetMonthly: mcs(
        "col-Dy2oTtx",
        "number",
        "Groundskeeping budget monthly",
        false,
      ),
      capexBudgetMonthly: mcs(
        "col-U2UTMN3",
        "number",
        "Capex budget monthly",
        true,
      ),
      perProperty: mcs("col-ejzcxIv", "number", "Per property", true),
      windowCountEstimate: mcs(
        "col-Qqr81ps",
        "number",
        "Window count estimate",
        true,
      ),
      roof: mcs("col-dmwUWVp", "number", "Roof", true),
      siding: mcs("col-meHYx80", "number", "Siding", true),
      furnace: mcs("col-RmN-bYV", "number", "Furnace", true),
      waterHeater: mcs("col-iUTHiqG", "number", "Water heater", true),
      flooring: mcs("col-jN28F8U", "number", "Flooring", true),
      gutters: mcs("col-zXJ8dhr", "number", "Gutters", true),
      interiorPaint: mcs("col-RvWphY1", "number", "Interior paint", true),
      refrigerator: mcs("col-JPhrE1-", "number", "Refrigerator", true),
      range: mcs("col-mqLl6c1", "number", "Range", true),
      clothesWasher: mcs("col-V5JLenJ", "number", "Clothes washer", true),
      clothesDryer: mcs("col-YjDwWCa", "number", "Clothes dryer", true),
      dishwasher: mcs("col-WJIYxcR", "number", "Dishwasher", true),
      windows: mcs("col-XI0diwj", "number", "Windows", true),
      cabinets: mcs("col-mHi63ZH", "number", "Cabinets", true),
      countertops: mcs("col-BIpQMby", "number", "Countertops", true),
      landscaping: mcs("col-h_ax2o8", "number", "Landscaping", true),
      driveway: mcs("col-55h3otY", "number", "Driveway", true),
      garageDoor: mcs("col-Ndh1QvP", "number", "Garage door", true),
      insuranceProvider: mcs(
        "col-l8xxJGI",
        "string",
        "Insurance provider",
        false,
      ),
      insurancePolicyNumber: mcs(
        "col-F5FD5Fu",
        "string",
        "Insurance policy number",
        false,
      ),
      insuranceRenewalDate: mcs(
        "col-LQlJfeM",
        "date",
        "Insurance renewal date",
        false,
      ),
      insuranceDeductible: mcs(
        "col-TEv3fQS",
        "number",
        "Insurance deductible",
        false,
      ),
      insurancePremiumYearly: mcs(
        "col-4dwzFhA",
        "number",
        "Insurance premium yearly",
        false,
      ),
      insurancePremiumMonthly: mcs(
        "col-f1sJZjS",
        "number",
        "Insurance premium monthly",
        true,
      ),
      insuranceNotes: mcs("col-fmolBdG", "string", "Insurance notes", false),
      outdoorWaterSource: mcs(
        "col-aBMOpUk",
        "string",
        "Outdoor water source",
        false,
      ),
      gardenBedSqFt: mcs("col-xgNmSP2", "number", "Garden bed sq ft", false),
      gardenYardSqFt: mcs("col-lLGiPJ-", "number", "Garden yard sq ft", true),
      boulevardSqFt: mcs("col-xPhh3bL", "number", "Boulevard sq ft", true),
      kidsPlayBackYardSqFt: mcs(
        "col-HmSzSso",
        "number",
        "Kids play back yard sq ft",
        false,
      ),
      lawnMowSqft: mcs("col-tGD0Atd", "string", "Lawn mow sqft", false),
      totalYardSqft: mcs("col-AWQC6wR", "string", "Total yard sqft", false),
    },
    propertyExpense: {
      expenseName: mcs("col-w_PiWJi", "string", "Expense name", true),
      id: mcs("col-Qj2-mYp", "string", "ID", true),
      propertyId: mcs("col-1hpEB5R", "string", "Property ID", false),
      date: mcs("col-eg74PeC", "date", "Date", false),
      year: mcs("col-4DAHsCd", "number", "Year", true),
      propertyYearId: mcs("col-WchviCc", "string", "Property year ID", true),
      unitId: mcs("col-rH-ATRE", "string", "Unit ID", false),
      billerName: mcs("col-icHn2T8", "string", "Biller name", false),
      description: mcs("col-g1WqJPr", "string", "Description", false),
      expenseCategory: mcs(
        "col-HVmhEMV",
        "expenseCategory",
        "Expense category",
        false,
      ),
      receiptFormat: mcs(
        "col-qpJqo2x",
        "receiptFormat",
        "Receipt format",
        false,
      ),
      amount: mcs("col-Tum3aH7", "number", "Amount", false),
      deductibleAmount: mcs("col-55XKM_i", "number", "Deductible amount", true),
      taxAdjust: mcs("col-V2BAd2p", "residenceTaxAdjust", "Tax adjust", false),
      isUpfrontInvestment: mcs(
        "col-bK8A6h_",
        "yesOrNo",
        "Is upfront investment",
        false,
      ),
      notes: mcs("col-tf50IlU", "string", "Notes", false),
    },
    propertyProspect: {
      name: mcs("col-S0OAuTp", "string", "Name", false),
      id: mcs("col-OkqJWNn", "string", "ID", true),
      parcelNumberPropertyId: mcs(
        "col-0lIe4Xa",
        "string",
        "Parcel Number/\nProperty ID",
        false,
      ),
      streetAddress: mcs("col-jiFMS_y", "string", "Street address", false),
      zipCode: mcs("col-1y1a6Ff", "string", "Zip code", false),
      purchaseDate: mcs("col-CW9RU72", "string", "Purchase date", false),
      status: mcs("col-8d9-nfv", "string", "Status", false),
      notes: mcs("col-RoBy_Ut", "string", "Notes", false),
      questions: mcs("col-9qe82lZ", "string", "Questions", false),
      yearBuilt: mcs("col-lKMwqMV", "string", "Year built", false),
      squareFeet: mcs("col-DqT0mwa", "string", "Square feet", false),
      unitCount: mcs("col-Ag6_m69", "string", "Unit count", false),
      furnaceCount: mcs("col-rO5CGy0", "string", "Furnace count", false),
      bedroomCount: mcs("col-se5gANl", "string", "Bedroom count", false),
      pavedDrivewayCount: mcs(
        "col-jVdARRy",
        "string",
        "Paved driveway count",
        false,
      ),
      garageDoorCount: mcs("col-yYgBB3-", "string", "Garage door count", false),
      purchasePrice: mcs("col-FpFVeeU", "string", "Purchase price", false),
      comission: mcs("col-QZfm4Rg", "string", "Comission", false),
      downPayment: mcs("col-E6lZNsV", "number", "Down payment", true),
      startingRentalIncome: mcs(
        "col-IkgdHr9",
        "string",
        "Starting rental income",
        false,
      ),
      rentalIncome: mcs("col-W0Q3tXm", "string", "Rental income", false),
      upfrontRepairCosts: mcs(
        "col-6cQlFxE",
        "string",
        "Upfront repair costs",
        false,
      ),
      nonUpfrontRepairCostsCapex: mcs(
        "col-MwxRVjG",
        "string",
        "Non-upfront repair costs (CapEx)",
        false,
      ),
      taxesAnnual: mcs("col-gCG2Qie", "string", "Taxes annual", false),
      taxesMonthly: mcs("col-VL874yL", "number", "Taxes monthly", true),
      lawncareBudgetMonthly: mcs(
        "col-W1p8b1b",
        "number",
        "Lawncare budget monthly",
        true,
      ),
      insuranceMonthlyEstimate: mcs(
        "col-XcPapnZ",
        "number",
        "Insurance monthly estimate",
        true,
      ),
      insuranceAnnualEstimate: mcs(
        "col-ZvJvQRO",
        "number",
        "Insurance annual estimate",
        true,
      ),
      utilityTotalMonthly: mcs(
        "col-e8TG1zH",
        "number",
        "Utility total monthly",
        true,
      ),
      waterMonthly: mcs("col-ybMqgFN", "number", "Water monthly", true),
      waterQuarterly: mcs("col-B3xgDQf", "string", "Water quarterly", false),
      garbageMonthly: mcs("col-tbRXTof", "number", "Garbage monthly", true),
      garbageQuarterly: mcs("col-P29jxIM", "number", "Garbage quarterly", true),
      capexTotalMonthly: mcs(
        "col-BTE_UBh",
        "number",
        "CapEx total monthly",
        true,
      ),
      perProperty: mcs("col-0E8iAux", "number", "Per property", true),
      windowCountEstimate: mcs(
        "col-NnjG4Rt",
        "number",
        "Window count estimate",
        true,
      ),
      roof: mcs("col-yT_a5B3", "number", "Roof", true),
      siding: mcs("col-5gg-upp", "number", "Siding", true),
      furnace: mcs("col-ioVtdjD", "number", "Furnace", true),
      waterHeater: mcs("col-izjCpVm", "number", "Water heater", true),
      flooring: mcs("col-JTSdHJz", "number", "Flooring", true),
      gutters: mcs("col-WESKtQv", "number", "Gutters", true),
      interiorPaint: mcs("col-iTcbFAe", "number", "Interior paint", true),
      refrigerator: mcs("col-Cmdyap_", "number", "Refrigerator", true),
      range: mcs("col-9YxhUFQ", "number", "Range", true),
      clothesWasher: mcs("col-wVSe7xy", "number", "Clothes washer", true),
      clothesDryer: mcs("col-QJ-YTkC", "number", "Clothes dryer", true),
      dishwasher: mcs("col-hY1lYJN", "number", "Dishwasher", true),
      windows: mcs("col-OQREydX", "number", "Windows", true),
      cabinets: mcs("col-IppyLV4", "number", "Cabinets", true),
      countertops: mcs("col-ICqtSww", "number", "Countertops", true),
      landscaping: mcs("col-vqT2zOu", "number", "Landscaping", true),
      driveway: mcs("col-PLW0MYK", "number", "Driveway", true),
      garageDoor: mcs("col-ZKkZ7-V", "number", "Garage door", true),
      vacancyBudgetMonthly: mcs(
        "col-ljxz0gR",
        "number",
        "Vacancy budget monthly",
        true,
      ),
      maintenanceBudgetMonthly: mcs(
        "col-i2fS7QU",
        "number",
        "Maintenance budget monthly",
        true,
      ),
      loanAmountBase: mcs("col-nwkgCz7", "number", "Loan amount base", true),
      ltvRatio: mcs("col-IYtSZG9", "string", "LTV ratio", true),
      interestRateYearly: mcs(
        "col-BB4uKDl",
        "number",
        "Interest rate yearly",
        true,
      ),
      interestRateMonthly: mcs(
        "col-Vw_TTgT",
        "number",
        "Interest rate monthly",
        true,
      ),
      loanTermYears: mcs("col-HOqeQW_", "number", "Loan term years", true),
      loanTermMonths: mcs("col-Db1veZf", "number", "Loan term months", true),
      closingCosts: mcs("col-MF8af4Z", "number", "Closing costs", true),
      sellerPaidClosingCosts: mcs(
        "col-XDKvGiw",
        "string",
        "Seller-paid closing costs",
        false,
      ),
      prepaidsAtClosing: mcs(
        "col-JHBkv_7",
        "string",
        "Prepaids at closing",
        false,
      ),
      principalAndInterestMonthly: mcs(
        "col-sxLq4Fz",
        "number",
        "Principal and interest monthly",
        true,
      ),
      pmiMonthly: mcs("col-5xHnDsz", "number", "PMI monthly", true),
      pmiAnnual: mcs("col-i50sS9U", "number", "PMI annual", true),
      pmiRate: mcs("col-geWSWWp", "string", "PMI rate", false),
      mortgagePaymentEstimatePiti: mcs(
        "col-ORerHse",
        "number",
        "Mortgage payment estimate (PITI)",
        true,
      ),
      grossIncomeMonthly: mcs(
        "col-Yt4wh4q",
        "string",
        "Gross income monthly",
        false,
      ),
      upfrontCosts: mcs("col-Af68cx4", "number", "Upfront costs", true),
      upfrontCash: mcs("col-SFb8uBJ", "string", "Upfront cash", false),
      propertyExpensesMonthly: mcs(
        "col-xvpvOfm",
        "number",
        "Property expenses monthly",
        true,
      ),
      financingExpensesMonthly: mcs(
        "col-X5gIiB8",
        "number",
        "Financing expenses monthly",
        true,
      ),
      totalExpensesMonthly: mcs(
        "col-6yEJQ__",
        "number",
        "Total expenses monthly",
        true,
      ),
      cashFlowMonthly: mcs("col-O8benrs", "number", "Cash flow monthly", true),
      cashFlowAnnual: mcs("col-JNeUlZP", "number", "Cash flow annual", true),
      roi: mcs("col-2JBw-J8", "number", "ROI", true),
      column96: mcs("col--9HLvkP", "string", "Column 96", false),
      insurancePremiumYearly: mcs(
        "col-CjODhuL",
        "string",
        "Insurance premium yearly",
        false,
      ),
      insurancePremiumMonthly: mcs(
        "col-B-TtJXJ",
        "number",
        "Insurance premium monthly",
        true,
      ),
      insuranceProvider: mcs(
        "col-W3x5YSr",
        "string",
        "Insurance provider",
        false,
      ),
      insurancePolicyNumber: mcs(
        "col-VqbqKMH",
        "string",
        "Insurance policy number",
        false,
      ),
      insuranceRenewalDate: mcs(
        "col-C62joYg",
        "string",
        "Insurance renewal date",
        false,
      ),
      insuranceDeductible: mcs(
        "col-gO6IMv8",
        "string",
        "Insurance deductible",
        false,
      ),
      insuranceNotes: mcs("col-6atkGeu", "string", "Insurance notes", false),
      utilityMonthlyTotal: mcs(
        "col-51JutEB",
        "number",
        "Utility monthly total",
        true,
      ),
      waterPaymentMonthly: mcs(
        "col-8yIBK-J",
        "number",
        "Water payment monthly",
        true,
      ),
      garbagePaymentMonthly: mcs(
        "col-pOB7Uhb",
        "number",
        "Garbage payment monthly",
        true,
      ),
      energyPaymentMonthly: mcs(
        "col-Wq9kMAe",
        "string",
        "Energy payment monthly",
        false,
      ),
      waterAccountUnverified: mcs(
        "col-hH3A_7Z",
        "string",
        "Water account (unverified)",
        false,
      ),
      avgWaterBillQuarterly: mcs(
        "col-YbK6nes",
        "string",
        "Avg water bill quarterly",
        false,
      ),
      nextWaterPaymentDate: mcs(
        "col-SFdq1KP",
        "date",
        "Next water payment date",
        true,
      ),
      waterPaymentDate: mcs(
        "col-mK1W-mH",
        "string",
        "Water payment date",
        false,
      ),
      avgGarbageBillQuarterly: mcs(
        "col-2Be_ZlX",
        "string",
        "Avg garbage bill quarterly",
        false,
      ),
      nextGarbagePaymentDate: mcs(
        "col-6sO5HEW",
        "string",
        "Next garbage payment date",
        false,
      ),
      garbagePaymentDate: mcs(
        "col-gi63OtF",
        "string",
        "Garbage payment date",
        false,
      ),
      column97: mcs("col-ptM7Jj7", "string", "Column 97", false),
      column1: mcs("col-Egb6CCR", "string", "Column 1", false),
      mortgagePaymentMonthly: mcs(
        "col-p9lga5D",
        "string",
        "Mortgage payment monthly",
        false,
      ),
      mortgageHolder: mcs("col-tvtnSGs", "string", "Mortgage holder", false),
      mortgageNumber: mcs("col-f0TEYw-", "string", "Mortgage number", false),
      mortgageBalance: mcs("col-XSvoDWo", "string", "Mortgage balance", false),
      ltv: mcs("col-7HKVmK_", "string", "LTV %", true),
      pmi: mcs("col-nto9Ao2", "string", "PMI", false),
      helocAvailable: mcs("col-P2LYFfH", "number", "HELOC available", true),
      helocPaymentMonthly: mcs(
        "col--vU01TX",
        "string",
        "HELOC payment monthly",
        false,
      ),
      helocHolder: mcs("col--wsHtE_", "string", "HELOC holder", false),
      helocNumber: mcs("col-RBLV5s_", "string", "HELOC number", false),
      helocStartDate: mcs("col-0dnlzzL", "string", "HELOC start date", false),
      helocLimit: mcs("col-PhrD5vU", "string", "HELOC limit", false),
      helocBalance: mcs("col-mNIXW1Y", "string", "HELOC balance", false),
      helocInterestRate: mcs(
        "col-XWTq4RX",
        "string",
        "HELOC interest rate",
        false,
      ),
    },
    propertyYear: {
      name: mcs("col--GXBgqg", "string", "Name", true),
      id: mcs("col-pLbR676", "string", "ID", true),
      propertyId: mcs("col-MqF-anY", "string", "Property ID", false),
      year: mcs("col-TawhTyt", "number", "Year", false),
      primarySpace: mcs("col-alQOQuj", "number", "Primary space", false),
      notPrimarySpace: mcs("col-QkHxyMW", "number", "Not primary space", true),
      primaryTimeOwned: mcs(
        "col-iSuANXq",
        "number",
        "Primary time owned",
        false,
      ),
      notPrimaryTimeOwned: mcs(
        "col-kj62b6N",
        "number",
        "Not primary time owned",
        true,
      ),
      total: mcs("col-w0edV92", "number", "Total", true),
      incomeFromHouseholds: mcs(
        "col-iD9skHh",
        "number",
        "Income from households",
        true,
      ),
      incomeFromSubsidies: mcs(
        "col-7X1LeUo",
        "number",
        "Income from subsidies",
        true,
      ),
      incomeFromOtherSources: mcs(
        "col-QseAaB5",
        "number",
        "Income from other sources",
        true,
      ),
      "1099Misc": mcs("col-dcCSLJn", "string", "1099-Misc", false),
      incomeExptected: mcs("col-8LhB3qW", "string", "Income exptected", false),
      incomeExpectedMaximum: mcs(
        "col-M08K-ca",
        "string",
        "Income expected maximum",
        false,
      ),
      budgetsCostEstimates: mcs(
        "col-qhjoI7t",
        "string",
        "Budgets & cost estimates",
        false,
      ),
      maintenanceBudget: mcs(
        "col-4r-P97r",
        "string",
        "Maintenance budget",
        false,
      ),
      vacancyBudget: mcs("col-vBhf-u-", "string", "Vacancy budget", false),
      lawncareBudget: mcs("col-PT5uv-S", "string", "Lawncare budget", false),
      capexBudget: mcs("col-p54csmV", "string", "CapEx budget", false),
      utilityCostEstimate: mcs(
        "col-xy2UuPt",
        "string",
        "Utility cost estimate",
        false,
      ),
      actualCosts: mcs("col-nIf7Xtx", "number", "Actual costs", true),
      maintenanceGroundskeepingCosts: mcs(
        "col-hYWXrQz",
        "number",
        "Maintenance & groundskeeping costs",
        true,
      ),
      utilityCosts: mcs("col-0KWDOnD", "number", "Utility costs", true),
      capexCosts: mcs("col-exdmXLl", "number", "CapEx costs", true),
      vacancyCosts: mcs("col-J7djr8C", "string", "Vacancy costs", false),
      taxableTotal: mcs("col-Bzs_uJu", "number", "Taxable total", true),
      absoluteTotal: mcs("col-PGC9pdA", "number", "Absolute total", true),
      cleaningMaintenance: mcs(
        "col-RmgQG7B",
        "number",
        "Cleaning & maintenance",
        true,
      ),
      insurance: mcs("col-lUNFd66", "number", "Insurance", true),
      mortgageInterestPaidToBanks: mcs(
        "col-J2F1NxS",
        "number",
        "Mortgage interest paid to banks",
        true,
      ),
      repair: mcs("col-AiWPNkl", "number", "Repair", true),
      supplies: mcs("col-4OAhSq1", "number", "Supplies", true),
      taxes: mcs("col-2pLgeyL", "number", "Taxes", true),
      utilities: mcs("col-uU2oYki", "number", "Utilities", true),
      depreciationExpenseOrDepletion: mcs(
        "col-Y9hnxem",
        "number",
        "Depreciation expense or depletion",
        true,
      ),
      legalProfessional: mcs(
        "col-D6zQXl4",
        "number",
        "Legal & professional",
        true,
      ),
      advertising: mcs("col-aHKMePu", "number", "Advertising", true),
      autoAndTravel: mcs("col-dx-FCXy", "number", "Auto and travel", true),
      mgmtFees: mcs("col-hmM-lMs", "number", "Mgmt fees", true),
      commissions: mcs("col-4J2Mxv9", "number", "Commissions", true),
      otherInterest: mcs("col-JbhS4Y6", "number", "Other interest", true),
      other: mcs("col-okSrW_E", "number", "Other", true),
      principal: mcs("col-i_x5Gzf", "number", "Principal", true),
    },
    quotes: {
      date: mcs("col-WGt6dPd", "date", "Date", false),
      id: mcs("col-h3wgJ39", "string", "ID", true),
      prospectiveBillerName: mcs(
        "col-QlJe96V",
        "string",
        "Prospective biller name",
        false,
      ),
      billerName: mcs("col-ly-BMJ_", "string", "Biller name", false),
      billerCategory: mcs("col-3hlIrmQ", "string", "Biller category", true),
      service: mcs("col-4swJjZZ", "string", "Service", false),
      amount: mcs("col-7xyQYhm", "number", "Amount", false),
      preferredForService: mcs(
        "col-Fwju2h2",
        "string",
        "Preferred for service",
        false,
      ),
      notes: mcs("col-qyRbDVX", "string", "Notes", false),
    },
    recurringTransaction: {
      id: mcs("col-gP8cSSs", "string", "ID", false),
      item: mcs("col-T5ui0fF", "string", "Item", false),
      transactionType: mcs("col-ViD8IQV", "string", "Transaction type", false),
      transactWith: mcs("col-1lm7yg5", "string", "Transact with", false),
      propertyId: mcs("col-0Hg4hkA", "string", "Property ID", false),
      transactionDayOfMonth: mcs(
        "col-Rk2rqXQ",
        "number",
        "Transaction day of month",
        false,
      ),
      monthsBetweenTransactions: mcs(
        "col-x7aeIs_",
        "number",
        "Months between transactions",
        false,
      ),
      nextTransactionDateEarly: mcs(
        "col-Qq_cpwI",
        "date",
        "Next transaction date early",
        true,
      ),
      nextTransactionAmount: mcs(
        "col-CCXBkki",
        "number",
        "Next transaction amount",
        true,
      ),
      averageMonthlyTransactionAmount: mcs(
        "col-sOSxVtN",
        "string",
        "Average monthly transaction amount",
        false,
      ),
      notes: mcs("col-NRvXapU", "string", "Notes", false),
    },
    rentComp: {
      id: mcs("col-pDoUFPj", "string", "ID", false),
      rentCompType: mcs("col-WPrzo7n", "string", "Rent comp type", true),
      paymentStandardName: mcs(
        "col-Dwm_BvW",
        "string",
        "Payment standard name",
        true,
      ),
      name: mcs("col-sk5BTbD", "string", "Name", false),
      date: mcs("col-PR3fL6v", "date", "Date", false),
      paymentStandardYear: mcs(
        "col-zAF93A0",
        "number",
        "Payment standard year",
        false,
      ),
      buildingType: mcs("col-kwd1nJf", "buildingType", "Building type", false),
      bedroomCount: mcs("col-zUPaL7J", "number", "Bedroom count", false),
      zipCode: mcs("col-SCKjbMh", "number", "Zip code", false),
      baseRentChargeMonthly: mcs(
        "col--KXLs3h",
        "number",
        "Base rent charge monthly",
        false,
      ),
      paymentStandardGrossRent: mcs(
        "col-XPaiJuh",
        "string",
        "Payment standard gross rent",
        true,
      ),
      paymentStandardUtilities: mcs(
        "col-uHlQTjQ",
        "string",
        "Payment standard utilities",
        true,
      ),
      gasHeating: mcs("col-v6ruJbN", "boolean", "Gas Heating", false),
      electricHeating: mcs("col-1tFVepW", "boolean", "Electric Heating", false),
      gasCooking: mcs("col-yXPEotT", "boolean", "Gas Cooking", false),
      electricCooking: mcs("col-lEpzVR-", "boolean", "Electric Cooking", false),
      gasWaterHeating: mcs(
        "col-fRt2Yns",
        "boolean",
        "Gas Water Heating",
        false,
      ),
      electricWaterHeating: mcs(
        "col-6CK9SPa",
        "boolean",
        "Electric Water Heating",
        false,
      ),
      otherElectric: mcs("col-kDXrKLj", "boolean", "Other Electric", false),
      waterSewer: mcs("col-d1u_yOr", "boolean", "Water & Sewer", false),
      trashCollection: mcs("col-xXD5Eot", "boolean", "Trash Collection", false),
      districtEnergyHeating: mcs(
        "col-qyoPjKZ",
        "boolean",
        "District Energy Heating",
        false,
      ),
      districtEnergyWaterHeating: mcs(
        "col-5aWwQIZ",
        "boolean",
        "District Energy Water Heating",
        false,
      ),
    },
    resident: {
      fullName: mcs("col-JQF8pac", "string", "Full name", true),
      id: mcs("col-8zXeQEw", "string", "ID", true),
      householdId: mcs("col-MMj5Qgq", "string", "Household ID", false),
      isActive: mcs("col-7LZcJ2t", "string", "Is active", true),
      firstName: mcs("col-ad6YZal", "string", "First name", false),
      lastName: mcs("col-cU-EQJv", "string", "Last name", false),
      middleInitial: mcs("col-w73gARY", "string", "Middle Initial", false),
      nameRank: mcs("col-XTeBHw2", "number", "Name rank", false),
      ssn: mcs("col-KDa6EVM", "string", "SSN", false),
      dob: mcs("col-NmeH8b0", "string", "DOB", false),
      phoneNumber: mcs("col-WDpsFk0", "string", "Phone Number", false),
      emailAddress: mcs("col-Q_gueC7", "string", "Email Address", false),
      income: mcs("col-TX8xQd6", "string", "Income", false),
      disability: mcs("col-Tkuv1y3", "string", "Disability", false),
      couldPay: mcs("col-FNPG_yQ", "string", "Could Pay?", false),
    },
    subPayAllocation: {
      name: mcs("col-uzEH5HL", "string", "Name", true),
      id: mcs("col-PJ1qm7P", "string", "ID", true),
      paymentId: mcs("col-jAnSZoZ", "string", "Payment ID", false),
      paymentDate: mcs("col-ek62dJt", "date", "Payment date", true),
      formOfPayment: mcs("col-3jQA3el", "string", "Form of payment", true),
      paymentAllocated: mcs("col-ci9Olfh", "number", "Payment allocated", true),
      chargeId: mcs("col-dWzWhmG", "string", "Charge ID", false),
      chargeDescription: mcs(
        "col-20hJLMV",
        "string",
        "Charge description",
        true,
      ),
      subsidyAgreementId: mcs(
        "col-xymKv30",
        "string",
        "Subsidy agreement ID",
        true,
      ),
      occupancyId: mcs("col--Kn3Eaj", "string", "Occupancy ID", true),
      propertyId: mcs("col-GnmfHIq", "string", "Property ID", true),
      paymentUnallocated: mcs(
        "col-zZm04Vj",
        "number",
        "Payment unallocated",
        true,
      ),
      chargeUnpaid: mcs("col-AdryODU", "number", "Charge unpaid", true),
      amount: mcs("col-uPlGvHp", "number", "Amount", true),
      allocateFullAmount: mcs(
        "col-dGJNUqv",
        "boolean",
        "Allocate full amount",
        false,
      ),
      lesserAmount: mcs("col-BZ8hOws", "string", "Lesser amount", false),
      filledOut: mcs("col-Goy1X8c", "string", "Filled out", true),
      processed: mcs("col-pZ746C-", "yesOrNo", "Processed", true),
    },
    subsidyAgreement: {
      name: mcs("col-2LNDs6x", "string", "Name", true),
      id: mcs("col-otFGzR9", "string", "ID", true),
      occupancyId: mcs("col-29TQHcp", "string", "Occupancy ID", false),
      subsidyProgramId: mcs(
        "col-0WyuPph",
        "string",
        "Subsidy program ID",
        false,
      ),
      paymentGroupId: mcs("col-hltQiWS", "string", "Payment group ID", false),
      paymentGroupName: mcs(
        "col-CNLvSX-",
        "string",
        "Payment group name",
        true,
      ),
      agreementStandardName: mcs(
        "col-Sh_eL0o",
        "string",
        "Agreement standard name",
        true,
      ),
      programStandardName: mcs(
        "col-9Aw3w41",
        "string",
        "Program standard name",
        true,
      ),
      unitStandardName: mcs(
        "col-SAZOgc0",
        "string",
        "Unit standard name",
        true,
      ),
      annualRenewalMonth: mcs(
        "col-9VVjyo4",
        "string",
        "Annual renewal month",
        false,
      ),
      annualInspectionMonth: mcs(
        "col-Xb7V4lu",
        "string",
        "Annual inspection month",
        false,
      ),
      subsidyContractStartDate: mcs(
        "col-h4okp5i",
        "date",
        "Subsidy contract start date",
        true,
      ),
      rentPortionMonthly: mcs(
        "col-KL3PAT5",
        "number",
        "Rent portion monthly",
        true,
      ),
      nextSubsidyContractStartDate: mcs(
        "col-RakSpZz",
        "string",
        "Next subsidy contract start date",
        false,
      ),
      nextRentPortionMonthly: mcs(
        "col-NktpEAf",
        "string",
        "Next rent portion monthly",
        false,
      ),
      updateSubsidyContractEnter: mcs(
        "col-pZ_-OR1",
        "boolean",
        "Update subsidy contract enter",
        false,
      ),
      subsidyWorkerId: mcs("col-0Ep6gXa", "string", "Subsidy worker ID", false),
      subsidyWorkerFirstName: mcs(
        "col-B0Dj4Od",
        "string",
        "Subsidy worker first name",
        true,
      ),
      subsidyWorkerEmail: mcs(
        "col-sOKTA2U",
        "string",
        "Subsidy worker email",
        true,
      ),
      totalCharges: mcs("col-YAdsPFN", "number", "Total charges", true),
      totalPayments: mcs("col-BPXV2hW", "number", "Total payments", true),
      balance: mcs("col-w8vLkK8", "number", "Balance", true),
    },
    subsidyCharge: {
      name: mcs("col-sUaYozJ", "string", "Name", true),
      id: mcs("col--nTU65W", "string", "ID", true),
      subsidyAgreementId: mcs(
        "col-MONO5y5",
        "string",
        "Subsidy agreement ID",
        false,
      ),
      date: mcs("col-siQYN_v", "date", "Date", false),
      description: mcs(
        "col-eki29GV",
        "chargeDescription",
        "Description",
        false,
      ),
      amount: mcs("col-D_ZLCZz", "number", "Amount", false),
      amountPaid: mcs("col-RNSqWma", "number", "Amount paid", true),
      amountUnpaid: mcs("col-899hXuQ", "number", "Amount unpaid", true),
    },
    subsidyPayment: {
      date: mcs("col-_YBhAu5", "date", "Date", false),
      id: mcs("col-PTux14k", "string", "ID", true),
      allocationName: mcs("col-f083hYz", "string", "Allocation name", true),
      subsidyProgramId: mcs(
        "col-3wCKfdm",
        "string",
        "Subsidy program ID",
        false,
      ),
      numAllocated: mcs("col-Bc6Z9wd", "number", "Num allocated", true),
      formOfPayment: mcs(
        "col-dkz_xwK",
        "paymentType",
        "Form of payment",
        false,
      ),
      amount: mcs("col-AcmAj-n", "number", "Amount", false),
      detailsVerified: mcs("col-V9Ue8yu", "yesOrNo", "Details verified", false),
      amountAllocated: mcs("col-OHWAx0k", "number", "Amount allocated", true),
      amountUnallocated: mcs(
        "col-4kyYlK4",
        "number",
        "Amount unallocated",
        true,
      ),
      processed: mcs("col-s-HNMVx", "yesOrNo", "Processed", true),
    },
    subsidyProgram: {
      name: mcs("col-o4QSWBF", "string", "Name", true),
      id: mcs("col-SP4bmlN", "string", "ID", true),
      nonResidentPayerId: mcs(
        "col-_17JhlQ",
        "string",
        "Non-resident payer ID",
        false,
      ),
      nonResidentPayerName: mcs(
        "col-p2sw2KM",
        "string",
        "Non-resident payer name",
        true,
      ),
      programStandardName: mcs(
        "col-J26TwQD",
        "string",
        "Program standard name",
        true,
      ),
      paymentStandardType: mcs(
        "col-2DJ5qZa",
        "string",
        "Payment standard type",
        false,
      ),
      paymentStandardArea: mcs(
        "col-Wk4Fb9d",
        "string",
        "Payment standard area",
        false,
      ),
    },
    subsidyTerms: {
      name: mcs("col-YqGL5a7", "string", "Name", true),
      id: mcs("col-8MJW0am", "string", "ID", true),
      subsidyAgreementId: mcs(
        "col-NGDD5AZ",
        "string",
        "Subsidy agreement ID",
        false,
      ),
      occupancyId: mcs("col-d7tvBlB", "string", "Occupancy ID", true),
      subsidyProgramId: mcs(
        "col-h9ut47r",
        "string",
        "Subsidy program ID",
        true,
      ),
      occupancyTermsId: mcs(
        "col-EiyA0BM",
        "string",
        "Occupancy terms ID",
        true,
      ),
      rentChargeMonthly: mcs(
        "col-kSFbjAd",
        "number",
        "Rent charge monthly",
        false,
      ),
      startDate: mcs("col-N98wM8U", "date", "Start date", false),
      endDate: mcs("col-WAdoKW-", "string", "End date", false),
      grossRent: mcs("col-ubljNHa", "string", "Gross rent", false),
      grossUtilities: mcs("col-Ysocizr", "string", "Gross utilities", true),
      paymentStandardName: mcs(
        "col-YS5igdB",
        "string",
        "Payment standard name",
        true,
      ),
      gasHeating: mcs("col-3Cxid3J", "boolean", "Gas Heating", true),
      electricHeating: mcs("col-2jWsE7c", "boolean", "Electric Heating", true),
      gasCooking: mcs("col-RNh1HKZ", "boolean", "Gas Cooking", true),
      electricCooking: mcs("col-Qz2zH70", "boolean", "Electric Cooking", true),
      otherElectric: mcs("col-rc7bLdS", "boolean", "Other Electric", true),
      gasWaterHeating: mcs("col-zVC9R-p", "boolean", "Gas Water Heating", true),
      electricWaterHeating: mcs(
        "col-jxHTX7M",
        "boolean",
        "Electric Water Heating",
        true,
      ),
      waterSewer: mcs("col-WElsMcQ", "boolean", "Water & Sewer", true),
      trashCollection: mcs("col-YJt59t-", "boolean", "Trash Collection", true),
      districtEnergyHeating: mcs(
        "col-TQGePfn",
        "boolean",
        "District Energy Heating",
        true,
      ),
      districtEnergyWaterHeating: mcs(
        "col-qcYF86e",
        "boolean",
        "District Energy Water Heating",
        true,
      ),
      space: mcs("col-ASpRcFN", "string", "_space", false),
    },
    subsidyWorker: {
      firstName: mcs("col-hfOt7C0", "string", "First name", false),
      lastName: mcs("col-L_VYXUd", "string", "Last name", false),
      id: mcs("col-TQPNwF_", "string", "ID", true),
      email: mcs("col-88UVmfe", "string", "Email", false),
      backupEmail: mcs("col-dNdbe6y", "string", "Backup email", false),
      phoneNumber: mcs("col-6VuYdwS", "string", "Phone number", false),
      organization: mcs("col-tPe80XG", "string", "Organization", false),
      programs: mcs("col-gN6fMbl", "string", "Programs", false),
      covers: mcs("col-J13PcBt", "string", "Covers", false),
      updateDate: mcs("col-MnyQXGB", "date", "Update date", false),
    },
    tenantPros: {
      id: mcs("col-DGFdnb-", "string", "ID", true),
      firstName: mcs("col-WrouvG3", "string", "First Name", false),
      lastName: mcs("col-7DS8uNK", "string", "Last Name", false),
      householdProspectId: mcs(
        "col-mhlI1zY",
        "string",
        "Household prospect ID",
        false,
      ),
      incomeSources: mcs("col-ldU8XUc", "string", "Income sources", false),
      incomeAmountMonthly: mcs(
        "col-eywE1hX",
        "number",
        "Income amount monthly",
        true,
      ),
      issues: mcs("col-amHKB33", "string", "Issues", false),
    },
    test: {
      column5: mcs("col-Oy9WtzQ", "string", "Column 5", true),
      id: mcs("col-8wOXbE6", "string", "ID", false),
      number: mcs("col-kJ47IXM", "number", "Number", false),
      dropdown: mcs("col-4_IzNLS", "yesOrNo", "Dropdown", false),
      date: mcs("col--K2Vvyh", "date", "Date", true),
    },
    unit: {
      name: mcs("col-6WTZgxx", "string", "Name", true),
      id: mcs("col-Qo3J03G", "string", "ID", true),
      propertyId: mcs("col-lrmLxqZ", "string", "Property ID", false),
      unitIdentifier: mcs("col-6lzrdO8", "string", "Unit identifier", false),
      addressLabel: mcs("col-jfe-foO", "string", "Address label", true),
      bedroomCount: mcs("col-jW2kk6k", "number", "Bedroom count", false),
      bathroomCount: mcs("col-OjXNgxW", "number", "Bathroom count", false),
      unitLocation: mcs("col-QyE4mns", "string", "Unit location", false),
      propertyName: mcs("col-VmQmaL-", "string", "Property name", true),
      streetAddress: mcs("col-euGUQGm", "string", "Street address", true),
      zipCode: mcs("col-8dSwV9O", "number", "Zip code", true),
      rentReasonablenessCompType: mcs(
        "col-XdcNPGi",
        "string",
        "Rent reasonableness comp type",
        true,
      ),
      unitStandardName: mcs(
        "col-70aCBAb",
        "string",
        "Unit standard name",
        true,
      ),
      rentDue: mcs("col-v5NXrsS", "string", "Rent due", false),
      householdName: mcs("col-Mgm5WDL", "string", "Household name", false),
      totalMonthlyRent: mcs(
        "col-x-nfN3F",
        "string",
        "Total monthly rent",
        false,
      ),
      securityDeposit: mcs("col-s6Coo3X", "string", "Security deposit", false),
      rentIncreaseDates: mcs(
        "col-FDIXEKX",
        "string",
        "Rent increase dates",
        false,
      ),
      runnerRugOptimalMeasurements: mcs(
        "col-8MKf5R4",
        "string",
        "Runner rug optimal measurements",
        false,
      ),
      refrigeratorSpotDimensions: mcs(
        "col-vSvL3Rv",
        "string",
        "Refrigerator spot dimensions",
        false,
      ),
      dishwasherDimensions: mcs(
        "col-eZKABlO",
        "string",
        "Dishwasher dimensions",
        false,
      ),
      windowUnitAirConditioner: mcs(
        "col-Qa7kjlt",
        "string",
        "Window unit air conditioner",
        false,
      ),
      showerRodLength: mcs("col-7xQbB7A", "string", "Shower rod length", false),
      furnaceId: mcs("col-oCIcC_4", "string", "Furnace ID", false),
      furnaceName: mcs("col-1b27zS9", "string", "Furnace name", true),
      needAccessForFurnaceTuneUp: mcs(
        "col-tl-7F_a",
        "string",
        "Need access for furnace tune up",
        false,
      ),
      needAccessForFilterReplacement: mcs(
        "col-XKCYp-Z",
        "string",
        "Need access for filter replacement",
        false,
      ),
      avgGasBillMonthly: mcs(
        "col-O4spxsQ",
        "string",
        "Avg gas bill monthly",
        false,
      ),
      avgElectricBillMonthly: mcs(
        "col-CBzNuou",
        "string",
        "Avg electric bill monthly",
        false,
      ),
      laundryDays: mcs("col-JLxgTft", "string", "Laundry days", false),
      noticeGivenForRentIncrease: mcs(
        "col-9u79MPa",
        "string",
        "Notice given for rent increase",
        false,
      ),
      rentUpdateEnter: mcs(
        "col-uwbyE7w",
        "boolean",
        "Rent update enter",
        false,
      ),
      rentUpdateStatus: mcs(
        "col-k6cKvLp",
        "string",
        "Rent update status",
        false,
      ),
    },
    valueConfig: {
      id: mcs("col-KISd0k_", "string", "ID", false),
      transactionDescription: mcs(
        "col-My0v9xM",
        "string",
        "Transaction description",
        true,
      ),
      chargeDescription: mcs(
        "col-4MRAohP",
        "string",
        "Charge description",
        true,
      ),
      chargeRecurringDescription: mcs(
        "col-LshlsTS",
        "string",
        "Charge recurring description",
        false,
      ),
      chargeOnetimeDescription: mcs(
        "col-ZFyzZf4",
        "string",
        "Charge onetime description",
        false,
      ),
      chargeReduceDescription: mcs(
        "col-FqR_6se",
        "string",
        "Charge reduce description",
        false,
      ),
      rentPortionName: mcs("col-LtgQHTi", "string", "Rent portion name", false),
      paymentType: mcs("col-9CulPu2", "string", "Payment type", false),
      payerCategory: mcs("col-_DwO2R3", "string", "Payer category", false),
      paymentAllocateWhat: mcs(
        "col-umhxhPg",
        "string",
        "Payment allocate what",
        false,
      ),
      expenseCategory: mcs("col-u0Fstxj", "string", "Expense category", false),
      expenseCategoryTaxable: mcs(
        "col-9XaRDGK",
        "string",
        "Expense category taxable",
        true,
      ),
      expenseCategoryBank: mcs(
        "col-k3_mD_q",
        "string",
        "Expense category bank",
        true,
      ),
      residenceTaxAdjust: mcs(
        "col-08YH-3Z",
        "string",
        "Residence tax adjust",
        false,
      ),
      receiptFormat: mcs("col-StBJQCC", "string", "Receipt format", false),
      firstOfEachMonthThisYear: mcs(
        "col-sgLi6Pa",
        "date",
        "First of each month this year",
        true,
      ),
      januaryQuartersThisYear: mcs(
        "col-iRu6A9m",
        "date",
        "January quarters this year",
        true,
      ),
      februaryQuartersThisYear: mcs(
        "col-ZOaq1Tm",
        "date",
        "February quarters this year",
        true,
      ),
      marchQuartersThisYear: mcs(
        "col-MZIxCW9",
        "date",
        "March quarters this year",
        true,
      ),
      yesOrNo: mcs("col-d5gC0K8", "string", "Yes or no", false),
      oneOccupancyOrAll: mcs(
        "col-qpxkX-L",
        "string",
        "One occupancy or all",
        false,
      ),
      buildingType: mcs("col-0eGzKFb", "string", "Building type", false),
      buildingTypeAndAny: mcs(
        "col-jJBNGWq",
        "string",
        "Building type and any",
        true,
      ),
    },
    valueName: {
      id: mcs("col-JhdzBMj", "string", "ID", false),
      valueName: mcs("col-35A6jyC", "string", "Value name", true),
    },
    variable: {
      id: mcs("col-bMRolLy", "string", "ID", false),
      today: mcs("col-07PPMWD", "date", "Today", true),
      "15thOfThisMonth": mcs("col-yfTbEv-", "date", "15th of this month", true),
      "2MonthsOut": mcs("col-_P8yYla", "date", "2 months out", true),
    },
    year: {
      id: mcs("col-MEgZSIX", "string", "ID", true),
      name: mcs("col-Z2qkqDh", "number", "Name", false),
      dayCount: mcs("col-hZo8xT2", "number", "Day count", true),
    },
  } as const,
);

export type AllColTraits = typeof allColTraits;

export type ColumnName<SN extends SheetNameSimple = SheetNameSimple> =
  keyof AllColTraits[SN];

export type TableColTraits<SN extends SheetNameSimple> = AllColTraits[SN];

export type ColumnValueName<
  SN extends SheetNameSimple,
  CN extends ColumnName<SN>,
> = AllColTraits[SN][CN]["valueName" & keyof AllColTraits[SN][CN]];

export type ColTraits<
  SN extends SheetNameSimple,
  CN extends ColumnName<SN>,
> = ColTraitsBase<ColumnValueName<SN, CN> & ValueName>;

export type ColumnValueSchema<
  SN extends SheetNameSimple,
  CN extends ColumnName<SN>,
> = ValueSchema<ColumnValueName<SN, CN> & ValueName>;

export type ColumnValue<
  SN extends SheetNameSimple,
  CN extends ColumnName<SN>,
> = Value<ColumnValueName<SN, CN> & ValueName>;

export type SheetDataValues<
  SN extends SheetNameSimple,
  VNS extends ColumnName<SN> = ColumnName<SN>,
> = {
  [CN in VNS]: ColumnValue<SN, CN>;
};

export function getSheetColumnNames<SN extends SheetNameSimple>(
  sheetName: SN,
): ColumnName<SN>[] {
  return Obj.keys(allColTraits[sheetName]);
}

// columnConfig isn't actually very unique. The only unique
export function getColumnTraitByName<
  TN extends SheetNameSimple,
  CN extends ColumnName<TN>,
  K extends keyof ColTraits<TN, CN>,
>(sheetName: TN, columnName: CN, key: K): ColTraits<TN, CN>[K] {
  return (allColTraits[sheetName][columnName] as ColTraits<TN, CN>)[key];
}

export type IndexedColIdTraits = KeyedMap<
  Record<string, ColTraitsBase>,
  "columnId",
  "columnName"
>;

type AllColTraitsGidColId = Map<number, IndexedColIdTraits>;
function makeAllColTraitsGidColId(): AllColTraitsGidColId {
  return schemaSheetNames.reduce((attrs, sheetName) => {
    const sheetGid = getSheetTraitByName(sheetName, "sheetGid");
    attrs.set(
      sheetGid,
      Obj.toKeyedMap(allColTraits[sheetName], "columnId", "columnName"),
    );
    return attrs;
  }, new Map() as AllColTraitsGidColId);
}

const allColTraitsGidColId = makeAllColTraitsGidColId();

export type ColTraitsRaw =
  IndexedColIdTraits extends Map<any, infer V> ? V : never;
export type ColTraitsRawKey = keyof ColTraitsRaw;
export function getColumnTraitByIndex<K extends ColTraitsRawKey>(
  sheetId: number,
  columnId: string,
  key: K,
): ColTraitsRaw[K] {
  const colTraits = valS.assert(
    allColTraitsGidColId.get(sheetId)?.get(columnId),
    `column attributes for sheetId=${sheetId}, columnId=${columnId}`,
  );
  return colTraits[key];
}
export function getSheetColumnIds(sheetGid: number): MapIterator<string> {
  return valS
    .assert(
      allColTraitsGidColId.get(sheetGid),
      `column attributes for sheetId=${sheetGid}`,
    )
    .keys();
}

const allColTraitsFlat = Obj.flattenTwoLevels(allColTraits, nameDelimiter);
type AllColTraitsFlat = typeof allColTraitsFlat;
export type ColumnFullNameSimple = keyof AllColTraitsFlat;

export type ColumnFullName<
  SN extends SheetNameSimple,
  CN extends ColumnName<SN>,
> = `${SN}${NameDelimiter}${CN & string}`;
