#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Re-runnable: each finished stage is recorded in STATE_DIR/wizard.env and offered as a skip next time.
AGENT_EMAIL="byronbroughtenai@gmail.com"
MCP_NAME="gworkspace"
MCP_PIN="workspace-mcp==1.28.0"
STATE_DIR="$HOME/.config/gworkspace-mcp"
CLIENT_SECRET_PATH="$STATE_DIR/client_secret.json"
CREDENTIALS_DIR="$STATE_DIR/credentials"
ENV_FILE="$STATE_DIR/wizard.env"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mkdir -p "$STATE_DIR" && chmod 700 "$STATE_DIR"

spreadsheet_id_of() {
  sed -nE 's/^[[:space:]]*"spreadsheetId":[[:space:]]*"([^"]+)".*/\1/p' "$REPO_ROOT/packages/$1/sheets.config.json" 2>/dev/null | head -n1
}
DEV_ID="$(spreadsheet_id_of framework)"
APP_ID="$(spreadsheet_id_of real-estate)"

# done_before KEY: true when KEY was recorded on an earlier run and the human chooses to skip it.
done_before() {
  local when; when=$(_existing "$1" || true)
  [[ -n "$when" ]] || return 1
  note "Done on an earlier run ($when)."
  ! confirm "Redo this stage?"
}
mark_done() { write_env "$1" "$(date +%Y-%m-%d)"; }

# api_of SERVICE: the Cloud API a workspace-mcp --tools service needs.
api_of() {
  case "$1" in
    calendar) printf 'calendar-json.googleapis.com' ;;
    *) printf '%s.googleapis.com' "$1" ;;
  esac
}

TOTAL_STAGES=8

banner "Agent account MCP setup (gworkspace, as $AGENT_EMAIL)"

_clear
say "Which workspace-mcp services should gworkspace load? Adding one later is a re-run with a new list."
note "Each one needs its API turned on (stage 3), the server re-registered (stage 6) and consent redone (stage 7)."
previous_services=$(_existing MCP_SERVICES || true)
ask MCP_SERVICES "Services, space-separated (Enter on a first run: docs drive sheets):"
MCP_SERVICES="${MCP_SERVICES:-docs drive sheets}"
if [[ "$MCP_SERVICES" != "$previous_services" ]]; then
  if [[ -n "$previous_services" ]]; then
    warn "Services changed: redo stages 3, 6 and 7, and add the new tools' rules to .claude/settings.json."
  fi
  write_env MCP_SERVICES "$MCP_SERVICES"
  pause
fi
read -ra SERVICES <<< "$MCP_SERVICES"
API_IDS=""
for service in "${SERVICES[@]}"; do API_IDS="${API_IDS:+$API_IDS,}$(api_of "$service")"; done

stage "Share the spreadsheets with the agent account"
if ! done_before SPREADSHEETS_SHARED; then
  [[ -n "$DEV_ID" && -n "$APP_ID" ]] || { warn "couldn't read spreadsheetId from packages/*/sheets.config.json"; exit 1; }
  say "Signed in as your MAIN account, share each spreadsheet with $AGENT_EMAIL as Editor."
  open_url "https://docs.google.com/spreadsheets/d/$DEV_ID/edit"
  step "Sheets Framework Dev: Share → add $AGENT_EMAIL → Editor → untick 'Notify' → Share."
  pause "Press Enter when the dev spreadsheet is shared."
  open_url "https://docs.google.com/spreadsheets/d/$APP_ID/edit"
  step "Real Estate Manager: Share → add $AGENT_EMAIL → Editor → Share."
  step "Share any Drive folders or Docs you want agents to reach the same way."
  confirm "Both spreadsheets are shared with $AGENT_EMAIL as Editor?" || { warn "Stopping: the final read test would fail."; exit 1; }
  mark_done SPREADSHEETS_SHARED
fi

stage "Create the Google Cloud project as the agent account"
if ! done_before GCP_PROJECT_ID; then
  warn "Every Cloud console step from here is as $AGENT_EMAIL, not your main account."
  open_url "https://console.cloud.google.com/projectcreate?authuser=$AGENT_EMAIL"
  step "If the avatar (top right) isn't $AGENT_EMAIL, switch to it, then reload."
  step "Project name: agent-workspace-mcp (any name works) → Create."
  step "Copy the Project ID shown under the name (it may differ from the name)."
  ask GCP_PROJECT_ID "Paste the project ID:"
  write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
fi
GCP_PROJECT_ID="${GCP_PROJECT_ID:-$(_existing GCP_PROJECT_ID)}"
CONSOLE_QS="project=$GCP_PROJECT_ID&authuser=$AGENT_EMAIL"

stage "Turn on the APIs for: $MCP_SERVICES"
if ! done_before APIS_ENABLED; then
  open_url "https://console.cloud.google.com/flows/enableapi?apiid=$API_IDS&$CONSOLE_QS"
  step "Check the project picker shows $GCP_PROJECT_ID, then Next → Enable."
  confirm "Every listed API is enabled?" || exit 1
  mark_done APIS_ENABLED
fi

stage "Consent screen: External, published to production"
if ! done_before CONSENT_PUBLISHED; then
  say "Publishing before any token is minted keeps the refresh token from expiring after 7 days."
  open_url "https://console.cloud.google.com/auth/overview?$CONSOLE_QS"
  step "Get started → App name: agent-workspace-mcp → support email: $AGENT_EMAIL → Next."
  step "Audience: External → Next → contact email: $AGENT_EMAIL → agree → Create."
  step "Skip Data access: no scopes need declaring for an unverified app."
  open_url "https://console.cloud.google.com/auth/audience?$CONSOLE_QS"
  step "Audience → Publishing status: Publish app → Confirm. It should read 'In production'."
  note "Leave it unverified; consent will show a 'Google hasn't verified this app' warning."
  confirm "Publishing status reads 'In production'?" || exit 1
  mark_done CONSENT_PUBLISHED
fi

stage "Desktop OAuth client, secret stored outside the repo"
if ! done_before CLIENT_SECRET_SAVED; then
  open_url "https://console.cloud.google.com/auth/clients/create?$CONSOLE_QS"
  step "Application type: Desktop app → Name: gworkspace-mcp → Create."
  step "In the dialog, Download JSON (Google won't show the secret again)."
  newest=$(ls -t "$HOME"/Downloads/client_secret_*.json 2>/dev/null | head -n1 || true)
  [[ -n "$newest" ]] && note "Newest download: $newest"
  ask DOWNLOADED_SECRET "Path to the downloaded JSON${newest:+ (Enter for the newest)}:"
  DOWNLOADED_SECRET="${DOWNLOADED_SECRET:-$newest}"
  [[ -f "$DOWNLOADED_SECRET" ]] || { warn "No file at '$DOWNLOADED_SECRET'."; exit 1; }
  mv "$DOWNLOADED_SECRET" "$CLIENT_SECRET_PATH" && chmod 600 "$CLIENT_SECRET_PATH"
  printf '  %s✓ moved%s client secret → %s (600)\n' "$GREEN" "$RESET" "$CLIENT_SECRET_PATH"
  mark_done CLIENT_SECRET_SAVED
fi

stage "Register the gworkspace server for this project"
if ! done_before MCP_REGISTERED; then
  if ! command -v uvx >/dev/null 2>&1; then
    warn "uvx isn't installed; it comes with uv."
    confirm "Install uv with Homebrew now (brew install uv)?" && brew install uv
    command -v uvx >/dev/null 2>&1 || { warn "Install uv, then re-run."; exit 1; }
  fi
  say "Adds '$MCP_NAME' to ~/.claude.json under $REPO_ROOT (local scope), pinned to $MCP_PIN:"
  note "uvx $MCP_PIN --single-user --tools $MCP_SERVICES"
  confirm "Write the entry (replacing any existing '$MCP_NAME')?" || exit 1
  (
    cd "$REPO_ROOT"
    claude mcp remove "$MCP_NAME" -s local >/dev/null 2>&1 || true
    claude mcp add "$MCP_NAME" -s local \
      -e "GOOGLE_CLIENT_SECRET_PATH=$CLIENT_SECRET_PATH" \
      -e "WORKSPACE_MCP_CREDENTIALS_DIR=$CREDENTIALS_DIR" \
      -e "USER_GOOGLE_EMAIL=$AGENT_EMAIL" \
      -- uvx "$MCP_PIN" --single-user --tools "${SERVICES[@]}"
  )
  mark_done MCP_REGISTERED
fi

stage "Restart Claude Code and consent as the agent account"
if ! done_before CONSENT_GRANTED; then
  if [[ -f "$CREDENTIALS_DIR/$AGENT_EMAIL.json" ]] && confirm "Delete the stored token so consent runs fresh (dead token or new scopes)?"; then
    rm "$CREDENTIALS_DIR/$AGENT_EMAIL.json"
  fi
  step "Quit Claude Code and start it again at $REPO_ROOT."
  step "Run /mcp and check '$MCP_NAME' is connected."
  step "Ask the agent: \"List the spreadsheets gworkspace can see.\""
  step "It returns a Google sign-in link. Open it, choose $AGENT_EMAIL."
  step "At 'Google hasn't verified this app': Advanced → Go to agent-workspace-mcp → Continue → allow every scope."
  step "The browser lands on a localhost success page; ask the agent to retry."
  confirm "The agent listed spreadsheets without asking you to sign in again?" || exit 1
  mark_done CONSENT_GRANTED
fi

stage "Read the dev spreadsheet through gworkspace"
say "Ask the agent, in the restarted session:"
note "Read the first 5 rows of the first sheet of $DEV_ID with mcp__gworkspace__read_sheet_values."
if confirm "It returned cell values from Sheets Framework Dev?"; then
  mark_done READ_TEST_PASSED
else
  warn "Not passing yet: check the sharing (stage 1) and /mcp, then re-run. Don't run the retire wizard."
  exit 1
fi

finish
say "gworkspace works. Next: scripts/retire-gsheets-service-account.sh retires the old service account."
