import { Obj } from "../../utils/Obj";
import type { CombineStringsWithFlat } from "../../utils/Str";
import { makeSchemaStructure } from "./0.1 makeSchema";
import {
  type ValidateValue,
  type Value,
  type ValueAttributes,
  type ValueName,
} from "./3.2 valueAttributes";
import { type TableNameSimple } from "./4.0 tableAttributes";

export interface ColumnAttributesBase<VN extends ValueName = ValueName> {
  columnId: string;
  valueName: VN;
  isFormula: boolean;
  emptyAllowed: boolean;
  customDefaultValue: Value<VN> | null;
}
function makeColumnAttributes<VN extends ValueName>(
  columnId: string,
  valueName: VN,
  isFormula: boolean,
  emptyAllowed: boolean = false,
  customDefaultValue: Value<VN> = null,
): ColumnAttributesBase<VN> {
  return {
    valueName,
    columnId,
    isFormula,
    emptyAllowed,
    customDefaultValue,
  };
}

const mca = makeColumnAttributes;
type TableColumnAttributessBase = Record<string, ColumnAttributesBase>;
type AllColumnAttributessBase = Record<
  TableNameSimple,
  TableColumnAttributessBase
>;

const allColumnAttributes = makeSchemaStructure(
  {} as AllColumnAttributessBase,
  {
    export: {
      necessaryAverageCostsMonthly: mca("col-iE08rV_", "number", true),
      subsidyPaymentsMonthly: mca("col-c2XXKTP", "number", true),
      tenantPaymentsMonthly: mca("col-vb-UnbW", "string", true),
      realEstateCostsMinusTenantPayments: mca("col-nQar3gw", "string", true),
      businessCheckingBalance: mca("col-b684Igh", "number", true),
      businessCheckingBalanceMinusNextBankPayments: mca(
        "col-M1iFwht",
        "number",
        true,
      ),
    },
    finance: {
      businessAccountBankPaymentCushion: mca("col-VttZ8-h", "number", true),
      businessCashAccount: mca("col-E5Sd1yv", "number", true),
      businessAccountDebt: mca("col-qLIGagR", "number", true),
      helocAvailable: mca("col-8eXfJd9", "number", true),
      helocSpent: mca("col-dypG3j3", "number", true),
      bankUtilityPaymentsMonthlyAvg: mca("col-UkNYRTj", "number", true),
      bankPaymentsMonthly: mca("col-RuG2S80", "number", true),
      mortgagePaymentsMonthly: mca("col-GJ3W5CH", "number", true),
      helocPaymentsMonthly: mca("col-_F9eVFO", "number", true),
      utilityPaymentsMonthlyAvg: mca("col-WNSnm31", "number", true),
      budgetsMonthly: mca("col-LqC3tvw", "number", true),
      maintenanceBudgetMonthly: mca("col-Usg-WMU", "number", true),
      lawncareBudgetMonthly: mca("col-USPILuC", "number", true),
      capExBudgetMonthly: mca("col-zrcshgj", "number", true),
      vacancyBudgetMonthly: mca("col-0MFgFfN", "number", true),
      flexibleIncomeMonthlyAvg: mca("col-Kctzpyn", "string", true),
      discretionaryIncomeMonthlyAvg: mca("col-S4V6HuT", "string", true),
      realEstateReceivableMonthly: mca("col-pCYNnOt", "string", true),
      subsidyIncomeMonthly: mca("col-ojc6Pj3", "number", true),
      tenantIncomeMonthly: mca("col-fSe_zos", "string", true),
    },
    recurringTransaction: {
      item: mca("col-T5ui0fF", "string", false),
      transactionType: mca("col-ViD8IQV", "string", false),
      transactWith: mca("col-1lm7yg5", "string", false),
      propertyId: mca("col-0Hg4hkA", "string", false),
      transactionDayOfMonth: mca("col-Rk2rqXQ", "number", false),
      monthsBetweenTransactions: mca("col-x7aeIs_", "number", false),
      nextTransactionDateEarly: mca("col-Qq_cpwI", "date", true),
      nextTransactionAmount: mca("col-CCXBkki", "number", true),
      averageMonthlyTransactionAmount: mca("col-sOSxVtN", "string", false),
      notes: mca("col-NRvXapU", "string", false),
    },
    householdYear: {
      name: mca("col-j48UWNj", "string", true),
      id: mca("col-slPqvjH", "string", true),
      baseId: mca("col-lWZtIG_", "baseId", false),
      occupancyId: mca("col-5NpZpfU", "string", false),
      year: mca("col-JPQvvQo", "number", false),
      residentCount: mca("col-bvqNtvg", "number", true),
      householdRentPaidPerResident: mca("col-tzpNLQZ", "number", true),
      caretakerRentReducedPerResident: mca("col-FIAS76q", "number", true),
      totalAttributedPerResident: mca("col-nXoe3eF", "number", true),
      totalAttributedToOccupancy: mca("col-dD8eVIq", "number", true),
      caretakerRentReduced: mca("col-55cJEpn", "number", true),
      householdRentPaid: mca("col-1dAHPjH", "number", true),
      firstDateChargedRentInYear: mca("col-3XZvYtM", "date", true),
      lastDateChargedRentInYear: mca("col-Jm50CK4", "date", true),
      firstRentChargeDate: mca("col-zvBywR1", "date", true),
      lastDateChargedRent: mca("col-0VgdtTA", "date", true),
      subsidyRentPaid: mca("col-OipY03K", "number", true),
      scrollSpace: mca("col-SqUK6d0", "string", false),
    },
    propertyYear: {
      name: mca("col--GXBgqg", "string", true),
      id: mca("col-pLbR676", "string", true),
      baseId: mca("col-pfUIsJG", "baseId", false),
      propertyId: mca("col-MqF-anY", "string", false),
      year: mca("col-TawhTyt", "number", false),
      primarySpace: mca("col-alQOQuj", "number", false),
      notPrimarySpace: mca("col-QkHxyMW", "number", true),
      primaryTimeOwned: mca("col-iSuANXq", "number", false),
      notPrimaryTimeOwned: mca("col-kj62b6N", "number", true),
      total: mca("col-w0edV92", "number", true),
      incomeFromHouseholds: mca("col-iD9skHh", "number", true),
      incomeFromSubsidies: mca("col-7X1LeUo", "number", true),
      incomeFromOtherSources: mca("col-QseAaB5", "number", true),
      "1099Misc": mca("col-dcCSLJn", "string", false),
      incomeExptected: mca("col-8LhB3qW", "string", false),
      incomeExpectedMaximum: mca("col-M08K-ca", "string", false),
      budgetsCostEstimates: mca("col-qhjoI7t", "string", false),
      maintenanceBudget: mca("col-4r-P97r", "string", false),
      vacancyBudget: mca("col-vBhf-u-", "string", false),
      lawncareBudget: mca("col-PT5uv-S", "string", false),
      capexBudget: mca("col-p54csmV", "string", false),
      utilityCostEstimate: mca("col-xy2UuPt", "string", false),
      actualCosts: mca("col-nIf7Xtx", "number", true),
      maintenanceGroundskeepingCosts: mca("col-hYWXrQz", "number", true),
      utilityCosts: mca("col-0KWDOnD", "number", true),
      capexCosts: mca("col-exdmXLl", "number", true),
      vacancyCosts: mca("col-J7djr8C", "string", false),
      taxableTotal: mca("col-Bzs_uJu", "number", true),
      absoluteTotal: mca("col-PGC9pdA", "number", true),
      cleaningMaintenance: mca("col-RmgQG7B", "number", true),
      insurance: mca("col-lUNFd66", "number", true),
      mortgageInterestPaidToBanks: mca("col-J2F1NxS", "number", true),
      repair: mca("col-AiWPNkl", "number", true),
      supplies: mca("col-4OAhSq1", "number", true),
      taxes: mca("col-2pLgeyL", "number", true),
      utilities: mca("col-uU2oYki", "number", true),
      depreciationExpenseOrDepletion: mca("col-Y9hnxem", "number", true),
      legalProfessional: mca("col-D6zQXl4", "number", true),
      advertising: mca("col-aHKMePu", "number", true),
      autoAndTravel: mca("col-dx-FCXy", "number", true),
      mgmtFees: mca("col-hmM-lMs", "number", true),
      commissions: mca("col-4J2Mxv9", "number", true),
      otherInterest: mca("col-JbhS4Y6", "number", true),
      other: mca("col-okSrW_E", "number", true),
      principal: mca("col-i_x5Gzf", "number", true),
    },
    businessExpense: {
      date: mca("col-viByQSW", "date", false),
      amount: mca("col-wH6T9oD", "number", false),
      description: mca("col-sGzmf3i", "string", false),
      deductibleAmount: mca("col-D4Um8gD", "string", true),
      id: mca("col-gI3wWFP", "string", true),
      baseId: mca("col-ZayN3nr", "baseId", false),
      billerName: mca("col-ws-Kl9O", "string", false),
      expenseCategory: mca("col-1FLurWI", "expenseCategory", false),
      receiptFormat: mca("col-PXfEBEq", "receiptFormat", false),
      taxAdjust: mca("col-FjnqqGg", "residenceTaxAdjust", false),
      notes: mca("col--TmFGAd", "string", false),
    },
    propertyExpense: {
      expenseName: mca("col-w_PiWJi", "string", true),
      id: mca("col-Qj2-mYp", "string", true),
      baseId: mca("col-WRWFjkO", "baseId", false),
      propertyId: mca("col-1hpEB5R", "string", false),
      date: mca("col-eg74PeC", "date", false),
      year: mca("col-4DAHsCd", "number", true),
      propertyYearId: mca("col-WchviCc", "string", true),
      unitId: mca("col-rH-ATRE", "string", false),
      billerName: mca("col-icHn2T8", "string", false),
      description: mca("col-g1WqJPr", "string", false),
      expenseCategory: mca("col-HVmhEMV", "expenseCategory", false),
      receiptFormat: mca("col-qpJqo2x", "receiptFormat", false),
      amount: mca("col-Tum3aH7", "number", false),
      deductibleAmount: mca("col-55XKM_i", "number", true),
      taxAdjust: mca("col-V2BAd2p", "residenceTaxAdjust", false),
      isUpfrontInvestment: mca("col-bK8A6h_", "yesOrNo", false),
      notes: mca("col-tf50IlU", "string", false),
    },
    quotes: {
      date: mca("col-WGt6dPd", "date", false),
      id: mca("col-h3wgJ39", "string", true),
      baseId: mca("col-_j99KBh", "baseId", false),
      prospectiveBillerName: mca("col-QlJe96V", "string", false),
      billerName: mca("col-ly-BMJ_", "string", false),
      billerCategory: mca("col-3hlIrmQ", "string", true),
      service: mca("col-4swJjZZ", "string", false),
      amount: mca("col-7xyQYhm", "number", false),
      preferredForService: mca("col-Fwju2h2", "string", false),
      notes: mca("col-qyRbDVX", "string", false),
    },
    biller: {
      name: mca("col-IAA7ymg", "string", false),
      contact: mca("col-TECY-w9", "string", false),
      id: mca("col-pBwZ74w", "string", true),
      baseId: mca("col-bSgizeM", "baseId", false),
      category: mca("col-HmUfHCe", "string", false),
      defaultExpenseCategory: mca("col-lZdCfdb", "string", false),
      defaultExpenseDescription: mca("col-Q7pTk6J", "string", false),
      notes: mca("col-ioUEJuB", "string", false),
    },
    subPayAllocation: {
      name: mca("col-uzEH5HL", "string", true),
      id: mca("col-PJ1qm7P", "string", true),
      baseId: mca("col-pV6BtqR", "baseId", false),
      paymentId: mca("col-jAnSZoZ", "string", false),
      paymentDate: mca("col-ek62dJt", "date", true),
      formOfPayment: mca("col-3jQA3el", "string", true),
      paymentAllocated: mca("col-ci9Olfh", "number", true),
      chargeId: mca("col-dWzWhmG", "string", false),
      chargeDescription: mca("col-20hJLMV", "string", true),
      subsidyAgreementId: mca("col-xymKv30", "string", true),
      occupancyId: mca("col--Kn3Eaj", "string", true),
      propertyId: mca("col-GnmfHIq", "string", true),
      paymentUnallocated: mca("col-zZm04Vj", "number", true),
      chargeUnpaid: mca("col-AdryODU", "number", true),
      amount: mca("col-uPlGvHp", "number", true),
      allocateFullAmount: mca("col-dGJNUqv", "boolean", false),
      lesserAmount: mca("col-BZ8hOws", "string", false),
      filledOut: mca("col-Goy1X8c", "string", true),
      processed: mca("col-pZ746C-", "yesOrNo", true),
    },
    subsidyPayment: {
      date: mca("col-_YBhAu5", "date", false),
      id: mca("col-PTux14k", "string", true),
      allocationName: mca("col-f083hYz", "string", true),
      baseId: mca("col-5KTGNWc", "baseId", false),
      subsidyProgramId: mca("col-3wCKfdm", "string", false),
      numAllocated: mca("col-Bc6Z9wd", "number", true),
      formOfPayment: mca("col-dkz_xwK", "paymentType", false),
      amount: mca("col-AcmAj-n", "number", false),
      detailsVerified: mca("col-V9Ue8yu", "yesOrNo", false),
      amountAllocated: mca("col-OHWAx0k", "number", true),
      amountUnallocated: mca("col-4kyYlK4", "number", true),
      processed: mca("col-s-HNMVx", "yesOrNo", true),
    },
    subsidyCharge: {
      name: mca("col-sUaYozJ", "string", true),
      id: mca("col--nTU65W", "string", true),
      baseId: mca("col-5BajmZs", "baseId", false),
      subsidyAgreementId: mca("col-MONO5y5", "string", false),
      date: mca("col-siQYN_v", "date", false),
      description: mca("col-eki29GV", "chargeDescription", false),
      amount: mca("col-D_ZLCZz", "number", false),
      amountPaid: mca("col-RNSqWma", "number", true),
      amountUnpaid: mca("col-899hXuQ", "number", true),
    },
    subsidyTerms: {
      name: mca("col-YqGL5a7", "string", true),
      id: mca("col-8MJW0am", "string", true),
      baseId: mca("col-ktUHY0U", "baseId", false),
      subsidyAgreementId: mca("col-NGDD5AZ", "string", false),
      occupancyId: mca("col-d7tvBlB", "string", true),
      subsidyProgramId: mca("col-h9ut47r", "string", true),
      occupancyTermsId: mca("col-EiyA0BM", "string", true),
      rentChargeMonthly: mca("col-kSFbjAd", "number", false),
      startDate: mca("col-N98wM8U", "date", false),
      endDate: mca("col-WAdoKW-", "string", false),
      grossRent: mca("col-ubljNHa", "string", false),
      grossUtilities: mca("col-Ysocizr", "string", true),
      paymentStandardName: mca("col-YS5igdB", "string", true),
      gasHeating: mca("col-3Cxid3J", "boolean", true),
      electricHeating: mca("col-2jWsE7c", "boolean", true),
      gasCooking: mca("col-RNh1HKZ", "boolean", true),
      electricCooking: mca("col-Qz2zH70", "boolean", true),
      otherElectric: mca("col-rc7bLdS", "boolean", true),
      gasWaterHeating: mca("col-zVC9R-p", "boolean", true),
      electricWaterHeating: mca("col-jxHTX7M", "boolean", true),
      waterSewer: mca("col-WElsMcQ", "boolean", true),
      trashCollection: mca("col-YJt59t-", "boolean", true),
      districtEnergyHeating: mca("col-TQGePfn", "boolean", true),
      districtEnergyWaterHeating: mca("col-qcYF86e", "boolean", true),
      space: mca("col-ASpRcFN", "string", false),
    },
    subsidyAgreement: {
      name: mca("col-2LNDs6x", "string", true),
      id: mca("col-otFGzR9", "string", true),
      baseId: mca("col-7wTwqbz", "baseId", false),
      occupancyId: mca("col-29TQHcp", "string", false),
      subsidyProgramId: mca("col-0WyuPph", "string", false),
      paymentGroupId: mca("col-hltQiWS", "string", false),
      paymentGroupName: mca("col-CNLvSX-", "string", true),
      agreementStandardName: mca("col-Sh_eL0o", "string", true),
      programStandardName: mca("col-9Aw3w41", "string", true),
      unitStandardName: mca("col-SAZOgc0", "string", true),
      annualRenewalMonth: mca("col-9VVjyo4", "string", false),
      annualInspectionMonth: mca("col-Xb7V4lu", "string", false),
      subsidyContractStartDate: mca("col-h4okp5i", "date", true),
      rentPortionMonthly: mca("col-KL3PAT5", "number", true),
      nextSubsidyContractStartDate: mca("col-RakSpZz", "string", false),
      nextRentPortionMonthly: mca("col-NktpEAf", "string", false),
      updateSubsidyContractEnter: mca("col-pZ_-OR1", "boolean", false),
      subsidyWorkerId: mca("col-0Ep6gXa", "string", false),
      subsidyWorkerFirstName: mca("col-B0Dj4Od", "string", true),
      subsidyWorkerEmail: mca("col-sOKTA2U", "string", true),
      totalCharges: mca("col-YAdsPFN", "number", true),
      totalPayments: mca("col-BPXV2hW", "number", true),
      balance: mca("col-w8vLkK8", "number", true),
    },
    subsidyProgram: {
      name: mca("col-o4QSWBF", "string", true),
      id: mca("col-SP4bmlN", "string", true),
      baseId: mca("col-n0PLQe0", "baseId", false),
      nonResidentPayerId: mca("col-_17JhlQ", "string", false),
      nonResidentPayerName: mca("col-p2sw2KM", "string", true),
      programStandardName: mca("col-J26TwQD", "string", true),
      paymentStandardType: mca("col-2DJ5qZa", "string", false),
      paymentStandardArea: mca("col-Wk4Fb9d", "string", false),
    },
    subsidyWorker: {
      firstName: mca("col-hfOt7C0", "string", false),
      lastName: mca("col-L_VYXUd", "string", false),
      id: mca("col-TQPNwF_", "string", true),
      baseId: mca("col-IipRE86", "baseId", false),
      email: mca("col-88UVmfe", "string", false),
      backupEmail: mca("col-dNdbe6y", "string", false),
      phoneNumber: mca("col-6VuYdwS", "string", false),
      organization: mca("col-tPe80XG", "string", false),
      programs: mca("col-gN6fMbl", "string", false),
      covers: mca("col-J13PcBt", "string", false),
      updateDate: mca("col-MnyQXGB", "date", false),
    },
    occPayAllocation: {
      name: mca("col-EL5Jx4e", "string", true),
      occupancyName: mca("col-vK3JZeg", "string", true),
      id: mca("col-0RTP0fy", "string", true),
      baseId: mca("col-KlLYwOR", "string", false),
      paymentId: mca("col-sCLgGiO", "string", false),
      payerCategory: mca("col-MFTWV8M", "string", true),
      payerName: mca("col-la7Ma45", "string", true),
      formOfPayment: mca("col-M6W-rV_", "string", true),
      paymentAllocated: mca("col-_q_cK2F", "number", true),
      paymentDate: mca("col-6ORlom4", "date", true),
      paymentAmount: mca("col-LDzLVDD", "number", true),
      chargeId: mca("col-9zJ7Xt4", "string", false),
      occupancyId: mca("col-v_hGHUV", "string", true),
      propertyId: mca("col-fmJ3xRA", "string", true),
      chargeDescription: mca("col-A8yIJGL", "string", true),
      chargePaid: mca("col-1uuH5TK", "number", true),
      chargeDate: mca("col-okGjzno", "date", true),
      chargeAmount: mca("col-NQN3uEw", "number", true),
      paymentSummary: mca("col-aRUT8Yn", "string", true),
      chargeSummary: mca("col-_6eV_gi", "string", true),
      paymentUnallocated: mca("col-EnmorGU", "number", true),
      chargeUnpaid: mca("col-Ue-A9_V", "number", true),
      amount: mca("col-Mz8l5TA", "number", true),
      allocateWhat: mca("col-YZpq7hn", "paymentAllocateWhat", false),
      lesserAmount: mca("col-vMrDrB6", "number", false),
      filledOut: mca("col-e9I0oXB", "string", true),
      processed: mca("col-ufcTD5Q", "yesOrNo", true),
    },
    occPayment: {
      id: mca("col-5p14Hz-", "string", true),
      paymentName: mca("col-JL9ycn7", "string", true),
      allocationName: mca("col-HwbqxPk", "string", true),
      baseId: mca("col--lXfPJU", "baseId", false),
      date: mca("col-v7ZMbTS", "date", false),
      payerCategory: mca("col-jU98tyc", "payerCategory", false),
      payerName: mca("col-W340xfW", "string", true),
      householdId: mca("col-2UvItSc", "string", false),
      nonResidentPayerId: mca("col-Y8oUjzx", "string", false),
      formOfPayment: mca("col-8c4YSaF", "paymentType", false),
      amount: mca("col-UzaXtjU", "number", false),
      detailsVerified: mca("col-YrD2LQj", "yesOrNo", false),
      amountAllocated: mca("col-SZpwM52", "number", true),
      allocationCount: mca("col-aip45rN", "number", true),
      amountUnallocated: mca("col-3SmJeZz", "number", true),
      processed: mca("col-DoMfDwe", "yesOrNo", true),
      notes: mca("col-ZLNoGUf", "string", false),
    },
    occChargeReduce: {
      id: mca("col-1rSG9i_", "string", true),
      baseId: mca("col-Vi-jfp9", "baseId", false),
      date: mca("col-9FwOGpt", "date", false),
      chargeId: mca("col-3zLvJOz", "string", false),
      description: mca("col-s_hOaKR", "chargeReduceDescription", false),
      chargeAmount: mca("col-bBHlDi-", "number", true),
      amount: mca("col-kzsS2s_", "number", true),
      reduceFullAmount: mca("col-2KKhHBO", "boolean", false),
      lesserAmount: mca("col-sRi8MA4", "string", false),
      chargeName: mca("col-pW6NptW", "string", true),
    },
    occCharge: {
      name: mca("col-udxK-Hf", "string", true),
      id: mca("col-nLiqq-6", "string", true),
      baseId: mca("col-PqI8hDY", "baseId", false),
      occupancyId: mca("col-IrTjVUr", "string", false),
      occupancyName: mca("col-VGP6Bgk", "string", true),
      date: mca("col-rdw667_", "date", false),
      description: mca("col-Z5b__-f", "string", false),
      amount: mca("col-bDbtLKn", "number", false),
      amountAccounted: mca("col-OCiouvy", "number", true),
      amountUnaccounted: mca("col-N4oYQrk", "number", true),
      notes: mca("col-wsWXgR4", "string", false),
    },
    occupancyTerms: {
      residentAndUnitName: mca("col-yq4jyPb", "string", true),
      id: mca("col-dcm4U7V", "string", true),
      baseId: mca("col-LXSgxvk", "baseId", false),
      occupancyId: mca("col-OXD-Ek9", "string", false),
      noticeDate: mca("col-0dJOCyD", "string", false),
      startDate: mca("col-AtT0nqz", "date", false),
      endDate: mca("col-nhh7hS1", "date", false),
      rentChargeMonthly: mca("col-ivd-pWw", "number", false),
      caretakerRentReductionMonthly: mca("col-h0uS5oi", "number", false),
      petFeeMonthly: mca("col-NXjOs5W", "number", false),
      gasHeating: mca("col-mdfuos3", "boolean", false),
      electricHeating: mca("col-C2tyPDA", "boolean", false),
      gasCooking: mca("col-y4Tjo7G", "boolean", false),
      electricCooking: mca("col-J5X2by5", "boolean", false),
      otherElectric: mca("col-3XZWzZb", "boolean", false),
      gasWaterHeating: mca("col-5q18yvd", "boolean", false),
      electricWaterHeating: mca("col-hr2Ex2L", "boolean", false),
      waterSewer: mca("col-TV-65-Y", "boolean", false),
      trashCollection: mca("col-ahrWo52", "boolean", false),
      districtEnergyHeating: mca("col-hgRDXpl", "boolean", false),
      districtEnergyWaterHeating: mca("col-WnfDv0q", "boolean", false),
      notes: mca("col-9E6_E_l", "string", false),
    },
    paymentGroup: {
      name: mca("col-M2AcrkT", "string", false),
      id: mca("col-8ZambHV", "string", true),
      baseId: mca("col-7Mthxwc", "baseId", false),
    },
    nonResidentPayer: {
      name: mca("col-K_eFNP9", "string", false),
      id: mca("col-rrScEfG", "string", true),
      baseId: mca("col-ffgSafo", "baseId", false),
    },
    occupancy: {
      name: mca("col-jHfWw_p", "string", true),
      id: mca("col-aobYS7A", "string", true),
      baseId: mca("col-h3Fep6G", "baseId", false),
      householdId: mca("col-cQbzV2A", "string", false),
      residentCount: mca("col-yVuonvl", "number", true),
      unitId: mca("col-OsokrlB", "string", false),
      propertyId: mca("col-d8mC6Rn", "string", true),
      unitStandardName: mca("col-I4yjYPD", "string", true),
      isActive: mca("col-tuQZLj-", "string", true),
      firstOccupancyTermsId: mca("col-mnW1daF", "string", true),
      activeOccupancyTermsId: mca("col-s4Zxv4D", "string", true),
      latestOccupancyTermsId: mca("col-EZp4_52", "string", true),
      latestEndedOccupancyTermsId: mca("col-SUlG0Wm", "string", true),
      latestOccupancyTermsStartDate: mca("col-lwvPphy", "date", true),
      firstOccupancyDate: mca("col-KRlbXkL", "date", true),
      latestOccupancyDate: mca("col-BWZ97DV", "date", true),
      subsidyCount: mca("col-6GjBcbG", "number", true),
    },
    household: {
      name: mca("col--IaO_J8", "string", true),
      id: mca("col-e0nP-e3", "string", true),
      baseId: mca("col-2_YjdPY", "baseId", false),
      fullName: mca("col-YICAuy6", "string", true),
      residentCount: mca("col-kSe11BO", "number", true),
      residentFullNames: mca("col-QD287on", "string", true),
      residentFirstNames: mca("col-iqcpd0w", "string", true),
      isActive: mca("col-xKY_f2p", "string", true),
      latestOccupancyId: mca("col-hvhiRQA", "string", true),
      unitId: mca("col-6T5u_QM", "string", true),
      unitName: mca("col-VNunYf2", "string", true),
      propertyId: mca("col-uja0Yrs", "string", true),
      subsidyCount: mca("col-N3Mr2EQ", "number", true),
      nextRentNoticeDate: mca("col-bCbIa94", "date", true),
      "2MonthsFromLastNotice": mca("col-Ps_QhMG", "date", true),
      properNoticeBeforeNextIncrease: mca("col-nCgODfJ", "date", true),
      properNoticeAfterNextIncrease: mca("col-GWnB0N2", "date", true),
      lastRentNoticeDate: mca("col-FJ8iUCl", "date", false),
      nextRentChangeDate: mca("col-nryi7Ib", "date", true),
      nextRentIncreaseDateOverride: mca("col-jnm0WWU", "string", false),
      nextIncreaseDateIfNoticeNotGiven: mca("col-pFdQ2wc", "date", true),
      nextIncreaseDateIfNoticeGiven: mca("col-jS7wkf6", "date", true),
      increaseAnnualDate: mca("col--UUuPBE", "date", true),
      currentLeaseId: mca("col-NTsT2xI", "string", false),
      lastRentChangeDate: mca("col-Y0_rdiQ", "date", true),
      firstRentChargeDate: mca("col-alSTrIH", "string", true),
      lastDayRented: mca("col-XePDi4w", "date", true),
      baseRentChargeMonthly: mca("col-BxUxPE3", "number", true),
      nextBaseRentChargeMonthly: mca("col-BjuCaR7", "number", true),
      increaseBy: mca("col-Ld9NSxu", "number", true),
      nextRentChargeOverride: mca("col-DDMUsEe", "string", false),
      increaseByOverride: mca("col-DzDssB7", "string", false),
      increaseBy3PerYear: mca("col-cUIfPaL", "number", true),
      nextMinusLastIncreaseYears: mca("col-fEFknBM", "number", true),
      daysInNextRentIncreaseYear: mca("col-qdUg1o-", "number", true),
      rentReasonablenessBaseRentMax: mca("col-1tbaSjP", "string", true),
      nextGrossRentMonthly: mca("col-6vZwa1y", "string", true),
      grossRentMonthly: mca("col-FXIspcm", "string", true),
      rentReasonablenessGrossRentMax: mca("col-lmqcCkk", "string", true),
      rentCompType: mca("col-rsTDTeF", "string", true),
      paymentStandardGrossRentMax: mca("col-szqb-Cu", "string", true),
      paymentStandardUtilities: mca("col-8FfdKef", "string", true),
      paymentStandardName: mca("col-OgGGOhY", "string", true),
      gasHeating: mca("col-RWqNDKN", "boolean", false),
      electricHeating: mca("col-s6dJhNw", "boolean", false),
      gasCooking: mca("col-lTFdWvg", "boolean", false),
      electricCooking: mca("col-JkMRVe3", "boolean", false),
      otherElectric: mca("col-OT1NP05", "boolean", false),
      gasWaterHeating: mca("col-1u19gB4", "boolean", false),
      electricWaterHeating: mca("col-c8031x6", "boolean", false),
      waterSewer: mca("col-d96lUou", "boolean", false),
      trashCollection: mca("col-uYwbwrh", "boolean", false),
      districtEnergyHeating: mca("col-C6cHg7u", "boolean", false),
      districtEnergyWaterHeating: mca("col-N6LwTYC", "boolean", false),
      netChargeMonthly: mca("col-W735ss-", "string", true),
      caretakerRentReductionMonthly: mca("col-VlkCkKM", "string", true),
      petFeeMonthly: mca("col-ZYvV_a2", "number", true),
      hhTotalPaymentMonthly: mca("col-WOCcFgo", "string", true),
      hhBaseRentPortionMonthly: mca("col-iWlLmUs", "number", true),
      subsidyRentPortionMonthly: mca("col-0S-3LvX", "number", true),
      currentHhBalance: mca("col-T3P1irS", "string", true),
      totalHhCharges: mca("col-oaHTV9l", "string", true),
      totalHhPayments: mca("col-D6EPFV3", "string", true),
      depositCharged: mca("col-ft6MFJu", "number", true),
      depositReceived: mca("col-FDyT3Vx", "number", true),
      currentSubsidyBalance: mca("col-0OkeFPc", "string", true),
      totalSubsidyCharges: mca("col-owX13pV", "string", true),
      totalSubsidyPayments: mca("col-829U06m", "string", true),
      grandPaymentTotalForTaxes: mca("col-A2Xqlyb", "string", false),
      tenantPaymentTotalForTaxes: mca("col-aDrn-R0", "string", false),
      phaPaymentTotalForTaxes: mca("col-dDeXl-9", "string", false),
    },
    pet: {
      id: mca("col-UukcD_J", "string", true),
      baseId: mca("col-Be7AKRZ", "baseId", false),
      name: mca("col-YfYkSGo", "string", false),
      householdName: mca("col-l9or2xk", "string", true),
      householdId: mca("col-0zkPeRN", "string", false),
      species: mca("col-NyQH0lV", "string", false),
      breed: mca("col-JT5K0b8", "string", false),
      birthDateApproximate: mca("col-i_9-yIb", "date", false),
      age: mca("col-XsopPha", "number", true),
      rentersInsuranceProofDate: mca("col--PB8t09", "date", false),
      vaccinationProofDate: mca("col-WiA5qeP", "date", false),
      petFeeMonthly: mca("col-uHS2k_j", "number", false),
    },
    resident: {
      fullName: mca("col-JQF8pac", "string", true),
      id: mca("col-8zXeQEw", "string", true),
      baseId: mca("col-CNya1SJ", "baseId", false),
      householdId: mca("col-MMj5Qgq", "string", false),
      isActive: mca("col-7LZcJ2t", "string", true),
      firstName: mca("col-ad6YZal", "string", false),
      lastName: mca("col-cU-EQJv", "string", false),
      middleInitial: mca("col-w73gARY", "string", false),
      nameRank: mca("col-XTeBHw2", "number", false),
      ssn: mca("col-KDa6EVM", "string", false),
      dob: mca("col-NmeH8b0", "string", false),
      phoneNumber: mca("col-WDpsFk0", "string", false),
      emailAddress: mca("col-Q_gueC7", "string", false),
      income: mca("col-TX8xQd6", "string", false),
      disability: mca("col-Tkuv1y3", "string", false),
      couldPay: mca("col-FNPG_yQ", "string", false),
    },
    rentComp: {
      rentCompType: mca("col-WPrzo7n", "string", true),
      paymentStandardName: mca("col-Dwm_BvW", "string", true),
      name: mca("col-sk5BTbD", "string", false),
      date: mca("col-PR3fL6v", "date", false),
      paymentStandardYear: mca("col-zAF93A0", "number", false),
      buildingType: mca("col-kwd1nJf", "buildingType", false),
      bedroomCount: mca("col-zUPaL7J", "number", false),
      zipCode: mca("col-SCKjbMh", "number", false),
      baseRentChargeMonthly: mca("col--KXLs3h", "number", false),
      paymentStandardGrossRent: mca("col-XPaiJuh", "string", true),
      paymentStandardUtilities: mca("col-uHlQTjQ", "string", true),
      gasHeating: mca("col-v6ruJbN", "boolean", false),
      electricHeating: mca("col-1tFVepW", "boolean", false),
      gasCooking: mca("col-yXPEotT", "boolean", false),
      electricCooking: mca("col-lEpzVR-", "boolean", false),
      gasWaterHeating: mca("col-fRt2Yns", "boolean", false),
      electricWaterHeating: mca("col-6CK9SPa", "boolean", false),
      otherElectric: mca("col-kDXrKLj", "boolean", false),
      waterSewer: mca("col-d1u_yOr", "boolean", false),
      trashCollection: mca("col-xXD5Eot", "boolean", false),
      districtEnergyHeating: mca("col-qyoPjKZ", "boolean", false),
      districtEnergyWaterHeating: mca("col-5aWwQIZ", "boolean", false),
    },
    unit: {
      name: mca("col-6WTZgxx", "string", true),
      id: mca("col-Qo3J03G", "string", true),
      baseId: mca("col-qFMPPMl", "baseId", false),
      propertyId: mca("col-lrmLxqZ", "string", false),
      unitIdentifier: mca("col-6lzrdO8", "string", false),
      addressLabel: mca("col-jfe-foO", "string", true),
      bedroomCount: mca("col-jW2kk6k", "number", false),
      bathroomCount: mca("col-OjXNgxW", "number", false),
      unitLocation: mca("col-QyE4mns", "string", false),
      propertyName: mca("col-VmQmaL-", "string", true),
      streetAddress: mca("col-euGUQGm", "string", true),
      zipCode: mca("col-8dSwV9O", "number", true),
      rentReasonablenessCompType: mca("col-XdcNPGi", "string", true),
      unitStandardName: mca("col-70aCBAb", "string", true),
      rentDue: mca("col-v5NXrsS", "string", false),
      householdName: mca("col-Mgm5WDL", "string", false),
      totalMonthlyRent: mca("col-x-nfN3F", "string", false),
      securityDeposit: mca("col-s6Coo3X", "string", false),
      rentIncreaseDates: mca("col-FDIXEKX", "string", false),
      runnerRugOptimalMeasurements: mca("col-8MKf5R4", "string", false),
      refrigeratorSpotDimensions: mca("col-vSvL3Rv", "string", false),
      dishwasherDimensions: mca("col-eZKABlO", "string", false),
      windowUnitAirConditioner: mca("col-Qa7kjlt", "string", false),
      showerRodLength: mca("col-7xQbB7A", "string", false),
      furnaceId: mca("col-oCIcC_4", "string", false),
      furnaceName: mca("col-1b27zS9", "string", true),
      needAccessForFurnaceTuneUp: mca("col-tl-7F_a", "string", false),
      needAccessForFilterReplacement: mca("col-XKCYp-Z", "string", false),
      avgGasBillMonthly: mca("col-O4spxsQ", "string", false),
      avgElectricBillMonthly: mca("col-CBzNuou", "string", false),
      laundryDays: mca("col-JLxgTft", "string", false),
      noticeGivenForRentIncrease: mca("col-9u79MPa", "string", false),
      rentUpdateEnter: mca("col-uwbyE7w", "boolean", false),
      rentUpdateStatus: mca("col-k6cKvLp", "string", false),
    },
    furnace: {
      name: mca("col-WgcleWq", "string", true),
      id: mca("col-pjjrcyC", "string", true),
      baseId: mca("col-8Quhgm8", "baseId", false),
      propertyId: mca("col-qM5MaTT", "string", false),
      propertyName: mca("col-MDkBZw7", "string", true),
      location: mca("col--nrSW5N", "string", false),
      descriptor: mca("col-3IqlZi_", "string", false),
      brand: mca("col-19ohP9V", "string", false),
      yearBuilt: mca("col-Jv4pMFL", "number", false),
      age: mca("col-333qv5F", "number", true),
      filterSize: mca("col-sPRYcYC", "string", false),
      filterLocation: mca("col-aOWKf6H", "string", false),
      filtersPresent: mca("col-Q5FZff_", "number", false),
      filterLastReplaced: mca("col-VnZPpE8", "date", false),
    },
    property: {
      name: mca("col-UKOooW1", "string", false),
      id: mca("col-NYNaEua", "string", true),
      baseId: mca("col-BWp64W5", "baseId", false),
      parcelNumber: mca("col-dlhnglY", "number", false),
      streetAddress: mca("col-RxPUYIT", "string", false),
      zipCode: mca("col-mf-CiKH", "number", false),
      yearBuilt: mca("col-iQ1mkhJ", "number", false),
      squareFeet: mca("col-ndjGDiW", "number", false),
      pavedDrivewayCount: mca("col-KaVpIiL", "number", false),
      garageDoorCount: mca("col-sppZ7na", "number", false),
      unitLabelPrepend: mca("col-ij_IAXs", "string", false),
      purchasePrice: mca("col-C2GI_ft", "number", false),
      closingDate: mca("col-7a6orCO", "string", false),
      buildingType: mca("col-pTuQDxB", "string", true),
      unitCount: mca("col-wsgC_ig", "number", true),
      bedroomCount: mca("col-dw-dis5", "number", true),
      furnaceCount: mca("col-9YOXfRA", "number", true),
      projectedRoi: mca("col-l6xMHBT", "string", false),
      upfrontInvestment: mca("col-2jKnRmE", "string", false),
      averagePrincipalMonthly: mca("col-Ww_GkTd", "string", false),
      discretionaryIncomeAnnualAvg: mca("col-fnh7KJP", "number", true),
      discretionaryIncomeMonthlyAvg: mca("col-McnYr72", "number", true),
      flexibleIncomeMonthlyAvg: mca("col-GIXXH26", "number", true),
      grossIncomeMonthly: mca("col-ajl0Vey", "number", true),
      mortgagePaymentMonthly: mca("col-6P8iAZC", "number", false),
      principalPaymentMonthlyAvg: mca("col-Nzx4807", "number", true),
      mortgageBalanceOriginal: mca("col-dMZggrr", "number", false),
      mortgageHolder: mca("col-oeUhWvv", "string", false),
      ltv: mca("col-EeeukQT", "number", true),
      pmi: mca("col-QxQPjIT", "string", false),
      mortgageBalance: mca("col-KhZEP9D", "number", false),
      mortgageNumber: mca("col-UH9nd_C", "number", false),
      helocPaymentMonthly: mca("col-7pB1h02", "number", true),
      helocPaymentOverride: mca("col-fa446XR", "string", false),
      helocInterestPayment: mca("col-Cx25AZv", "number", true),
      helocSpent: mca("col-Sh2sxCg", "number", false),
      helocLimit: mca("col-DDIzEX3", "number", false),
      helocAvailable: mca("col-_sRmpcG", "number", true),
      helocHolder: mca("col-lIgVCtz", "string", false),
      helocInterestRate: mca("col-1xOaDGm", "number", false),
      helocPaymentDay: mca("col-7oATSzG", "number", false),
      helocNumber: mca("col-Jw8ApcW", "number", false),
      helocStartDate: mca("col-1gA69gI", "date", false),
      utilityPaymentMonthlyAvg: mca("col-fDZD238", "number", true),
      energyPaymentMonthlyAvg: mca("col-kh-75Dj", "number", false),
      waterPaymentMonthlyAvg: mca("col-pxPZeyT", "number", true),
      waterBillQuarterlyAvg: mca("col-2r-MvrC", "number", false),
      waterAccount: mca("col-zGB5wLk", "string", false),
      waterPaymentDayOfMonthEarly: mca("col-qDmMkZJ", "number", false),
      waterPaymentDayOfMonthLate: mca("col-8jXuvG-", "number", false),
      waterPaymentFirstQuarter: mca("col-o1x-wv4", "string", false),
      garbagePaymentMonthlyAvg: mca("col-n_D8298", "number", true),
      garbageBillQuarterly: mca("col-jvoXCCB", "number", false),
      garbageBins: mca("col-8bq2kF6", "string", false),
      budgetsMonthly: mca("col-m1WV4qs", "number", true),
      maintenanceBudgetMonthly: mca("col-ZH_jQsz", "number", true),
      vacancyBudgetMonthly: mca("col-g9Wb4sq", "number", true),
      groundskeepingBudgetMonthly: mca("col-Dy2oTtx", "number", false),
      capexBudgetMonthly: mca("col-U2UTMN3", "number", true),
      perProperty: mca("col-ejzcxIv", "number", true),
      windowCountEstimate: mca("col-Qqr81ps", "number", true),
      roof: mca("col-dmwUWVp", "number", true),
      siding: mca("col-meHYx80", "number", true),
      furnace: mca("col-RmN-bYV", "number", true),
      waterHeater: mca("col-iUTHiqG", "number", true),
      flooring: mca("col-jN28F8U", "number", true),
      gutters: mca("col-zXJ8dhr", "number", true),
      interiorPaint: mca("col-RvWphY1", "number", true),
      refrigerator: mca("col-JPhrE1-", "number", true),
      range: mca("col-mqLl6c1", "number", true),
      clothesWasher: mca("col-V5JLenJ", "number", true),
      clothesDryer: mca("col-YjDwWCa", "number", true),
      dishwasher: mca("col-WJIYxcR", "number", true),
      windows: mca("col-XI0diwj", "number", true),
      cabinets: mca("col-mHi63ZH", "number", true),
      countertops: mca("col-BIpQMby", "number", true),
      landscaping: mca("col-h_ax2o8", "number", true),
      driveway: mca("col-55h3otY", "number", true),
      garageDoor: mca("col-Ndh1QvP", "number", true),
      insuranceProvider: mca("col-l8xxJGI", "string", false),
      insurancePolicyNumber: mca("col-F5FD5Fu", "string", false),
      insuranceRenewalDate: mca("col-LQlJfeM", "date", false),
      insuranceDeductible: mca("col-TEv3fQS", "number", false),
      insurancePremiumYearly: mca("col-4dwzFhA", "number", false),
      insurancePremiumMonthly: mca("col-f1sJZjS", "number", true),
      insuranceNotes: mca("col-fmolBdG", "string", false),
      outdoorWaterSource: mca("col-aBMOpUk", "string", false),
      gardenBedSqFt: mca("col-xgNmSP2", "number", false),
      gardenYardSqFt: mca("col-lLGiPJ-", "number", true),
      boulevardSqFt: mca("col-xPhh3bL", "number", true),
      kidsPlayBackYardSqFt: mca("col-HmSzSso", "number", false),
      lawnMowSqft: mca("col-tGD0Atd", "string", false),
      totalYardSqft: mca("col-AWQC6wR", "string", false),
    },
    paymentStandard: {
      name: mca("col-nXZJynE", "string", true),
      areaStandardName: mca("col-LLk1Rnw", "string", true),
      unitStandardName: mca("col-_d26cZW", "string", true),
      type: mca("col-UKMMk6d", "string", false),
      area: mca("col-PdIqODe", "string", false),
      year: mca("col-Vqa770-", "number", false),
      buildingType: mca("col-MciQOdX", "buildingTypeAndAny", false),
      bedroomCount: mca("col-ayrEE8U", "number", false),
      grossRent: mca("col-2NN5vKf", "number", false),
      gasHeating: mca("col-D5Mq2iT", "number", false),
      electricHeating: mca("col-Tk7-gts", "number", false),
      gasCooking: mca("col-TQGm_hh", "number", false),
      electricCooking: mca("col-usiVwX-", "number", false),
      gasWaterHeating: mca("col--PXRLlq", "number", false),
      electricWaterHeating: mca("col-bijwMhk", "number", false),
      otherElectric: mca("col-huaucO6", "number", false),
      waterSewer: mca("col-1GsKsEm", "number", false),
      trashCollection: mca("col-nAb9KBk", "number", false),
      districtEnergyHeating: mca("col-Z428AUE", "number", false),
      districtEnergyWaterHeating: mca("col-3DuCyZ1", "number", false),
      range: mca("col-TlqPiw-", "number", false),
      refrigerator: mca("col-kt86HvQ", "number", false),
    },
    tenantPros: {
      id: mca("col-DGFdnb-", "string", true),
      baseId: mca("col-8SCafE_", "baseId", false),
      firstName: mca("col-WrouvG3", "string", false),
      lastName: mca("col-7DS8uNK", "string", false),
      householdProspectId: mca("col-mhlI1zY", "string", false),
      incomeSources: mca("col-ldU8XUc", "string", false),
      incomeAmountMonthly: mca("col-eywE1hX", "number", true),
      issues: mca("col-amHKB33", "string", false),
    },
    householdProspect: {
      name: mca("col-pMwl8_N", "string", false),
      id: mca("col-cqj4thW", "string", true),
      baseId: mca("col-yuXxntB", "baseId", false),
      totalIncomeMonthly: mca("col-7k3rBt_", "number", true),
      dependents: mca("col-grW56Jj", "number", false),
      pets: mca("col-xXB1s_l", "string", false),
    },
    propertyProspect: {
      name: mca("col-S0OAuTp", "string", false),
      id: mca("col-OkqJWNn", "string", true),
      baseId: mca("col-CpPdodO", "baseId", false),
      parcelNumberPropertyId: mca("col-0lIe4Xa", "string", false),
      streetAddress: mca("col-jiFMS_y", "string", false),
      zipCode: mca("col-1y1a6Ff", "string", false),
      purchaseDate: mca("col-CW9RU72", "string", false),
      status: mca("col-8d9-nfv", "string", false),
      notes: mca("col-RoBy_Ut", "string", false),
      questions: mca("col-9qe82lZ", "string", false),
      yearBuilt: mca("col-lKMwqMV", "string", false),
      squareFeet: mca("col-DqT0mwa", "string", false),
      unitCount: mca("col-Ag6_m69", "string", false),
      furnaceCount: mca("col-rO5CGy0", "string", false),
      bedroomCount: mca("col-se5gANl", "string", false),
      pavedDrivewayCount: mca("col-jVdARRy", "string", false),
      garageDoorCount: mca("col-yYgBB3-", "string", false),
      purchasePrice: mca("col-FpFVeeU", "string", false),
      comission: mca("col-QZfm4Rg", "string", false),
      downPayment: mca("col-E6lZNsV", "number", true),
      startingRentalIncome: mca("col-IkgdHr9", "string", false),
      rentalIncome: mca("col-W0Q3tXm", "string", false),
      upfrontRepairCosts: mca("col-6cQlFxE", "string", false),
      nonUpfrontRepairCostsCapex: mca("col-MwxRVjG", "string", false),
      taxesAnnual: mca("col-gCG2Qie", "string", false),
      taxesMonthly: mca("col-VL874yL", "number", true),
      lawncareBudgetMonthly: mca("col-W1p8b1b", "number", true),
      insuranceMonthlyEstimate: mca("col-XcPapnZ", "number", true),
      insuranceAnnualEstimate: mca("col-ZvJvQRO", "number", true),
      utilityTotalMonthly: mca("col-e8TG1zH", "number", true),
      waterMonthly: mca("col-ybMqgFN", "number", true),
      waterQuarterly: mca("col-B3xgDQf", "string", false),
      garbageMonthly: mca("col-tbRXTof", "number", true),
      garbageQuarterly: mca("col-P29jxIM", "number", true),
      capexTotalMonthly: mca("col-BTE_UBh", "number", true),
      perProperty: mca("col-0E8iAux", "number", true),
      windowCountEstimate: mca("col-NnjG4Rt", "number", true),
      roof: mca("col-yT_a5B3", "number", true),
      siding: mca("col-5gg-upp", "number", true),
      furnace: mca("col-ioVtdjD", "number", true),
      waterHeater: mca("col-izjCpVm", "number", true),
      flooring: mca("col-JTSdHJz", "number", true),
      gutters: mca("col-WESKtQv", "number", true),
      interiorPaint: mca("col-iTcbFAe", "number", true),
      refrigerator: mca("col-Cmdyap_", "number", true),
      range: mca("col-9YxhUFQ", "number", true),
      clothesWasher: mca("col-wVSe7xy", "number", true),
      clothesDryer: mca("col-QJ-YTkC", "number", true),
      dishwasher: mca("col-hY1lYJN", "number", true),
      windows: mca("col-OQREydX", "number", true),
      cabinets: mca("col-IppyLV4", "number", true),
      countertops: mca("col-ICqtSww", "number", true),
      landscaping: mca("col-vqT2zOu", "number", true),
      driveway: mca("col-PLW0MYK", "number", true),
      garageDoor: mca("col-ZKkZ7-V", "number", true),
      vacancyBudgetMonthly: mca("col-ljxz0gR", "number", true),
      maintenanceBudgetMonthly: mca("col-i2fS7QU", "number", true),
      loanAmountBase: mca("col-nwkgCz7", "number", true),
      ltvRatio: mca("col-IYtSZG9", "string", true),
      interestRateYearly: mca("col-BB4uKDl", "number", true),
      interestRateMonthly: mca("col-Vw_TTgT", "number", true),
      loanTermYears: mca("col-HOqeQW_", "number", true),
      loanTermMonths: mca("col-Db1veZf", "number", true),
      closingCosts: mca("col-MF8af4Z", "number", true),
      sellerPaidClosingCosts: mca("col-XDKvGiw", "string", false),
      prepaidsAtClosing: mca("col-JHBkv_7", "string", false),
      principalAndInterestMonthly: mca("col-sxLq4Fz", "number", true),
      pmiMonthly: mca("col-5xHnDsz", "number", true),
      pmiAnnual: mca("col-i50sS9U", "number", true),
      pmiRate: mca("col-geWSWWp", "string", false),
      mortgagePaymentEstimatePiti: mca("col-ORerHse", "number", true),
      grossIncomeMonthly: mca("col-Yt4wh4q", "string", false),
      upfrontCosts: mca("col-Af68cx4", "number", true),
      upfrontCash: mca("col-SFb8uBJ", "string", false),
      propertyExpensesMonthly: mca("col-xvpvOfm", "number", true),
      financingExpensesMonthly: mca("col-X5gIiB8", "number", true),
      totalExpensesMonthly: mca("col-6yEJQ__", "number", true),
      cashFlowMonthly: mca("col-O8benrs", "number", true),
      cashFlowAnnual: mca("col-JNeUlZP", "number", true),
      roi: mca("col-2JBw-J8", "number", true),
      column96: mca("col--9HLvkP", "string", false),
      insurancePremiumYearly: mca("col-CjODhuL", "string", false),
      insurancePremiumMonthly: mca("col-B-TtJXJ", "number", true),
      insuranceProvider: mca("col-W3x5YSr", "string", false),
      insurancePolicyNumber: mca("col-VqbqKMH", "string", false),
      insuranceRenewalDate: mca("col-C62joYg", "string", false),
      insuranceDeductible: mca("col-gO6IMv8", "string", false),
      insuranceNotes: mca("col-6atkGeu", "string", false),
      utilityMonthlyTotal: mca("col-51JutEB", "number", true),
      waterPaymentMonthly: mca("col-8yIBK-J", "number", true),
      garbagePaymentMonthly: mca("col-pOB7Uhb", "number", true),
      energyPaymentMonthly: mca("col-Wq9kMAe", "string", false),
      waterAccountUnverified: mca("col-hH3A_7Z", "string", false),
      avgWaterBillQuarterly: mca("col-YbK6nes", "string", false),
      nextWaterPaymentDate: mca("col-SFdq1KP", "date", true),
      waterPaymentDate: mca("col-mK1W-mH", "string", false),
      avgGarbageBillQuarterly: mca("col-2Be_ZlX", "string", false),
      nextGarbagePaymentDate: mca("col-6sO5HEW", "string", false),
      garbagePaymentDate: mca("col-gi63OtF", "string", false),
      column97: mca("col-ptM7Jj7", "string", false),
      column1: mca("col-Egb6CCR", "string", false),
      mortgagePaymentMonthly: mca("col-p9lga5D", "string", false),
      mortgageHolder: mca("col-tvtnSGs", "string", false),
      mortgageNumber: mca("col-f0TEYw-", "string", false),
      mortgageBalance: mca("col-XSvoDWo", "string", false),
      ltv: mca("col-7HKVmK_", "string", true),
      pmi: mca("col-nto9Ao2", "string", false),
      helocAvailable: mca("col-P2LYFfH", "number", true),
      helocPaymentMonthly: mca("col--vU01TX", "string", false),
      helocHolder: mca("col--wsHtE_", "string", false),
      helocNumber: mca("col-RBLV5s_", "string", false),
      helocStartDate: mca("col-0dnlzzL", "string", false),
      helocLimit: mca("col-PhrD5vU", "string", false),
      helocBalance: mca("col-mNIXW1Y", "string", false),
      helocInterestRate: mca("col-XWTq4RX", "string", false),
    },
    materialCost: {
      item: mca("col-VH8n1pn", "string", false),
      v1Name: mca("col-zwyYm9d", "string", false),
      v1Cost: mca("col-UhEx93h", "number", false),
      v1Count: mca("col-f_qLF8F", "number", false),
      v2Name: mca("col-QdlP7OT", "string", false),
      v2Cost: mca("col-J9MMP8s", "string", false),
    },
    capex: {
      name: mca("col-wQVendk", "string", false),
      unitCost: mca("col-zeNzhyO", "number", false),
      propertyMultiplierName: mca("col-ZTAY92_", "string", false),
      lifespanYears: mca("col-U6_ZT0o", "number", false),
      lifespanMonths: mca("col-YqvaRuI", "number", true),
      preference: mca("col-4zmF0qs", "string", false),
    },
    hhLedger: {
      date: mca("col-9fBrgEn", "string", false),
      id: mca("col-K6z58MJ", "string", true),
      baseId: mca("col-K3ai6jl", "baseId", false),
      unit: mca("col-Gp-A2rX", "string", false),
      issuer: mca("col-6w2_q8O", "string", false),
      description: mca("col-NUiKLPH", "string", false),
      charge: mca("col-Uty4AVV", "string", false),
      payment: mca("col-qa5Sh_a", "string", false),
      amountOwed: mca("col-5pNKEjq", "string", true),
      notes: mca("col-zU1zrqH", "string", false),
    },
    addExpenses: {
      date: mca("col-vXNHJps", "string", false),
      propertyName: mca("col-_iOHEPj", "string", false),
      unitName: mca("col-OBqodd0", "string", false),
      billerName: mca("col-xp4RR28", "string", false),
      description: mca("col-pRON8SW", "string", false),
      amount: mca("col-sE7oAfr", "string", false),
      expenseCategory: mca("col-vgdpQaI", "expenseCategory", false),
      taxAdjust: mca("col-T6Qbxvk", "residenceTaxAdjust", false),
      receiptFormat: mca("col-yQtzinN", "receiptFormat", false),
      notes: mca("col-V7s3k7A", "string", false),
      householdToCharge: mca("col-nGxFx4D", "string", false),
      householdChargeLesserAmount: mca("col-OLIOifY", "string", false),
      hhChargeNotes: mca("col-6w_8wXP", "string", false),
      householdId: mca("col-Mx2BiCo", "string", true),
      id: mca("col-Wn1oOom", "string", true),
      baseId: mca("col-KDrkgbX", "baseId", true),
      propertyId: mca("col-7hwOnld", "string", true),
      unitId: mca("col-6mhn61V", "string", true),
      enter: mca("col-wipvQ46", "boolean", false),
      enterStatus: mca("col-jFOlWsa", "string", false),
    },
    addHhPaymentOnetime: {
      householdName: mca("col-JxtgYhJ", "string", false),
      portion: mca("col-9qc_UOo", "rentPortionName", false),
      description: mca("col-OBqwLsb", "chargeDescription", false),
      amount: mca("col-6Z-g6aN", "string", false),
      unitName: mca("col-YP9kC8o", "string", true),
      subsidyAgreementName: mca("col-Ligyt6Y", "string", false),
      id: mca("col-kU0tGW_", "string", true),
      baseId: mca("col-ryAlT3A", "baseId", true),
      householdId: mca("col-noXL_e_", "string", true),
      unitId: mca("col-fzBlkyl", "string", true),
      subsidyAgreementId: mca("col--w2ekts", "string", true),
      date: mca("col-u5S1p53", "date", true),
      detailsVerified: mca("col-Wb5wdwz", "string", false),
      payerCategory: mca("col-bXBsrNU", "payerCategory", false),
      paymentHhName: mca("col-Y7a0Yut", "string", true),
      subsidyProgramName: mca("col-DHgo-6o", "string", false),
      otherPayerName: mca("col-W7b2hGx", "string", false),
      paymentHhId: mca("col-TGUKG69", "string", true),
      subsidyProgramId: mca("col-XedCXAM", "string", true),
      otherPayerId: mca("col-OYsbh1q", "string", true),
      notes: mca("col-KTl705t", "string", false),
      enter: mca("col-6PNfr_e", "boolean", false),
      enterStatus: mca("col-OHc-nd9", "string", false),
    },
    addOccChargeOnetime: {
      date: mca("col-RcPqzF2", "date", true),
      householdName: mca("col-olQUfAZ", "string", false),
      amount: mca("col-wS5UkZR", "string", false),
      description: mca("col-fq3Wkwf", "chargeOnetimeDescription", false),
      unitName: mca("col-A18WumZ", "string", true),
      householdId: mca("col-S0LLFch", "string", true),
      unitId: mca("col-43FJGcv", "string", true),
      notes: mca("col-rEqlwlw", "string", false),
      id: mca("col-VG-Y2z7", "string", true),
      baseId: mca("col-wIsVf4Z", "baseId", true),
      enter: mca("col-auSNCDT", "boolean", false),
      enterStatus: mca("col-MuVUEGl", "string", false),
    },
    buildOccLedger: {
      dateLastRan: mca("col-56paOQ6", "date", false),
      householdIdLastRan: mca("col-h8wdhIm", "string", false),
      unitIdLastRan: mca("col-kN5w1ui", "string", true),
      occupancyName: mca("col-2IST_DW", "string", false),
      portion: mca("col-javENeZ", "rentPortionName", false),
      householdId: mca("col-9K87DiZ", "string", true),
      subsidyAgreementName: mca("col-pJqCDM_", "string", false),
      subsidyAgreementId: mca("col-bdXnDU7", "string", true),
      id: mca("col-qFYr3BR", "string", true),
      baseId: mca("col-amJZBHq", "baseId", true),
      enter: mca("col-0pQVFbo", "boolean", false),
      enterStatus: mca("col-NReu6z0", "string", false),
    },
    api: {
      id: mca("col-ohQJSZw", "string", true),
      baseId: mca("col-qqYLEfe", "baseId", false),
      ulsLastRan: mca("col-o3z5zKF", "string", false),
      ulsEnter: mca("col-H147sTm", "boolean", false),
      ulsEnterStatus: mca("col-2Hh5Tiv", "string", false),
      upcLastRan: mca("col-MVPM3jg", "string", false),
      upcStartMonth: mca("col-dBUrfx_", "date", false),
      upcEndMonth: mca("col-QIU-hI6", "date", false),
      upcHousehold: mca("col-JAZwV4Z", "string", false),
      upcHouseholdId: mca("col-jL103Fz", "string", true),
      upcEnter: mca("col-2CcZP7l", "boolean", false),
      upcEnterStatus: mca("col-7zKZtJP", "string", false),
      aepLastRan: mca("col-NpC_m7j", "string", false),
      aepEnter: mca("col-SkBfBWg", "boolean", false),
      aepEnterStatus: mca("col-lhC7IXV", "string", false),
      bhlLastRan: mca("col-s3TA0Js", "date", false),
      bhlLastRanHouseholdAndUnit: mca("col-koaPkot", "string", true),
      bhlHouseholdIdLastRan: mca("col-Bt_hiLJ", "string", false),
      bhlUnitIdLastRan: mca("col-YgNpwF1", "string", true),
      bhlHouseholdName: mca("col-qbSdWm7", "string", false),
      bhlHouseholdId: mca("col-L2Vwjlr", "string", true),
      bhlPortion: mca("col-66PEBlM", "rentPortionName", false),
      bhlSubsidyAgreementName: mca("col-7Dl8V9w", "string", false),
      bhlSubsidyAgreementId: mca("col--Cx2izo", "string", true),
      bhlEnter: mca("col-bBZV44s", "boolean", false),
      bhlEnterStatus: mca("col-VHVRiOc", "string", false),
      upcMode: mca("col-lw1GArS", "oneOccupancyOrAll", false),
    },
    year: {
      id: mca("col-MEgZSIX", "string", true),
      baseId: mca("col-TopsfpU", "baseId", false),
      name: mca("col-Z2qkqDh", "number", false),
      dayCount: mca("col-hZo8xT2", "number", true),
    },
    validationList: {
      transactionDescription: mca("col-My0v9xM", "string", true),
      chargeDescription: mca("col-4MRAohP", "string", true),
      chargeRecurringDescription: mca("col-LshlsTS", "string", false),
      chargeOnetimeDescription: mca("col-ZFyzZf4", "string", false),
      chargeReduceDescription: mca("col-FqR_6se", "string", false),
      rentPortionName: mca("col-LtgQHTi", "string", false),
      paymentType: mca("col-9CulPu2", "string", false),
      payerCategory: mca("col-_DwO2R3", "string", false),
      paymentAllocateWhat: mca("col-umhxhPg", "string", false),
      expenseCategory: mca("col-u0Fstxj", "string", false),
      expenseCategoryTaxable: mca("col-9XaRDGK", "string", true),
      expenseCategoryBank: mca("col-k3_mD_q", "string", true),
      residenceTaxAdjust: mca("col-08YH-3Z", "string", false),
      receiptFormat: mca("col-StBJQCC", "string", false),
      firstOfEachMonthThisYear: mca("col-sgLi6Pa", "date", true),
      januaryQuartersThisYear: mca("col-iRu6A9m", "date", true),
      februaryQuartersThisYear: mca("col-ZOaq1Tm", "date", true),
      marchQuartersThisYear: mca("col-MZIxCW9", "date", true),
      yesOrNo: mca("col-d5gC0K8", "string", false),
      buildingType: mca("col-0eGzKFb", "string", false),
      buildingTypeAndAny: mca("col-jJBNGWq", "string", true),
      oneOccupancyOrAll: mca("col-qpxkX-L", "string", false),
    },
    config: {
      activePaymentStandardYear: mca("col-mW2UEKf", "number", false),
      domLateFeeCharged: mca("col-ZsjeOd2", "number", false),
      columnIdRowIdxBase1: mca("col-4ySoLne", "number", false),
      idDelimiter: mca("col-zR-sehH", "string", false),
      headerRowIdxBase1: mca("col-hOXiFmz", "number", false),
      topBodyRowIdxBase1: mca("col-DZ4VSLw", "number", false),
    },
    allTableAttributes: {
      id: mca("col-90lQMkS", "string", true),
      baseId: mca("col-_NrBHfg", "baseId", false),
      sheetGid: mca("col-fqCrMdm", "number", false),
      idPrefix: mca("col-iqW3fCT", "string", false),
      tableName: mca("col-ssYwA1T", "string", false),
    },
    allColumnAttributes: {
      tableName: mca("col-U6y6xUt", "string", false),
      columnId: mca("col-K9DptS1", "string", false),
      isFormula: mca("col-F2caCWz", "boolean", false),
      valueName: mca("col-PeplPjS", "string", false),
      columnName: mca("col-wHrc1Q3", "string", false),
    },
    test: {
      column5: mca("col-Oy9WtzQ", "string", true),
      id: mca("col-8wOXbE6", "string", true),
      baseId: mca("col-uHm7dGg", "baseId", false),
      number: mca("col-kJ47IXM", "number", false),
      dropdown: mca("col-4_IzNLS", "yesOrNo", false),
      date: mca("col--K2Vvyh", "date", true),
    },
    variable: {
      today: mca("col-07PPMWD", "date", true),
      "15thOfThisMonth": mca("col-yfTbEv-", "date", true),
      "2MonthsOut": mca("col-_P8yYla", "date", true),
    },
    valueName: {
      valueName: mca("col-35A6jyC", "string", true),
    },
  } as const,
);

export type AllColumnAttributes = typeof allColumnAttributes;

export type ColumnName<TN extends TableNameSimple = TableNameSimple> =
  keyof AllColumnAttributes[TN];

export type TableColumnAttributes<TN extends TableNameSimple> =
  AllColumnAttributes[TN];

export type ColumnAttributes<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
> = TableColumnAttributes<TN>[CN];

export type ColumnValueName<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
> = ColumnAttributes<TN, CN>["valueName" & keyof ColumnAttributes<TN, CN>];

export type ColumnValueAttributes<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
> = ValueAttributes<ColumnValueName<TN, CN> & ValueName>;

export type ValidateVarb<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
> = ValidateValue<ColumnValueName<TN, CN> & ValueName>;

export type ColumnValue<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
> = Value<ColumnValueName<TN, CN> & ValueName>;

export type TableValues<
  TN extends TableNameSimple,
  VNS extends ColumnName<TN> = ColumnName<TN>,
> = {
  [CN in VNS]: ColumnValue<TN, CN>;
};

export function getTableColumnNames<TN extends TableNameSimple>(
  tableName: TN,
): ColumnName<TN>[] {
  return Obj.keys(allColumnAttributes[tableName]);
}

const allColumnAttributesFlat = Obj.flattenTwoLevels(allColumnAttributes);
type AllColumnAttributesFlat = typeof allColumnAttributesFlat;
type ColumnNameFullSimple = keyof AllColumnAttributesFlat;
type ColumnNameFull<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
> = CombineStringsWithFlat<TN, CN & string>;

export function getColumnAttribute<
  TN extends TableNameSimple,
  CN extends ColumnName<TN>,
  K extends keyof ColumnAttributes<TN, CN>,
>(tableName: TN, columnName: CN, key: K): ColumnAttributes<TN, CN>[K] {
  return allColumnAttributes[tableName][columnName][key];
}
