import {
  cellValueNames,
  type CellValueName,
  type CellValueNameToValue,
} from "../1.0 Configs/0.0 ConfigPrecursors";
import {
  configValueNames,
  type ValueConfigValues,
} from "../1.0 Configs/4.0 valueConfig";
import { Dat } from "../utils/Dat";
import type { Merge } from "../utils/Obj/merge";
import { valS } from "../utils/validation";
import {
  vsc,
  type ValueSchemaBase,
  type ValueSchemaKey,
} from "./3.0 valueSchema";
import { makeSchemasFromValueConfig } from "./3.1 configValueSchemas";

const valueNames = ["id", ...cellValueNames, ...configValueNames] as const;
type ValueNameSimple = (typeof valueNames)[number];

interface BaseValues extends CellValueNameToValue {
  id: string;
}

type AllValues = Merge<BaseValues, ValueConfigValues>;
type AllValuesOrEmpty = {
  [VN in ValueNameSimple]: AllValues[VN] | "";
};

export type ValueSchemas = {
  [VN in ValueNameSimple]: ValueSchemaBase<AllValuesOrEmpty[VN]>;
};
export type ValueName<V extends ValueNameSimple = ValueNameSimple> = V;
export type ValueSchema<VN extends ValueName = ValueName> = ValueSchemas[VN];

const valueSchemas: ValueSchemas = {
  id: vsc({
    type: "" as string,
    makeDefault: () => {
      throw new Error(
        "Attempted to make default value for an ID column from valTraits; it should be generated by a sheet schema.",
      );
    },
    strictValidate: valS.validate.string,
  }),
  string: vsc({
    type: "" as string,
    makeDefault: () => "",
    strictValidate: valS.validate.string,
  }),
  number: vsc({
    type: 0 as number | "",
    makeDefault: () => "" as const,
    strictValidate: valS.validate.number,
  }),
  boolean: vsc({
    type: false as boolean | "",
    makeDefault: () => false,
    strictValidate: valS.validate.boolean,
  }),
  date: vsc({
    type: "" as number | "",
    makeDefault: () => Dat.dateToSerial(new Date()),
    strictValidate: valS.validate.number,
  }),
  ...makeSchemasFromValueConfig(),
} as const;

export type ValueTrait<
  VN extends ValueName,
  K extends ValueSchemaKey,
> = ValueSchema<VN>[K];

export function getValTrait<
  VN extends ValueNameSimple,
  K extends ValueSchemaKey,
>(valueName: VN, key: K): ValueSchema<VN>[K] {
  return valueSchemas[valueName][key] as ValueSchema<VN>[K];
}

export function getCellValTrait<
  VN extends CellValueName,
  K extends ValueSchemaKey,
>(valueName: VN, key: K): ValueSchema<VN>[K] {
  return valueSchemas[valueName][key] as ValueSchema<VN>[K];
}

export type Value<VN extends ValueName = ValueName> = ValueTrait<VN, "type">;
